- terraform/cross-account-IAM/data-eng-rds-dev.tf
This PR is to enable probation microservices to write data dumps into an Analytical Platform (AP) S3 bucket.
Raised on behalf of Jacob Browning (a data engineer working on probation within the AP).
> Enable write access to AP S3 bucket

- terraform/cloud-platform-network/main.tf
Bump current version of the flow log module to the latest. 
https://github.com/ministryofjustice/cloud-platform-terraform-flow-logs/releases/tag/1.3
> bump version of flowlogs module, added condition on is_enabled

- terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-account/main.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-account/modules/automated-tests/main.tf
terratest user is used for unit/integration testing our terraform modules inside the cloud-platform-ephemeral-test account.
> terratest user in the cloud-platform-ephemeral account

- terraform/cloud-platform-components/components.tf
- terraform/cloud-platform-eks/components/components.tf
Removed Helm provider deprecated resources. More info in https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/71
> Updated Prometheus component to latest

- terraform/cloud-platform-components/main.tf
This PR will add two null resources in TF to add the Cloud Platform default NS annotations and Labels to the kube-system namespace.
> Add default annotations and labels for ks ns

- .gitattributes
- .gitignore
Because we need to find the way how to store the seed state (the one used to create the initial S3/DybamoDB table), it feels a good idea to store it encrypted within the repo instead of ignoring them.
> Default to encrypt *.tfstate rather than ignoring it

- terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-account/main.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-account/modules/automated-tests/main.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-account/modules/automated-tests/variables.tf
Some AWS_* creds are required by Github actions in order to execute unit tests against terraform modules.
> AWS Ephemeral account credentials required by Github actions

- terraform/cloud-platform-components/components.tf
WHAT
New version of the monitoring module with kibana proxies
WHY
Proxies use to be in env repo as yaml code, now in managed TF code. (Applies in live-1 only)
> New monitoring release with kibana proxies

- makefile
Several of our runbooks include running `make tools-shell`, so this needs to be kept up to date with the latest release.
We could also do something like this:
```
curl https://api.github.com/repos/ministryofjustice/cloud-platform-tools-image/releases/latest | grep tag_name | sed 's/.*: "\(.*\)".*/\1/'
```
But building that into a make target would lead to a file that was difficult to read, so it's probably simplest to keep bumping the version manually
> Use tools-image 1.27 in `make tools-shell`

- terraform/cloud-platform-account/main.tf
- terraform/cloud-platform-account/outputs.tf
- terraform/global-resources/elasticsearch.tf
- terraform/global-resources/main.tf
To avoid duplication of work and to ensure resources aren't overwritten I have removed the additional notify slack module call from the elasticsearch terraform. This will now be created by the aws-baselines module in the cloud-platform-account terraform and consumed by elasticsearch.
> Add slack SNS topic fix to Elasticsearch and accounts modules

- terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-account/main.tf
After here it will be implemented within the cloud-platform main account.
> Using latest kops module within ephemeral test account

- terraform/global-resources/saml.tf
We are using `jq`, `bash` & `curl` when we can just use HTTP data resource to download/query an endpoint.
> Removed external dependencies on terraform

- terraform/cloud-platform/main.tf
- terraform/cloud-platform/outputs.tf
There is state dependency within `cloud-platform/` folder. This PR removed it and take advantage of AWS data resources
> Removed terraform_remote_state dependency

- terraform/cloud-platform-components/components.tf
It contains Helm repository inline. More information in https://github.com/ministryofjustice/cloud-platform-terraform-certmanager/pull/17
> Update cert-manager to latest version

- terraform/cloud-platform-components/components.tf
WHAT
Remove failover test ingress controller - ingress_controllers_k8snginx_fallback
WHY
This was created for the major nginx ingress upgrade and used for testing. As this work is complete this is no longer required.
> Remove failover test ingress controller

- makefile
This image uses terraform 0.14 which is current version used for infrastucture
Add KUBE_CONFIG_PATH env variable. Latest Kubernetes provider expects a path for kubeconfig file.
> Bump tools image to use 1.31.

- terraform/cloud-platform/main.tf
When creating test clusters `terraform plan` throw error ```Error: no matching Route53Zone found
on .terraform/modules/bastion/main.tf line 25, in data "aws_route53_zone" "selected":
25: data "aws_route53_zone" "selected" {```
This is because the bastion module data.aws_route53_zone.selected expects the zone to be created. And for some reason  terraform cannot infer dependency calculations.
> Add explicit dependency for creating route53

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-components/components.tf
More details in this PR: https://github.com/ministryofjustice/cloud-platform-terraform-certmanager/pull/18
> Cert manager upgrade for eks and ephemeral-test accounts

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-components/components.tf
- terraform/cloud-platform-components/components.tf
Cpu high critical change irate to rate - use latest monitoring module (1.6.2 to 1.6.3)
> Cpu high critical change irate to rate - use latest monitoring module

- terraform/cloud-platform-components/components.tf
This has the chart version upgrade to 1.2.0.
Related to: https://github.com/ministryofjustice/cloud-platform/issues/2771
> Upgrade certmanager to release 1.1.0

- terraform/cloud-platform-components/components.tf
Upgrade already done in EKS and also ran [eks integration tests](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/eks-integration-tests/builds/618) to ensure everything is fine.
> Update external-dns helm chart in live-1 to latest

- terraform/cloud-platform-components/components.tf
As discussed here, we are giving a try at removing the affinity rules for Prometheus, It means the pod is going to be scheduled in a normal node.
Before applying this it is important to change Prometheus's pingdom health check, so it doesn't trigger when node-recycling triggers
> Removed affinity rules for Prometheus

- terraform/cloud-platform-components/components.tf
Fixed missing YAML header (resource). More info in https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/90/files
> Update components.tf (Prometheus)

- terraform/cloud-platform-components/components.tf
It is too heavy for the nodes and consumes too many resources for the nodes. We just saw a spike of CPU to 99%. 
At least we tried
> Revert Prometheus - affinity rules again 

- .gitignore
We have taken the decision to not commit the version hcl lock file to
git.
> Add hcl lock to git ignore

- smoke-tests/spec/ingress_spec.rb
Enable nginx ingress test to investigate intermittent issues
> Enable nginx ingress smoke tests

- smoke-tests/spec/cert_manager_spec.rb
- smoke-tests/spec/external_dns_spec.rb
Enable cert-man and exDNS tests to check if stability of other test changes
> Enable cert-man and exDNS tests

- terraform/cloud-platform/main.tf
The new release of the bastion module uses ubuntu as the default username, this happens because kops 1.18 uses ubuntu as default node image
> Fixing username for kops nodes

- terraform/cloud-platform-components/main.tf
This is not being used, I can't find any reference within the files
> Removed global's terraform_remote_state

- create-cluster.rb
What problem does this PR fix
---
Before this PR we had a problem where bootstrapped EKS clusters would use the `eks.privileged` pod security policy. This policy essentially makes PSP's redundant as all pods will assume it, which allows them to do anything they like (i.e. priv escalation). We have our own carefully thought out Pod Security Policies that are easily applied to a kOps cluster but not EKS.
Why merge this PR
---
Merging this PR means all future EKS clusters will use our own Pod Security Policies.
How
---
It's not an elegant fix, but it amends the `create-cluster` script to do the following:
- Delete the old eks.priv psp
- Apply our own psps
- Recycle every pod in the cluster
The important thing to note here is that at point of execution we have a minimal set of pods in the …
> Add PSP tactical fix to create-cluster script

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
This is to modify the cert-manager deployment with the correct
filesystem permissions, so the serviceaccount token can be read.
Information related to it:
https://github.com/cert-manager/website/pull/456/
> Add security context with fsgroup for eks

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/k8s-resources.tf
This will allow re-applying the psp if the resources already exists.
When creating test clusters, it throw the below error. 
```Error: Error running command 'kubectl create -f ./resources/psp/pod-security-policy.yaml': exit status 1. Output: Error from server (AlreadyExists): error when creating "./resources/psp/pod-security-policy.yaml": podsecuritypolicies.policy "privileged" already exists```
Because the psp are created before installing components to remove the eks.privileged, it cannot be created again when installing components. Refer (https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1174).
> Use apply instead of create

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This should fix the Prometheus operator issue in the manager cluster. It basically reduces the resources quotas set for live-1 (we are in manager, we don't need that amount of memory + we don't have large node groups)
> Updating Prometheus Operator in Manager 

- terraform/aws-accounts/cloud-platform-aws/vpc/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/variables.tf
WHAT
This PR adds live cluster tags to AWS VPC and all 6 subnets owned by live-1 
WHY
This is required so live cluster can create LB using the subnets created by live-1 cluster. Live is installed within live1 vpc.
The tag for the VPC is not technically required anymore but will be removed in the future. 
https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html - VPC tagging
> Add live cluster tags to live-1 VPC

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Also moved `manager-concourse` down to the end of the list for clarity.
> Add cloud-platform-admin user to eks users

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/outputs.tf
This PR removes all conditionals and also uses the new auth0 module version, which simplifies all `locals`
This PR also removes the bastion host, which we don't need on EKS (anyway we already have the kops one within the live-1 VPC)
> Refactor code - remove almost all conditionals

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/variables.tf
Overview
---
This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/2854 and relates to the creation of a new production grade cluster named `live`. This cluster's name is deliberately vague to ensure future upgrades and iterations don't change name. It requires a change to the cluster, main and vpc terraform HCL in this repository. At the end of this PR, we should have a `live` production EKS cluster bootstrapped and initial components installed.
What's in this PR
---
We would like to create as close to
`live-1` as possible. `Live-1` is currently running 19 worker nodes and
three masters. At the start of `Live` it will need a different instance
type `r5.xlarge` for mem optimisation but we can keep the instance count
the same and utilise the out of the box …
> Create node size terraform map

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf
In order to enable externalDNS test to run in all clusters, we must give it access to integrationtest hostzone.
> Enable access to integrationtest hostzone in all clusters 

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
As we are migrating to eks, this will add mod-sec ingress controller in EKS
So users need modsec can use this.
> Add mod-sec ingress controller for eks

- tests/e2e/config.yaml
- tests/e2e/external_dns_test.go
- tests/e2e/fixtures/external-dns-ingress.yaml.tmpl
- tests/go.mod
- tests/pkg/config/config.go
- tests/pkg/config/external_dns.go
- tests/pkg/config/nginx_ingress_controller.go
- tests/pkg/helpers/externaldns.go
This closes https://github.com/ministryofjustice/cloud-platform/issues/2920 adding support to check external-DNS component in Kubernetes cluster. 
The check consist in:
1) Create an ingress resource 
2) Wait until external-DNS creates in Route53
3) Ensure the A records exist in Route53 with the domain specified in Step 1 ingress record
> externalDNS e2e tests in Golang

- smoke-tests/spec/daemonsets_spec.rb
The label used for eks calico is different to the one used in kops,
this cause tests to fail.
> Fix calico eks tests

- tests/e2e/files_exist_test.go
- tests/e2e/live.yaml
- tests/go.mod
- tests/pkg/config/config.go
This PR includes a new generic field (`filesExist`) which performs an HTTP check of the status code, if it doesn't match `200` the test fails.
> Adding authorized keys test - made generic http file checker

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
In order to achieve updates from simple records to weight records we must upgrade external-dns. Otherwise we face https://github.com/kubernetes-sigs/external-dns/issues/1411.
> Update external-dns to latest

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
In order to achieve updates from simple records to weight records, we must upgrade external-dns.
> Updated external-dns to latest in live-1

- tests/config/live.yaml
- tests/e2e/namespaces_test.go
Overview
---
This connects to https://github.com/ministryofjustice/cloud-platform/issues/2919 and relates to the creation of a namespace annotation test in EKS clusters. We already have a ns-annotation smoketest for live-1 https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/main/smoke-tests/spec/namespace_annotations_spec.rb but this is very specific to live-1.
What's in this PR
---
This PR contains:
- a new Ginkgo test within the Namespace description. 
- a slight wording tweak on the other namespace test.
- removes kiam from list of expected daemonsets in the live cluster.
Why do we want to merge it
---
All namespaces (including `kube-system`) should contain annotations specific to the cluster. This test will confirm if a namespace has been created manually or …
> Add namespace annotation test

- tests/Dockerfile
- tests/makefile
This will be useful when we decide to trigger pipelines that execute the e2e tests. 
- Good news: container can be as small as 40MB
- Bad news: To connect to EKS (not the kops side) you need `aws-cli` installed which adds so many MBs of size
Total image size: 94MB 
https://hub.docker.com/repository/docker/ministryofjustice/cloud-platform-tests/tags?page=1&ordering=last_updated
> Dockerfile and makefile for e2e testing

- smoke-tests/spec/cert_manager_spec.rb
The  cert-manager spec is consistently failing because it failed to resolve the DNS for host created. Even though the ingress was created in <90s and the external DNS entry created in A record around 114s, It takes some time to get the DNS resolved.
When ran locally, it passed when the wait time is 240. It did failed sometimes when set to 180.
> cert-manager test - Increase waiting time after creating ingress 

- smoke-tests/spec/fixtures/helloworld-deployment-modsec.yaml.erb
- smoke-tests/spec/ingress_controller_spec.rb
- smoke-tests/spec/ingress_spec.rb
- smoke-tests/spec/modsec_spec.rb
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
```
ingress controllers
default
.    returns 200 for http get
.    does not return a server header
eks
.    returns 302 for http get
.    does not return a server header
nginx ingress
when ingress is not deployed
.    fails http get
when ingress is deployed using 'nginx' ingress controller
.    returns 200 for http get
when ingress is deployed using 'modsec01' ingress controller
.    responds to http get
when ingress is deployed with invalid syntax
.    is rejected by the admission webhook
Testing modsec on ingress class: 'modsec01'
when modsec is deployed
when the url is benign
.      request succeeds
when the url is malicious
.      request is blocked
when modsec is disabled
when the url is benign
.      request succeeds
when the url is malicious
.      request succeeds
Finished in 4 …
```
> remove integration ingress

- smoke-tests/spec/ingress_controller_spec.rb
Integration-tests for live-1 is run excluding tags 'eks-manager', 'cluster:test-cluster-only'. Hence live-1:false will not be excluded from running in live-1
> Change tag to test-cluster-only

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This release fixes an issue where an ACME Certificate, with a long name (52 characters or more)
jetstack/cert-manager#3866.
Ticket related to it:
ministryofjustice/cloud-platform#2976
> Upgrade cert-maanger to v1.4.0

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/outputs.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/variables.tf
add null resource to associate the identity provider (Auth0) to the cluster
add  null_resource wait for the association to be active
This is required for authenticate to the cluster using OIDC via Auth0.
Related to: https://github.com/ministryofjustice/cloud-platform/issues/2945
> Add null resource associate Identity Provider to cluster 

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/outputs.tf
WHAT
Change node_type to a list and add a secondary instance type if first is not available for any reason.
Increase the number of nodes on live to up the limit on available IP addresses = pods
WHY
A list allows to choose more than one node type as we have had a previous incident when a node type was not available in a particular AZ.
IP address limits (pods) per node_type - https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt
> Make node_type a list and change instance type for clusters

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/outputs.tf
Because external_subnet_ids are not in eks cluster folder outputs, the terraform state file has this information missing. Hence, when comparing the list of subnets in vpc and determine whether they are orphaned from the HOODAW reports page, it shows the subnets as orphaned for clusters which are available
> Output external_subnets_ids for eks.

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
Add multiple modules depends on for OPA to install it at the end.
Upgrade cert-manger chart to latest which got a fix for null resource dependency
> Fix create cluster dependency for kops and eks

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
As cert-manager module contains creating cluster issuer, and the ingress controller module creating default cert depends on it.
> Added depends on cert-manager for ingress-controller

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Upgrade to chart v3.34.0 for both default and modsec ingress controller,
this is to have both controllers running on the same version.
For modsec ingress controller, remove controller name to fix NLB recreation and validation webhook issue.
More info:
https://github.com/ministryofjustice/cloud-platform/issues/2989#issuecomment-866103729
Related to ticket:
https://github.com/ministryofjustice/cloud-platform/issues/2994
> Upgrade default & modsec Ingress-controller for EKS

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
Upgrade to chart v3.34.0 for both default and modsec ingress controller,
this is to have both controllers running on the same version.
For modsec ingress controller, remove controller name to fix NLB recreation and validation webhook issue.
More info:
https://github.com/ministryofjustice/cloud-platform/issues/2989#issuecomment-866103729
Related to ticket:
https://github.com/ministryofjustice/cloud-platform/issues/2994
> Upgrade default & modsec Ingress-controller for Kops

- destroy-cluster.rb
As we will be migrating to EKS cluster, we need to create more EKS clusters to test and destroy them later.
We have create cluster script that supports both KOPS and EKS, now updated the destroy cluster script to support both KOPS and EKS.
> Update destroy-cluster script to support EKS

- smoke-tests/spec/kiam_spec.rb
Error 
```
Aws::IAM::Errors::EntityAlreadyExists:
A policy called integration-test-kiam-policy already exists. Duplicate names are not allowed.
```
seen in a number of integration tests. I recommend we skip this test until the morning.
> Skip the kiam namespace until we can fix an issue

- smoke-tests/spec/kiam_helper.rb
- smoke-tests/spec/kiam_spec.rb
The list_policies started failing with 
`Aws::IAM::Errors::EntityAlreadyExists:
A policy called integration-test-kiam-policy already exists. Duplicate names are not allowed.`
because the policy expected is not in the first set of responses. This PR change will call list_policies until all policies are returned and hence the test pass.
> Add paginated list_policies responses

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/variables.tf
This is to include *.apps.live-1, so users can use apps.live-1 domain, when migrating to eks-live cluster.
This is related to the issue:
https://github.com/ministryofjustice/cloud-platform/issues/3013
> Update default certificate of "live" cluster

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/k8s-resources.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/resources/helloworld-deployment.yaml
This is to check if the infrastructure apply pipeline is, using the right kubectl context to apply null resources.
> Create null resource to test default cert incident

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
This contains changes for the live domain filter.
More info:
https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/pull/17
> Update external-dns to use the latest version.

- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
This is to include *.apps.live-1 for "eks-live" cluster, so users can use apps.live-1 domain, when migrating to eks-live cluster.
This is related to the issue:
https://github.com/ministryofjustice/cloud-platform/issues/3013
> Update ingress-controller module to latest version

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/variables.tf
This change to push logs from eks-live fluent-bit to live AWS-ES, with separate index for a cluster.
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/3006
> Set up logging for eks-live cluster

- smoke-tests/spec/concourse_spec.rb
This skips concourse tests in the eks-live cluster, as concourse only runs in manager cluster.
> Skip concourse tests for eks-live

- terraform/global-resources/elasticsearch.tf
We are using a single elastic search for multiple clusters (live-1, manager and eks-live), scale up AWS live ES to accommodate the load.
ref for ES pricing:
https://aws.amazon.com/elasticsearch-service/pricing/
As we are going to create a separate index for all the clusters, fluent-bit by default push 1-week logs with the new index.
scaled up to "r5.4xlarge.elasticsearch",  observing for 1-2 weeks we need to scale up or down depending upon the load.
> Scale up live aws elastic-search.

- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
This is to maintain a separate index for clusters.
Related to:
ministryofjustice/cloud-platform#3006
> Update logging module to use the latest

- smoke-tests/spec/logging_spec.rb
This is to fix the logging test by updating the right search_url, as ES indices are now updated by adding cluster name to the suffix.
> Fix logging rspec tests

- smoke-tests/spec/logging_spec.rb
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
The latest module got a fix for elastic search-curator.
Update logging RSpec tests to run on all clusters, this excludes test clusters, as logs don't get to ES for test clusters.
Not moving the curator job to eks-live yet, as clearing completed jobs is working as expected in eks.
- We don't have TTLAfterFinished, as it only supports EKS from K8's v.1.20.
- Jobs are not deleted as configured in "failed_jobs_history_limit" and "successful_jobs_history_limit"
> Update the logging module to use the latest.

- tests/e2e/modsec_ingress_test.go
- tests/makefile
Even when the endpoint returns 200 it doesn't mean modsec ingress controller is ready. It takes some seconds extra (even if the website is serving 200s) to be enabled.
This was determined by testing/tuning the values of the timeouts and steps between tries.
It was also removed the DNS check, which is not needed here We have a wildcard DNS value for the hostzone.
> Fix non-determinic failure with modsec integration test

- tests/e2e/modsec_ingress_test.go
Somehow, even if modsec returns 200's for the site, it doesn't mean it is acting as WAF. It takes a small amount of time (less than 2 mins) to get properly ready. This PR adds two minute wait (can be less but requires more testing/tuning) before doing the check for bad URLs and modsecurity.
> Explicit sleep for nginx modsec test

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This release got the latest image, as the pinned version is removed in this module
> external-dns-upgrade to latest

- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
This change is already applied. It updated external-dns to the latest docker image (the one defined by the helm chart by default)
> Upgraded external-dns to latest version

- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/versions.tf
Used the kubectl provider (instead of null resource) to add the PrometheusRule
The metrics are enabled directly by the helm chart.
The end to end was tested in test cluster: cp-2307-1158
> Add metrics and alerts to externalDNS in live-1

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/versions.tf
Used the kubectl provider (instead of null resource) to add the PrometheusRule
The metrics are enabled directly by the helm chart.
The end to end was tested in test cluster: cp-2307-1158
>  Add metrics and alerts to externalDNS in manager

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Because external-dns adds an alertRule, it required CRD. It means Prometheus must be installed first.
> Add external-dns dependence on Prometheus

- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
Because external-dns adds an alertRule, it required CRD. It means Prometheus must be installed first.
> Add external-dns dependence on Prometheus (kops)

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
WHAT
Upgrade OPA Module to 0.0.12
WHY
This module has a fix for the invalid webhook certificate error when on kubernetes 1.19
> Upgrade OPA Module to 0.0.12

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/k8s-resources.tf
The storage class io-expand, used bu Prometheus, is missing in EKS. If we want to be consistent with live-1 and with Prometheus it should be added
> Add missing storage class in EKS

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Update to the latest Prometheus/Monitoring module in order to use io1-expand storage class in EKS side.
> Update monitoring/prometheus module in components

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
- As we are seeing multiple issues using null_resource, replacing this with  kubectl_manifest.
- Add '*.apps.<cluster_domain_name>' to all clusters
- Add '*.apps.cloud-platform.service.justice.gov.uk' to live_clusters
> Replace "null_resource" with "kubectl_manifest"

- smoke-tests/spec/fixtures/external-dns-ingress.yaml.erb
- smoke-tests/spec/fixtures/helloworld-deployment-modsec.yaml.erb
- smoke-tests/spec/fixtures/helloworld-deployment.yaml.erb
- smoke-tests/spec/fixtures/invalid-nginx-syntax.yaml.erb
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/main.tf
- tests/e2e/fixtures/external-dns-ingress.yaml.tmpl
- tests/e2e/modsec_ingress_test.go
- tests/e2e/nginx_ingress_test.go
Update cloud-platform components to remove "apps", this is in the DNS name and add the external-dns annotation.
This is related to the ticket:
https://github.com/ministryofjustice/cloud-platform/issues/3116
> Update cloud-platform components to remove "apps"

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
- This is to add external_dns annotation as we are going to apply,
OPA policy to restrict ingress which doesn't have these annotations.
- Remove "apps" from the hostname
> Add external_dns annotation and remove apps from host

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- This is to deny ingress creation with out external_dns annotation.
-  Terraform count condition to enable this policy,
as only get applied to live-eks.
-  Create tests for external-dns annotation check
https://github.com/ministryofjustice/cloud-platform/issues/3008
> Create Policy to check external-dns annotation

- tests/e2e/modsec_ingress_test.go
- tests/e2e/nginx_ingress_test.go
This is failing on external-dns annotations:
error: unable to decode
> Fix go tests which have external-dns annotation

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- tests/makefile
The v17.1.0 have an issue(https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1446)
Where each plan will have a change for the templates, this causes our divergence pipeline to fail
Pinned the version until this fix get merged
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1447
> Pin launch_template_version for EKS module

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf
This will reduce the chances of making mistakes with kubectl context while we do `terraform apply/destroy`
> K8S credentials loaded dynamically depending on workspace

- smoke-tests/spec/docker_registry_cache_spec.rb
The docker-registry-cache integration test is failing regularly, Increasing the sleep time to wait for logs, before comparing the logs.
Tested this locally multiple times, increasing the delay, not seen any failure.
> Increase the sleep time for docker-registry-cache test

- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
Why:
[Release new version of OPA#3091](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/3091)
(ensure the latest tag is used in our live-1 infrastructure).
```
~/projects/cloud-platform-infrastructure/smoke-tests
```
> latest-tag-opa-live-1

- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/main.tf
The monitoring module in live-1 fails when it is upgraded from module v1.6.6 to the latest version(v1.7.5)
Upgrade live-1 monitoring module to use v1.7.0, this is to do incremental apply to live-1.
This module contains changes:
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/93
> Upgrade live-1 monitoring module to use v1.7.0

- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
Implement URLs for monitoring stack
This is in light of the EKS migration
-  Add external-dns annotation to grafana/kibana/prometheus/alertmanager
- Configure cluster-specific and live_domain hosts in ingress, for Prometheus and Alertmanager
- Create ingress to redirect_grafana while accessing live_domain, cannot set up as we did for Prometheus and alert manager as GF_SERVER_ROOT_URL supports only one URL.
> Upgrade monitoring to use the latest module

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
concourse and certmanager null resources were migrated to use kubectl provider.
> Migrated k8s null_resources to kubectl provider

- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
Using `kubectl` provider instead of `null_resources`
> [kops] Update cert-manager to latest

- smoke-tests/spec/ingress_controller_spec.rb
By removing ".apps" for hostname
"Test ingress controllers default" smoke test, which is specific for test clusters is failing, this is because we updated the cloud-platform applications to remove ".apps" in the hostname.
> Fix test ingress controllers default smoke test

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This will fix index issue, as kubernetes_cluster_live*, also serves kubernetes_cluster_live-1*.
> Use cluster name as prefix for Index patterns

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/k8s-resources.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/k8s-resources.tf
We don't mind tests clusters get created with this _ServiceAccounts_ because they don't do any harm. 
Removing the `count` makes the code more readable and test clusters more similar to production ones.
> Remove counts/condition in concourse's ServiceAccounts

- .github/workflows/commit-message-checker-with-regex.yaml
It is required to be stricter with commit messages, we're giving a try to enforce some of the policies using a GitHub action
This closes: https://github.com/ministryofjustice/cloud-platform/issues/3004
> Adding commit messages checker

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/variables.tf
This commit connects to
https://github.com/ministryofjustice/cloud-platform/issues/2860 and
relates to the requrement to log all available control plane actions to
cloudwatch.
This commit takes advantage of the AWS EKS Terraform module's option to
enable cluster logging and sets the default values to all available
options.
> Enable cluster log types and retention period

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/variables.tf
This commit connects to
https://github.com/ministryofjustice/cloud-platform/issues/2860 and
relates to the requirement to keep API log data for 13 months as per
security requirements.
The default value has to be either 365 or 400, nothing in between. I've
chosen 400 as it's only 5 days over 13 months.
src:
https://security-guidance.service.justice.gov.uk/logging-and-monitoring/#log-retention
> Change default log retention for control plane logs

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
WHAT
Remove cluster autoscaler from being used on EKS clusters
WHY
We have not tested full implementation of autoscaler and currently default setup takes too long for new node to come up. This will be looked into, once solved will bring back cluster-autoscaler
> Remove cluster-autoscaler

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This has increased memory limit for prometheus.
> Update monitoring module to latest release 1.7.7 for EKS clusters.

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
In this release, it is fixed the Prometheus metrics release name
> Update external-dns to latest 

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
This is because Pipeline is timingout to build EKS test cluser
> Increase wait_for_active_associate to try for 60

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/variables.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/versions.tf
The terraform resource is now available from provider and hence replace in place of null_resource.
For existing clusters, terraform import will be done
> Remove null_resouce for associate_provider and add as terraform resource

- destroy-cluster.rb
This is to fix the authentication error while destroying eks components, caused by this issue:
https://github.com/hashicorp/terraform-provider-kubernetes/issues/1131
> Add terraform refresh to destroy eks_components

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
A timeout (in seconds) to wait for the cluster to be available is set as 300s by default. Creating cluster is failing sometimes with error:
connect: connection timed out
in data "http" "wait_for_cluster":
As it is taking, longer than the default timeout set, increased the timeout to 15 min.
> Increase wait_for_cluster_timeout to 15 min

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to keep cert-manager up to date, also fix Certificate sometimes fails to issue properly.
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/3113
> Upgrade EKS cert-manger to version "v1.5.3"

- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
This is to keep kops cert-manager up to date, also fix the Certificate that sometimes fails to issue properly.
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/3113
> Upgrade KOPS cert-manger to version "v1.5.3"

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
WHAT
Increase replica count to 6
WHY
We are seeing an intermittent issue on the modsec ingress with pods crashing and not coming back without being killed by an admin. Increasing the replica count till a solution is found,
> Increase ModSec replica count to 6

- smoke-tests/spec/external_dns_spec.rb
- smoke-tests/spec/fixtures/external-dns-ingress.yaml.erb
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Update external-dns to use the latest v1.7.1
This version has a fix for the ErrorsInExternalDNS alert. This alert was looking at total errors, so the alert is not cleared even after the issue is fixed. Fix the alert to look for the last 2 hrs for more than 5 errors, as external-dns trigger alert every minute.
Update external-dns tests RSpec tests
- Remove cleanup_zone, as external-dns sync will remove records when ingress is deleted
This is to fix "level=error msg="InvalidChangeBatch: [Tried to delete resource record set
[name='_external_dns.integrationtest.service.justice.gov.uk.', type='TXT', set-identifier='integrationtest.service.justice.gov.uk-integrationtest-dns-20211001113548-blue'] but it was not found,
- Use unique host name for external-dns test
> Update external-dns to use the latest v1.7.1

- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
This version have fix for ErrorsInExternalDNS alert
> Update kops external-dns to use latest v1.7.1

- destroy-cluster.rb
This was caught by our failing destroy cluster pipeline that picked starter-pack-0 up as a user namespace.
> Add starter-pack namespaces to system namespaces

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
launch template always changing plan issue(https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1446)
is fixed in version "v17.3.0"
Comparing changes v17.1.0 to v17.3.0:
https://github.com/terraform-aws-modules/terraform-aws-eks/compare/v17.1.0...v17.3.0
> Update eks module version to "v17.3.0"

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to use the status of [helm_prometheus_operator_eks_status](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/blob/main/outputs.tf#L6), as we have a new helm resource with upgraded Prometheus for EKS
> Add dependence_prometheus for EKS

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to fix "ProcessNotFoundError",
The suggestion below to tune resource values:
https://github.com/concourse/concourse/wiki/Error-Messages-And-What-To-Do-About-Them#processnotfounderror
> Increase concourse resource limit to 8gi

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/versions.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/versions.tf
We are facing this [issue](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1280), revert the upgrade until we got a fix for it.
> Revert Kubernetes provider upgrade

- makefile
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/versions.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/versions.tf
Upgrade k8's provider to version = "~> 2.6.1", this is a pre-requisite for K8s 1.20 upgrade.
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/v2-upgrade-guide#changes-in-v200
* The load_config_file attribute has been removed.
* Support for the KUBECONFIG environment variable has been dropped. (Use KUBE_CONFIG_PATH or KUBE_CONFIG_PATHS instead).
* The config_path attribute will no longer default to ~/.kube/config.
If KUBE_CONFIG_PATH is set, it is ignoring below, so we need to unset KUBE_CONFIG_PATH, unless we want to set config_path
```
host                   = data.aws_eks_cluster.cluster.endpoint
cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
token                  = data.aws_eks_cluster_auth.cluster.token …
```
> Upgrade Kubernetes Provider

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- This is for the manager and live cluster.
- Using EKS module version "v17.23.0"
- Upgrade addons using the supported version for 1.20
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/3345
https://github.com/ministryofjustice/cloud-platform/issues/3346
> Upgrade K8s to 1.20

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf
- Update calico before cni version upgrade
This version has this fix: Added permissions to endpointslices
https://github.com/aws/amazon-vpc-cni-k8s/pull/1678
- Updated calico to set increased resources 
This is to fix the OOM issue seen in typha for resources, also, calico node needs more CPU and memory
- Increased timeout to get the terraform apply working on more node cluster
> Upgrade calico to latest

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- Upgrade cni to support higher pod density 
https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html
- Upgrade node size to nitro instance type 
EKS VPC CNI Addon - Support for high pod density in node only on Amazon EC2 Nitro instances for node groups in the cluster.
> Upgrade cni to support higher pod density 

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Now we upgraded cni to have “Support for high pod density in node”, this will enable more pods on node, so reduced node count to 42 from 54.
> Update node_groups_count to 42 for "live" cluster

- tests/config/live.yaml
- tests/e2e/certmanager_test.go
- tests/e2e/fixtures/certificate.yaml.tmpl
- tests/e2e/fixtures/helloworld-deployment.yaml.tmpl
- tests/e2e/tests_suite_test.go
- tests/go.mod
- tests/go.sum
- tests/makefile
- tests/pkg/helpers/certificates.go
- tests/pkg/helpers/main.go
Overview
---
This PR relates to the requirement of a cert-manager integration test for live clusters. It includes a full GinkGo BDD test for the existence of a certificate created by the Staging Let's Encrypt provider. To make this test lightweight and the code re-usable, I created two new "helper" functions in the `helpers` package. This allows callers to create and test for a positive status of 'Ready'. 
Other things to note
---
To make creating a Helloworld application easier, I created new struct optionality and functionality to do this in a few lines of code.
How to test
---
```
git checkout cert-manager-tests
cd tests/e2e
go test -v -config ../config/live.yaml ./...
```
To test just this function: checkout the branch and add an "F" to the beginning of the `It` Ginkgo call.
> Add cert-manager integration test and go mod tidy

- terraform/aws-accounts/cloud-platform-aws/account/versions.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/versions.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/versions.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/versions.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/versions.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/versions.tf
- terraform/aws-accounts/cloud-platform-dsd/versions.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-account/versions.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-components/variables.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-components/versions.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-network/versions.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform/versions.tf
- terraform/cross-account-IAM/versions.tf
- terraform/global-resources/versions.tf
- terraform/modules/aws_federation/versions.tf
- terraform/modules/cluster_dns/versions.tf
- terraform/modules/cluster_ssl/versions.tf
This is to make sure upgraded versions changes are not affected without teams notice.
Pinned to version = "~> 3.68.0", as we notiected > v3.70, showing chagnes.
> Pin hashicorp/aws provider version

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Upgrade Monitoring Module to 2.0.5 which includes the Prometheus-Operator to v30.0.1
> Upgrade Monitoring Module to 2.0.5

- tests/config/live.yaml
Use new ServiceMonitor names for kube state metrics and node exporter
> Use new ServiceMonitor names

- destroy-cluster.rb
We are using exec now for Kubernetes provider, to avoid short-lived authentication tokens. 
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#exec-plugins
Removing terraform refresh will also avoid getting below error when terraform refresh is run.
Error: Unsupported attribute
> Remove terraform refresh in destroy-cluster script

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This change will enable test clusters to use the integration test zone, as valid hosts.
> Upgrade OPA to use the latest module

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Why:
[Use bitnami helm chart for metrics_server#3411](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/3411)
> Update metric server with bitnami chart

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Related to: https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/122
> Bump monitoring to 2.0.8, change on metric-server

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Update fluent-bit to the latest version, as the stable chart is not supported, used:
https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/Chart.yaml
Pinned app version to "1.8.4", as we see this issue in the latest version
https://github.com/fluent/fluent-bit/issues/4260
> Upgrade logging to use latest version

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- Use ingressClass from controller name, as it is by default named as Nginx
```
More info:
ingressClass: nginx
```
- Add a condition to support tlsv1.3 along with tlsv1.2, this can be used for new ingress controllers
> Update new ing controller to use the latest

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Increased buffer size to 1MB, default is 32k
This is to fix the warn:
cannot increase buffer: current=32000 requested=64768 max=32000
This is fixed in release 1.8.7, but we can't go to that version yet
https://github.com/fluent/fluent-bit/issues/3900
> Update logging to use the latest version

- kops/live-1.yaml
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/variables.tf
As most of the migration to live is completed, scaling down live-1
https://github.com/ministryofjustice/cloud-platform/issues/3574
> Scale down kops live-1 cluster

- tests/e2e/certmanager_test.go
This is to fix the failing cert-manager test.
> Add sleep time for cert test

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/main.tf
- These will be routed to the live cluster:
Prometheus: https://prometheus.cloud-platform.service.justice.gov.uk/
AlertManager: https://alertmanager.cloud-platform.service.justice.gov.uk/
Grafana: https://grafana.cloud-platform.service.justice.gov.uk/
This is related to step4, after migration to eks completed to live:
https://github.com/ministryofjustice/cloud-platform/issues/3007
- Disable kibana proxy on live-1
Created new release from 2.0.1, to have "cloud-platform.service.justice.gov.uk" URLs for live cluster
> Implement URLs for monitoring stack

- smoke-tests/spec/cert_manager_spec.rb
As v1apha3 cannot be used in current cert-manger
> Update  cert-manger test to user v1

- tests/go.mod
- tests/go.sum
Overview
---
This was highlighted by dependabot entry https://github.com/ministryofjustice/cloud-platform-infrastructure/security/dependabot/1
What's in this PR
---
The updated version of protobuf to 1.3.2 which fixes the CVE mentioned above.
> Update to 1.3.2 to fix cve-2021-3121

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/3752
The crds for existing clusters has to be imported to the terraform 
```
terraform import  'module.monitoring.kubectl_manifest.prometheus_operator_crds["alertmanager_configs"]' apiextensions.k8s.io/v1//CustomResourceDefinition//alertmanagerconfigs.monitoring.coreos.com//monitoring
terraform import 'module.monitoring.kubectl_manifest.prometheus_operator_crds["alertmanagers"]' apiextensions.k8s.io/v1//CustomResourceDefinition//alertmanagers.monitoring.coreos.com//monitoring
terraform import 'module.monitoring.kubectl_manifest.prometheus_operator_crds["podmonitors"]' apiextensions.k8s.io/v1//CustomResourceDefinition//podmonitors.monitoring.coreos.com//monitoring
terraform import …
```
> Update module dependency and bump monitoring

- .github/workflows/commit-message-checker-with-regex.yaml
this breaks the conventional commit framework, which we should adopt.
> Change the git commit checker | allow lowercase letter

- go.mod
- go.sum
- makefile
This fixes the error outlined in this concourse job run: https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/live-integration-tests/builds/3304#L62184e06:122:138
> Update the gomega and ginkgo dependencies

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Increase replica count for v1 Ingress controllers to 6 in preparation for roll out to users
> Increase replica count for v1 Ingress controllers to 6

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to keep up to date and also fix the error:
Error: could not download chart: chart "external-dns" version "5.4.8" not found in
https://charts.bitnami.com/bitnami repository
> Upgrade external-dns to latest version

- terraform/global-resources/auth0.tf
- terraform/global-resources/main.tf
Convert Auth0 "rules" to "actions" for add-github-teams-to-oidc-group-claim
https://github.com/ministryofjustice/cloud-platform/issues/3157
> Add module for global auth0 actions

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is because using latest image, we have below error
Tried to delete resource record set [name='_external_dns.xxx.', type='TXT', set-identifier='xxx'] but it was not found
That caused Failure in zone
> Update external-dns to use version 1.11

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/components/components.tf
This is by using ingressclassname as default
This new version also includes:
Change GET to POST when requesting download kubecfg
Enable curator cronjob for the logging module
> Update kuberos to use v1 ingress controller

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/versions.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/versions.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/components/versions.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/versions.tf
This is to use the kubernetes_ingress_v1 resource for kuberos redirect url
> Upgrade kubernetes provider to 2.9.0 to use kubernetes_ingress_v1 resource

- destroy-cluster.rb
This is for destroying script, if any namespaces exist in the cluster which is not listed , the destroy script will abort
> Add kuberhealthy to the list of exist namespaces

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is for new v1 ingress controllers
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/3904
> Remove support for TLS 1.0 and 1.1

- .gitignore
- terraform/global-resources/.terraform.lock.hcl
- terraform/global-resources/versions.tf
This PR pins Terraform provider versions in `global-resources` and inverses the `.gitignore` configuration for the Terraform lock file in `global-resources`.
This ensures that on every `terraform init`, whether run manually or automatically, will always use the same Terraform provider versions as defined in this repository (rather than attempting a minor upgrade, for e.g.).
This is preparatory work for enabling Dependabot in this directory.
> Pin Terraform provider versions in global-resources

- .gitignore
- terraform/cross-account-IAM/.terraform.lock.hcl
- terraform/cross-account-IAM/versions.tf
This PR pins Terraform provider versions in `cross-account-IAM` and inverses the `.gitignore` configuration for the Terraform lock file in `cross-account-IAM`.
This ensures that on every `terraform init`, whether run manually or automatically, will always use the same Terraform provider versions as defined in this repository (rather than attempting a minor upgrade, for e.g.).
This is preparatory work for enabling Dependabot in this directory.
Note that when running `terraform init`, `hashicorp/kubernetes` was already using `v1.13.4`.
> Pin Terraform provider versions in cross-account-IAM

- .github/dependabot.yml
This PR enables Dependabot for the Terraform configuration in `/terraform/cross-account-IAM`.
> Enable Dependabot for cross-account-IAM

- .gitignore
- terraform/aws-accounts/cloud-platform-aws/account/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-aws/account/versions.tf
This PR pins Terraform provider versions in `aws-accounts/cloud-platform-aws/account` and inverses the `.gitignore` configuration for the Terraform lock file.
This ensures that on every `terraform init`, whether run manually or automatically, will always use the same Terraform provider versions as defined in this repository (rather than attempting a minor upgrade, for e.g.).
This is preparatory work for enabling Dependabot in this directory.
> Pin Terraform provider versions in cloud-platform-aws/account

- .gitignore
This PR removes `.terraform.lock.hcl` from `.gitignore`, so as they're generated, they can be committed to this repository.
> Remove .terraform.lock.hcl from .gitignore

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/outputs.tf
This PR removes the deprecated `aws_subnet_ids` resource and replaces it with `aws_subnets`. The only change in a `terraform plan` from this is that the `outputs` for `internal_subnet_ids` has been re-ordered but are the same values.
The upstream PR for this is hashicorp/terraform-provider-aws#22743.
> Replace deprecated `aws_subnet_ids` resource to `aws_subnets`

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/outputs.tf
Dot notation (`.(*|n).`) was deprecated and removed from documentation in Terraform 0.12, in favour of square bracket notation `[(*|n)]`. This PR updates this configuration to reflect that change.
> Replace legacy dot notation with bracket notation

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/versions.tf
This PR pins provider versions in `cloud-platform-aws/vpc/eks`, and removes the unused (directly) provider declaration for `null`.
> Pin provider versions in cloud-platform-aws/vpc/eks

- .github/dependabot.yml
> Enable Dependabot for cloud-platform-aws/vpc/eks

- .github/dependabot.yml
> Enable Dependabot for cloud-platform-aws/vpc/eks/components

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
The kuberos and starter pack are switched to new ingress controllers and hence test cluster fails to create and throw error
`Error: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://nginx-ingress-default-controller-admission.ingress-controllers.svc:443/networking/v1/ingresses?timeout=10s": no endpoints available for service "nginx-ingress-default-controller-admission"`
Add the new ingress controllers as dependency.
> Add dependency for new ingress controller for kuberos and starter-pack

- test/external_dns_test.go
Now we've added [flake-attempts](https://github.com/ministryofjustice/cloud-platform-terraform-concourse/blob/main/pipelines/manager/main/reporting.yaml#L193) to our pipeline, it means failed tests will attempt to rerun. The rerun will use whatever namespace, domain and host are defined in the spec, but this means it'll attempt to use resources that are destroyed in the AfterAll block. This commit adds the namespace, host and domain to the before block, but still make them available to all specs in the suite.
> Add external-dns variables to before block

- test/config/config.go
- test/namespaces_test.go
- test/tests_suite_test.go
Overview
---
The following adds a new field in the `config` struct. It allows the creation of a cloud-platform client wrapper, which enables us to use the kubernetes client-go interface to communicate with the kubernetes API. Using this client replaces the need for terratest, which essentially just calls the `kubectl` binary and executes commands on its behalf. By using the client we can be more efficient with calls and control the output in a less verbose way.
> Use client-go interface to talk to API

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to trigger as warning(low-priority) when it is > 90
> Update the Memory-High alert

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
More details on release: https://github.com/ministryofjustice/cloud-platform-terraform-kuberhealthy/releases/tag/1.0.3
> Bump kuberhealthy module 1.0.3

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
> modsec ingress don't log req body by default

- .github/dependabot.yml
- terraform/aws-accounts/cloud-platform-aws/vpc/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-dsd/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-ephemeral-test/account/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/components/.terraform.lock.hcl
This PR enables Dependabot for Terraform provider and module updates for the rest of the Terraform configurations that did not have a `.terraform.lock.hcl` file or a Dependabot configuration already set.
This includes these directories:
- `/terraform/aws-accounts/cloud-platform-aws/vpc`
- `/terraform/aws-accounts/cloud-platform-aws/vpc/kops`
- `/terraform/aws-accounts/cloud-platform-aws/vpc/components`
- `/terraform/aws-accounts/cloud-platform-dsd`
- `/terraform/aws-accounts/cloud-platform-ephemeral-test/account`
- `/terraform/aws-accounts/cloud-platform-ephemeral-test/vpc`
- `/terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks`
- `/terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/components`
This also configures Dependabot to run on Sunday's going forward; so it is …
> Enable Dependabot for automatic PRs for Terraform provider and module updates

- .github/dependabot.yml
These configurations were removed in #1733, so we no longer need a Dependabot configuration for them.
> Remove Dependabot for terraform/cross-account-IAM and cloud-platform-aws/vpc/kops/components

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Why: 
[upgrade & pin Helm provider for Infrastructure#3882](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/3882)
With reference to:
https://mojdt.slack.com/archives/C514ETYJX/p1658851642017489
Note terraform plan/apply should make no config changes
> upgrade-and-pin-Helm-provider-modules-for-Infrastructure-part1

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
The starter pack module uses both default and modsec ingress controllers.
> Add modsec v1 dependency for starter_pack

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Why: 
[upgrade & pin Helm provider for Infrastructure#3882](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/3882)
With reference to (new releases of modules):
https://mojdt.slack.com/archives/C514ETYJX/p1658918434771229
> upgrade-and-pin-Helm-provider-modules-for-Infrastructure-part2

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/versions.tf
This PR updates `cloud-platform-terraform-auth0` to track the `auth0/auth0` Terraform provider rather than the deprecated `alexkappa/auth0` provider.
> Update cloud-platform-terraform-auth0 to v1.3.1

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Increase live node group size due to hitting memory limits on nodes regularly
> Increase live node group size

- test/namespaces_test.go
Previously a failure in the 'it must have appropriate annotations' test would fail and not inform the viewer of how it failed. This commit fails with a custom message, outlining the offending namespace.
An example of this is shown here:
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/live-integration-tests/builds/4895#L62cb9718:136:158
> Handle missing annotations on a namespace

- terraform/aws-accounts/cloud-platform-aws/vpc/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-aws/vpc/outputs.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/variables.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/versions.tf
This PR updates `terraform/aws-accounts/cloud-platform-aws/account/vpc` to:
- add missing variable/output types and descriptions
- removes providers from `versions.tf` that are unused _directly_ in this root module (as the modules that define them will define version constraints themselves)
- removes unused variables
> Remove unused root module providers; add missing var types and descriptions

- terraform/aws-accounts/cloud-platform-aws/account/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-aws/account/main.tf
- terraform/aws-accounts/cloud-platform-aws/account/outputs.tf
- terraform/aws-accounts/cloud-platform-aws/account/variables.tf
- terraform/aws-accounts/cloud-platform-aws/account/versions.tf
This PR updates `terraform/aws-accounts/cloud-platform-aws/account` to:
- use the standard `#` comment structure rather than `//`
- add missing variable/output types and descriptions
- removes providers from `versions.tf` that are unused _directly_ in this root module (as the modules that define them will define version constraints themselves)
> Remove unused root module providers; use standard comment structure; add missing var types and descriptions

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This release changes the PV alert to only notify on PVs owned by the CP team and not cluster wide PVs
> Monitoring release with new PV alert

- test/certmanager_test.go
This means we don't fail by timing out (25mins), but rather fail because of the test failing.
> Fix flaky test retry from 3 to 2

- .github/dependabot.yml
This PR updates each Dependabot configuration to:
- run on Wednesday at 09:00 UTC rather than on a Sunday at any time
- limit open pull requests for each directory to _1 (one)_ at a time
This is a result of a [team conversation](https://mojdt.slack.com/archives/C514ETYJX/p1660557207947019) to move from a Sunday, when those on-call will get an alert, and also reduces the amount of allowed open PRs from `dependabot` to allow team members to focus on one Terraform provider update at a time for each configuration.
> Reconfigure Dependabot to run on Wednesday 09:00 UTC, and limit to 1 pull request per directory

- README.md
Since moving to EKS, Kops is no longer used.
> docs(readme) remove reference to kops

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to let, velero not deployed in test cluster by default
> Enable conditional deployment for velero

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to fix the error:
Error: Internal error occurred: failed calling webhook "webhook.openpolicyagent.org":
Post "https://opa.opa.svc:443/?timeout=10s":
no endpoints available for service "opa"
> Update opa module dependency

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Add clusterID option to allow filtering elasticache metrics by cluster by @poornima-krishnasamy in https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/140
> better Elasticache metrics

- terraform/aws-accounts/cloud-platform-aws/vpc/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/storage.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/variables.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/main.tf
-  add `live-2` to the list of production clusters listed in this repo. This PR include live-2 as production for monitoring and opa modules which differ from test clusters.
- does-not include `live-2` to production list for ingress-controllers, cert-manager, and external-dns modules
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4101
> Add live-2 cluster to the production standard clusters list

- terraform/global-resources/main.tf
The state for account/ is changed and not updated in global-resources. This updates the correct location of account terraform state
> Remvoe dsd and fix account state

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This PR installs the cloud-platform-terraform-cluster-autoscaler module which includes:
cluster-autoscaler
cluster-overprovisioner
cluster-proportional-autoscaler
> Install cluster-autoscaler

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Set a minimum of nodes to 2 to not have a single point of failure for monitoring nodes which can get scaled down to 1 node group by cluster-autoscaler
> Set minimum number of nodes 2 for node groups 

- makefile
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf
This OPA policy is enabled only on the "live" cluster, all other clusters will not have this check
> Validation for external_dns_weight annotation

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Add default node group min count to cater for cluster autoscaler reducing node count too low
> Add Default node group min count

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/variables.tf
- test/logging_test.go
live-2 don't have permission to write to the existing "live" elastic search, as it is not on the same VPC.
This will be added once a new OpenSearch ES cluster is created for live-2
> Remove elasticsearch_hosts_maps for live-2

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
New releases reduced utilisation for node scale down from 0.5 to 0.1
> New CA release with reduced util for scaledown

- test/fixtures/logging-job.yaml.tmpl
This is to fix the error using bitnami:nginx
OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "curl":
executable file not found in $PATH: unknown
> Use nginxinc/nginx-unprivileged for logging test

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to fix the cluster creation failure.
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "kuberhealthy" namespace: "kuberhealthy" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1" ensure CRDs are installed first
> Add prometheus crd dependency for kuberhealthy and autoscaler

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/variables.tf
Passing false to this variable will skip the oidc installation and save around 30 mins installation time.
> Add ternary conditional for oidc provider

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf
- This will avoid high-priority alerts for test clusters
While building test clusters we replace tokens with dummy values, but applying changes from main to test clusters will add them back and cause accidental alerts to be a high and low priority.
This change will build test clusters without enabling alerts by default and if needed in test clusters, it has an option to enable it.
> Disable alerts for test clusters by default

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to fix alertmanager for test cluster, by passin g dummy values, as there is a "count = length(var.alertmanager_slack_receivers)", to create resources
> Update monitoring to fix alerts for test cluster

- terraform/aws-accounts/cloud-platform-aws/account/main.tf
This is needed for setting up google search console for domain: cloud-platform.service.justice.gov.uk.
> Add TXT record for google search console ownership verification

- terraform/global-resources/elasticsearch.tf
- terraform/global-resources/variables.tf
This PR reduces warm and hot instances count to original count. 
The instances were increases to fix the low disk space: https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1926. The issue of with the ISM policy with the warm to cold migration is fixed, so the count can be reduced.
> Reduce ES instance count back to 5 and 3 and fix ism policy 

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4176
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.3.4
> Bump terraform module for eventrouter upgrade

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- This move the namespace and default certificate to the new ingress controller module
- Update the dependencies as the old ingress controller will be deleted
> Remove old ingress controller

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This has the following.
- Upgrade cloudwatch-exporter and iam-assumable-role-with-oidc used by cloudwatch-exporter
- Maintain IRSA(iam-assumable-role-with-oidc) module locally as the latest self assumed role has a dependency on terraform version
- Upgrade grafana
- Move grafana to the manager node group
- Upgrade grafana sidecar.
> Upgrade monitoring components

- .github/workflows/go-vet-lint-deps.yaml
This PR will enable the running of the `go-vet-lint` workflow, when the workflow is updated. It's useful to be able to test _workflow updates_ without having to use the manual workflow-dispatch.
> Run go-vet-lint workflow, when workflow is updated

- .github/dependabot.yml
This PR turns off Dependabot again, as upgrades are finished for today.
Completed today (06/12/2022):
- github-actions
- terraform/aws-accounts/cloud-platform-aws/account
- terraform/aws-accounts/cloud-platform-aws/vpc
- terraform/aws-accounts/cloud-platform-aws/vpc/eks
- terraform/global-resources
> Turn off Dependabot

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
More details of release: https://github.com/ministryofjustice/cloud-platform-terraform-cluster-autoscaler/releases/tag/1.0.4
Closes: https://github.com/ministryofjustice/cloud-platform/issues/4240
> Upgrade cluster-autoscaler to match k8s version

- terraform/aws-accounts/cloud-platform-aws/account/main.tf
This PR produces `no changes` with a Terraform plan, but nonetheless:
- updates `s3_bucket_thanos` and `s3_bucket_kubeconfigs` from `v3.3.0` to `v3.6.0` of the module
- updates `s3_bucket_velero` from `v1.18.0` to `v2.14.0`, as `v2.15` pins terraform-aws-provider to <= 4; and `v3.0.0` produces changes that may require manual intervention
This PR is solely to produce no-op module updates before tackling hands-on updates.
> Update terraform-aws-modules/s3-bucket/aws to 3.6.0 and 2.14.0 respectively

- .github/workflows/tflint.yml
This PR removes the `--force` flag from the TFLint workflow, to allow a failure in the workflow, which _should_ stop anyone merging PRs that fail linting.
> Allow tflint workflow to fail

- .github/workflows/terraform-tools.yml
This PR introduces a job to run [tfsec](https://github.com/aquasecurity/tfsec) against this repository, and then upload the SARIF output to allow the team to view issues (if any) in the [Code Scanning](https://github.com/ministryofjustice/cloud-platform-infrastructure/security/code-scanning) view of the Security tab.
`tfsec` is currently configured to run with the following flags:
```sh
tfsec
--force-all-dirs # forces a full repository scan, recursively
--soft-fail # forces an exit code 0 on the workflow
-m=CRITICAL # sets the minimum severity to be reported as `CRITICAL`, to reduce the nose as we fix issues
--no-module-downloads # doesn't download modules, to reduce the noise as we fix issues
--exclude-path=terraform/aws-accounts/cloud-platform-ephemeral-test # ignores this unused …
```
> Introduce TFSec scanning

- .github/dependabot.yml
This PR re-enables Dependabot for GitHub actions, as they aren't particularly noisy and should be kept up to date.
> Enable Dependabot for github-actions, as these aren't particularly noisy

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/psp.tf
Overview
---
This PR contains terraform config that installs trivy-operator (and all associated trimmings) into a Cloud Platform Kubernetes cluster. By calling the `cloud-platform-trivy-operator` module, we invoke a helm install which creates the deployment, etc. Users will interact with the operator by either running:
```bash
kubectl get vuln -n <my_namespace>
kubectl describe vuln -n <my_namespace> <vuln_id>
```
There's also a Prometheus metrics scrape, which should enable users and admins to visualise the results in Prometheus and Grafana.
What we do with these results is up to the team.
> Add psp trivy-system group priveledges, add trivy-operator call

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This PR adds the following changes:
* Trivy-operator version bump to provision the operator with increased CPU and memory requests/limits for greater workload in `live` cluster(s)
* A `depends_on` Prometheus CRDs for trivy-operator module (required for ServiceMonitor)
> upgrade trivy to latest release, add prometheus crd dependency

- terraform/aws-accounts/cloud-platform-aws/vpc/main.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/versions.tf
versions.tf terraform version reverted to 0.14 for vpc and flow logs module to fix failing create cluster concourse pipelines whilst upgrade testing is in progress
> Revert terraform version

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
this will reduce concurrent scan job limit in Helm values from 10 to 5
> update trivy-operator module version

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
this trivy-operator release increases the vulnerability report scan job timeout from 5m to 10m
> trivy-operator module bump

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Setting the following scan modes to `false`
```
- configAuditScannerEnabled
- rbacAssessmentScannerEnabled
- infraAssessmentScannerEnabled
- exposedSecretScannerEnabled
```
> increase trivy scan timeout to 10m, configure to run image scans only

- .github/dependabot.yml
This PR enables `gomod` in Dependabot, with an open pull request limit of 10 PRs.
> Enable `gomod` in Dependabot

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Details of release: https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/2.5.4
> Bump monitoring module to 2.5.4

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/versions.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/versions.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/versions.tf
This PR updates all instances of terraform provider version constraint in `versions.tf` to `>= 1.2.5` at vpc, eks and components layer
> update tf provider in vpc, eks and components versions.tf

- create-cluster.rb
This PR addresses failing create cluster pipeline #4431
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/eks-create-test-destroy/jobs/create-cluster-eks/builds/308#L63ffdeca:8
Caused by tools image ruby version upgrade from `2.6` to `3.1`. See:
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/
> fix run_and_output execute function call argument syntax

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
investigating what impact trivy may be having on node CPU spikes
> scale down trivy scan concurrency to 1

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Turn off clusterComplianceEnabled reporting which defaults to true (we are only interested in vulnerability scanning at this time)
as per trivy PR:
https://github.com/ministryofjustice/cloud-platform-terraform-trivy-operator/pull/24
> bump trivy-operator release

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
scaling down re OOMKilled errors for vulnerabilityreport pods
> restore trivy job concurrency to 1

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
github token is only required for standalone mode, removed now we are in clientServer mode
> remove github token from trivy-operator helm values

- terraform/global-resources/elasticsearch.tf
- terraform/global-resources/variables.tf
This reverts commit 134e70c5bf4520e55f53fd07be457d2001712cb7.  We will move the opensearch cluster to the account directory in a future pr.
> Revert "Add Opensearch for live - modsec logs (#2138)"

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/variables.tf
This module streams logs from ingress-controllers filtered for modsec logs to `cp-live-modsec-audit` Opensearch cluster
> Bump logging module to 1.5.0

- terraform/aws-accounts/cloud-platform-aws/account/opensearch.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/account/opensearch.tf
- As webops we will continue to be able to see all logs
- Users will only have access to logs which are tagged with their github team and they are also a member of that team
Part of [#4504]https://github.com/ministryofjustice/cloud-platform/issues/4504
> feat: 🎸 enable document level security on modsec logs

- terraform/aws-accounts/cloud-platform-aws/account/opensearch.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/account/opensearch.tf
Fixes minor bug where the document level security permissions were also applied to the webops team
> fix: 🐛 override document level permissions for webops team

- terraform/aws-accounts/cloud-platform-aws/account/opensearch.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/account/opensearch.tf
opensearch was not mapping the backend_role to the document field `github_teams` correctly, the hyphens were causing hyphenated team names to be split into separate search terms.
Using `github_teams.keyword` solves this.
https://opensearch.org/docs/2.5/field-types/keyword/
> fix: 🐛 opensearch needs exact search (match - in teamnames!)

- terraform/aws-accounts/cloud-platform-aws/account/main.tf
Module update implements github team session tag clean up as per:
https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/pull/20
> This PR updates aws-sso module to latest release

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Ref: https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.6.4
> Bump logging module to 1.6.4

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- Use 1.2.1 version to debug ingress logs output
Fluent-bit errors with `failed to flush chunk` and debug logs with `version_conflict_engine_exception` and invalid `upstream_status`. Reverting to 1.2.1 to see if the log formatting has introduced these errors
> Use 1.2.1 version to debug ingress logs output

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Increasing concurrent scanner job limit to 2.
> increase trivy scan concurrency

- terraform/global-resources/elasticsearch.tf
This PR removes the old `cloud-platform-audit` which is leftover from the `live-1` migration. 
The last set of logs in this domain are as follows:
```
all_logs-2020.10.19
kubeapi_audit-2021.10.28
logstash-2020.10.19
```
> Remove deprecated cloud-platform-audit ElasticSearch domain

- terraform/aws-accounts/cloud-platform-aws/account/main.tf
https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/releases/tag/1.3.2
> Bump aws-sso module to 1.3.2 allowing apigateway permissions

- terraform/aws-accounts/cloud-platform-aws/account/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-aws/account/opensearch.tf
- terraform/aws-accounts/cloud-platform-aws/account/versions.tf
This PR removes the legacy `//` comment syntax in favour of `#`, removes the unused `external` and `random` providers, and replaces the community `curl` provider with `hashicorp/http`.
> cloud-platform-aws/account: remove unused providers, reconfigure version constraints

- terraform/global-resources/.terraform.lock.hcl
- terraform/global-resources/elasticsearch.tf
- terraform/global-resources/versions.tf
This PR removes the deprecated [`hashicorp/template`](https://github.com/hashicorp/terraform-provider-template) provider in favour of the built-in `templatefile()` function.
> global-resources: remove use of deprecated template provider

- terraform/aws-accounts/cloud-platform-aws/account/main.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/account/main.tf
https://github.com/ministryofjustice/cloud-platform-terraform-awsaccounts-baselines/releases/tag/0.1.0
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4539
> Bump account-baselines module to 0.1.0

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/versions.tf
this will allow use to move kuberhealthy ECR, which is currently the biggest offender for crossing the daily Docker rate limit. This method is being take as its cant be obtained via pull through cache due to not being a Docker offical image
> feat(bump): move aws terraform provider to 4.67.0

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
24hrs not long enough for the operator to scan all images across cluster
> Increase vulnerability report TTL from 24 to 48hrs

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Reverts ministryofjustice/cloud-platform-infrastructure#2303
Removing the 2nd test modsec controller. We are seeing some missing audit logs because of too many controller logs pushing to Audit Opensearch. 
And this is not needed for weekend
> Revert "Add 2nd modsec ingress controller to test hmpps slow responses"

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This pulls in the updated gatekeeper module, which adds gatekeeper to the cluster but in a dormant state with no constraints.
> feat: 🎸 install gatekeeper with all constraints disabled

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
`hmpps-auth` raised an issue where they saw ~1 to 2% of their traffic through their modsec controllers display high latency levels. There is no pattern to the type of requests or timings.
To identify the issue, we created the team a dedicated ingress controller from which we could experiment with changing modsec settings and measuring their effect on their traffic. Without changing any modsec values, the team immediately reported results following load testing. Just by introducing a dedicated ingress controller with no changes we saw results suggesting the fault doesn't lie with our modsec config.
Whilst load testing we would sporadically see `SSL handshakes failed`. The theory modsec ingress controllers are running out of TCP connections (maybe due to keep-alives keeping the socket open …
> perf: ⚡️ increase modsec ingress replicas from 6 to 12

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
raise memory limits for prod as gatekeeper has to sync a lot more resources
> chore: 🤖 bump gatekeeper module

- terraform/aws-accounts/cloud-platform-aws/account/variables.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/account/variables.tf
Why:
[Fix ISM Policy for cp-live-modsec-audit Opensearch#4578](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4578)
Specifically to correct the index pattern to apply on the ISM policy
> Fix ISM Policy for cp-live-modsec-audit Opensearch

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
run gatekeeper in dryrun mode and add service_type constraint.
Once verified that everything is working as expected then we can disable the corresponding opa rule and disable dryrun for the gatekeeper rule.
> chore: 🤖 update gatekeeper vars, bump version to run gatekeeper in

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
migrate all remaining opa rules to gatekeeper constraints, but have them running in dry run mode
> chore: 🤖 bump gatekeeper

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/components/components.tf
Why: [Investigate Route53 rate limit error on external-dns #4608](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4608) issue
> reference latest external-dns module release

- terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/components/components.tf
Use latest external-dns module release 1.11.1:
Why: bump up update interval to 10m:
[Investigate Route53 rate limit error on external-dns#4608](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4608)
> use-latest-exteranal-dns-release

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/components/components.tf
Why: reference latest external-dns release:
To address throttling issue [Investigate Route53 rate limit error on external-dns#4608](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4608)
> reference-latest-external-dns-release

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/global-resources/elasticsearch.tf
We are seeing alerts triggered for no enough minimum free storage and related to the jvm memory pressure being too high. Attached shows our storage really is very low
Also bumping logging module as there was a syntax error in the limit range
> chore: 🤖 double es ebs volume to 3TB

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/components/components.tf
Why [Nginx Default Backend Issue#4691](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4691)
Temporarily revert back module - just incase I have inadvertently introduced a problem with my config change re throttling ref[Investigate Route53 rate limit error on external-dns#4608](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4608).
> revert-external-dns-module-to-1.11.1-re-route53-problem

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/components/components.tf
Why - latest:
reference latest external-dns release https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/releases/tag/v1.11.4
> update-external-dns latest release  to not list cp and yy route53

- terraform/global-resources/variables.tf
- Update hot to warm transition from 7d to 14d. The ES has 12 hot nodes and has more disk space to store 14 days of data. Since the uneven shard distribution is resolved now, the 12 hot nodes should be able to handle 14 days of data
- Update warm to cold from 14d to 30d. This is needed so 30d logs are available to search in kibana
> Update warm and cold transition duration, 30d needs to search in kibana

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/security-group.tf
This PR moves our worker node security group and rules config outside of EKS  module in preparation for 17.24.0 > 18.31.2 EKS module upgrade.
> Move worker security group outside of eks module

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Why:
[Kuberhealthy Alerts Review#4670](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4670)
> use-latest-monitoring-release-to-alert-on-missing-namespaces-only

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.9.15
> Bump logging module to 1.9.15

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This PR bumps gatekeeper to latest release with psp migrated mutations enabled.
> bump gatekeeper for enabling psp migrated mutations

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Why [Kuberhealthy Alerts Review#4670](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4670)
To make namespace checks less frequent
> change-timings-for-kh-namespace-kuberhealthy-check-use-latest-module

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/psp.tf
This PR adds a privileged PSP which doesnt mutate any of the pod characteristics. This is needed to bypass existing psp inorder for the PSA to take control of the namespaces.
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4872
> Add 0-super-privileged as a non mutation psp

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/psp.tf
This is needed for the psp bypass which we will carry out next sprint. The bypass works by escalating privilege to the `0-super-privilege` PSP on a per namespace level which triggers PSA a takeover.
> refactor: 💡 add throw away rolebinding for super-privileged psp

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.9.17
Closes: https://github.com/ministryofjustice/cloud-platform/issues/4767
> Bump logging module to 1.9.17

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/2.10.6
> Bump monitoring to 2.10.6

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/2.10.7
> Bump monitoring to 2.10.7

- test/fixtures/namespace.yaml.tmpl
both groups capture the same targets, `system:authenticated` is preferred because it reads better and is consistent with our psp rolebindings.
> test: 💍 system:seviceaccounts:* -> system:authenticated

- terraform/global-resources/elasticsearch.tf
The Elasticsearch has hit high JVMMemoryPressure > 80% frequently and we need to investigate the root cause of it. There is coincidence when there is too many documents pushed to the cluster, but how the cluster handles those requests still needs to be investigated.
This PR enables search slow logs and indexing slow log which will help identify if there any performance issues related to indexing and searching when the JVMMemoryPressure is high
Enabling slow logs consume considerable disk space of the nodes, and hence this is only enabled for some time period, keeping an eye on disk space and should be disabled once we get logs for particular period of time when JVMMemoryPressure is alerted as high
> Enable slow logs for search and index to investigate on JVMMemoryPressure

- test/certmanager_test.go
- test/psa_priv_ephemeral_test.go
- test/psa_priv_init_test.go
- test/psa_priv_test.go
- test/psa_restricted_eph_test.go
- test/psa_restricted_init_test.go
- test/psa_restricted_test.go
- test/psa_serviceaccount_test.go
This PR mask kubernetes output when doing kubernetes specific operations stopping the test logs to display serviceaccount tokens and the yaml when performing KubectlApplyFromStringE and RunKubectlAndGetOutputE
Also,  tidy-up so the tests output is readable.
> Discard k8s output from logger

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf
Test cluster has missing annotations when applying components and when a terraform apply is performed, it wipes the labels from kube-system namespace.
There is a open issue and the suggestion is to add filedManager.
https://github.com/hashicorp/terraform-provider-kubernetes/issues/1791
This PR allows both annotations and labels to be managed by Terraform.
> Add field_manager argument to prevent labels and annotations overwriting

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-kuberhealthy/releases/tag/1.2.9
> Bump kuberhealthy to 1.2.9

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/releases/tag/1.9.2
> Bump gatekeeper for 1.9.2

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Why:[KuberhealthyOverallClusterStateCheck Alert - output information as to which of the Kuberhealthy alerts has failed#4844](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4844)
> latest-monitoring-release

- test/certmanager_test.go
This PR increases the retry count of ingress resolving to 200 OK. The certificate tests fails because of this and increase in the retry will enable to wait for long time until it get resolved.
> Increase retry count of ingress resolving - cert-manager test

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf
This pins the module versions and removes their version qualifier (`~>`), as Dependabot throws an error when trying to retrieve the "installed" version (i.e. it's blank). This means Dependabot can't create a new PR for the latest version.
> Pin app-opensearch and modsec-opensearch ACM module versions instead of using a qualifier

- terraform/global-resources/kibana-alerts.tf
The monitor will instead remain firing, this will decrease the message spam into the lower-priority-alerts channel
> Increasing search period to decrease monitor firing so often

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.20.3
> Bump concourse to 1.20.3

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
We are seeing SEGV faults which is causing the fluent bit container to restart
```
[2024/01/09 06:38:39] [engine] caught signal (SIGSEGV)
#0  0x55d90465c427      in  __mk_list_del() at lib/monkey/include/monkey/mk_core/mk_list.h:141
#1  0x55d90465c45e      in  mk_list_del() at lib/monkey/include/monkey/mk_core/mk_list.h:147
#2  0x55d90465d100      in  chunk_state_sync() at lib/chunkio/src/cio_chunk.c:546
#3  0x55d90465d244      in  cio_chunk_up_force() at lib/chunkio/src/cio_chunk.c:600
#4  0x55d903d6f1d5      in  input_chunk_get() at src/flb_input_chunk.c:1061
#5  0x55d903d6fd01      in  input_chunk_append_raw() at src/flb_input_chunk.c:1460
#6  0x55d903d707f7      in  flb_input_chunk_append_raw() at src/flb_input_chunk.c:1810
#7  0x55d903e56399      in  input_log_append() at …
```
> chore: 🤖 bump modsec fluent bit

- terraform/global-resources/kibana-alerts.tf
Originally only was looking for "failed to load dashboard" and was missing "failed to save dashboard" errors
> Include failed to save dashboard search param for monitor

- .github/workflows/malformed-yaml.yml
I have opened an issue with ops-eng while they fix the dependency I've pinned the version to the last working release.
https://github.com/ministryofjustice/github-actions/issues/230
> ci: 🎡 pin malformed yaml action

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/compare/1.10.0...1.10.1
Closes: ministryofjustice/cloud-platform#5189
> Bump gatekeeper fot 1.10.1

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-trivy-operator/releases/tag/0.8.2
Closes: https://github.com/ministryofjustice/cloud-platform/issues/5188
> Bump trivy-operator to 0.8.2

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/variables.tf
The placeholder address error could be causing the other logs to fail to be flushed
> fix: 🐛 placeholder-opensearch for manager cluster

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.20.4
> Bump concourse to 1.20.4

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-kuberhealthy/releases/tag/1.3.0
We need to remove the count method and it's been replaced with a for_each which causes the k8s manifests to be deleted and recreated (not referred to via index any more)
> chore: 🤖 bump kuberhealthy

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
closes ministryofjustice/cloud-platform#5296
> bump external-dns module

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Following further testing, we've seen an notable decrease in timeouts when we increase the number of ingress replicas. See the testing results below:
Summary:
> Success rate: 99.37% -> 99.92%
>   [54] timeout -> [6]
>   [5] Connection reset by peer (os error 104) -> [2]
>   [4] connection error -> [0]
3 ingress replicas:
```
Summary:
Success rate: 99.37%
Total:        48.6973 secs
Slowest:      11.5267 secs
Fastest:      0.0063 secs
Average:      4.7402 secs
Requests/sec: 205.3502
Total data:   19.41 KiB
Size/request: 2
Size/sec:     408 B
Response time histogram:
0.006 [1]    |
1.158 [1594] |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
2.310 [1044] |■■■■■■■■■■■■■■■■■■■
3.462 [1172] |■■■■■■■■■■■■■■■■■■■■■
4.614 [1008] |■■■■■■■■■■■■■■■■■■
5.767 [1023] |■■■■■■■■■■■■■■■■■■
6.919 [1001] |■■■■■■■■■■■■■■■■■■ …
```
> perf: ⚡️ bump replicas to alleviate timeouts

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/versions.tf
for calico crds and gp2 manifest objects
relates to ministryofjustice/cloud-platform#5380
> switching components to new kubectl tf provider

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
> switch gatekeeper module to alekc kubectl provider

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
Reverts ministryofjustice/cloud-platform-infrastructure#2933
This causes the integration tests for live-2 to fail on external-dns and cert-manager tests
> Revert "reduce external-dns polling for live-2"

- terraform/global-resources/kibana-alerts.tf
external-dns uses [aws sdk retryer](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/retries-timeouts/#standard-retryer) set to max 3 attempts with sensible backoff defaults. We are probably being too sensitive with our throttling alert triggers. 
Relates to ministryofjustice/cloud-platform#5326
> reduce window of time for observed throttling messages

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/5353
https://github.com/ministryofjustice/cloud-platform-terraform-cluster-autoscaler/releases/tag/1.8.0
> Bump cluster autoscaler to 1.8.0

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
We are getting WAL restarts and Prometheus reporting "TSBD Not ready" in error. Reverting to previous module to rule out the change is not the issue
> Reverting Monitoring to previous module release

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.7.3
> Bump monitoring to 3.7.3

- terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf
The node version is bumped to 2.7.0 for the auth0 action. Fix the code to match the actual version
> Fix node version bump to match actual version

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf
- Implement live mod-sec and app-logs OpenSearch CloudWatch Alarm
- correct domain name tag for app-logs certificate
- Relates to ministryofjustice/cloud-platform#5486
> Implement live OpenSearch CloudWatch Alarm

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf
- Bump OpenSearch CloudWatch Alarm version
- Get the module min_available_nodes value from attribute reference instead of hardcoding it
> Bump OpenSearch CloudWatch Alarm version

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
By default, OpenSearch Service uses 50% of an instance's RAM for JVM heaps up to 32 GiB in size. The JVM memory pressure specifies the percentage of the Java heap in a cluster node.
https://repost.aws/knowledge-center/opensearch-high-jvm-memory-pressure
https://aws.amazon.com/opensearch-service/pricing/
current elastic search: https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/f34a90e82313ac473e023d1d90a57673bdb304e1/terraform/global-resources/elasticsearch.tf#L169
> perf: ⚡️ increase data node size to raise jvm heap size (match current elastic search)

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- following high-priority alarm for root vol threshold, bump the disk space
> perf: ⚡️ increase disk space on default nodes

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch-index-templates.tf
- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- shards should be set to ~30gb each
- shards should be a multiple of data nodes
with 5 shards set our live cluster logs:
```
live_kubernetes_cluster-2024.05.24 0     p      STARTED 201889968 85.9gb x.x.x.x 6a9ac9a283d158e32ae8a6d6e3e3679d
```
> perf: ⚡️ configure shard sizes and set n data nodes

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.7.10
> Bump monitoring to 3.7.10 - Update nginx ingress alerts

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.7.11
> Bump monitoring to 3.7.11

- terraform/global-resources/elasticsearch.tf
Alerts are triggered for ElasticSearch not having enough minimum free storage - `FreeStorageSpaceTooLow`.
Attached shows some of the data node storage is really low.
> perf: Bump Elasticsearch ebs volume to 4TB

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
EKS upgrade to 1.28 as detailed in the ticket ministryofjustice/cloud-platform#5576
> eks upgrade from 1.27 to 1.28

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
Alerts are triggered for OpenSearch not having enough minimum free storage - FreeStorageSpaceTooLow.
Attached shows some of the data node storage is really low.
> perf: Bump OpenSearch ebs volume to 4TB

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
To combat flakey Prometheus and downtime routinely affecting our users, increase the Prometheus replicas to increase resilience. We currently have one Prometheus in a private subnet in `eu-west-2b`. Increase this to 3 one in each AZ (`eu-west-2a/b/c`).
The 3 Prometheis scrape the same targets, meaning we have duplicated each metric twice (3 times in total). To deduplicate this there are 2 steps:
- prometheus deduplicates at the the query level (see the "use deduplication" checkbox in the prom UI)
- thanos compactor runs against the blocks in storage and dedupes the metrics back down to 1. This process runs after the metrics are pushed to s3. So for some time (currently 24hrs) there will be duplicate metrics, this can be reduced by lowering the `--delete-delay=Xh` flag in the Thanos …
> perf: ⚡️increase promethues replicas so we have one per az

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
Release:
https://github.com/ministryofjustice/cloud-platform-terraform-cluster-autoscaler/releases/tag/1.10.0
relates to ministryofjustice/cloud-platform#5582
> chore: 🤖 bump autoscaler for k8s 1.28

- terraform/global-resources/elasticsearch.tf
Alerts are triggered for ElasticSearch not having enough minimum free storage - FreeStorageSpaceTooLow.
Attached shows some of the data node storage is really low.
> perf: Bump Elasticsearch ebs volume to 5TB

- terraform/global-resources/elasticsearch.tf
Got below error in [terraform apply](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/infrastructure-global-resources/jobs/terraform-apply/builds/32#L6674b47e:788) for bumping ebs volume from 4TB to 5TB, so we need to bump the IOPS
`Error: updating Elasticsearch Domain
(arn:aws:es:eu-west-2:754256621582:domain/cloud-platform-live) config: LimitExceededException: IOPS must be between 15000 and 20000`
> perf: Bump Elaticsearch IOPS

- terraform/global-resources/elasticsearch.tf
Resolve `Error: updating Elasticsearch Domain (arn:aws:es:eu-west-2:754256621582:domain/cloud-platform-live) config: LimitExceededException: IOPS must be set to 20000`
concourse link [here](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/infrastructure-global-resources/jobs/terraform-apply/builds/34#L6674f368:788)
> perf: bump IOPS

- terraform/global-resources/elasticsearch.tf
fix `Error: updating Elasticsearch Domain (arn:aws:es:eu-west-2:754256621582:domain/cloud-platform-live) config: LimitExceededException: Throughput must be set to 593`
concourse link [here](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/infrastructure-global-resources/jobs/terraform-apply/builds/35#L6674f44c:789)
> fix: bump throughput

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-descheduler/releases/tag/0.8.0
> feat: Update decheduler for 1.28 kube release

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
release: https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.12.0
relates to ministryofjustice/cloudplatform#5581
> chore: 🤖 bump monitoring module for prom upgrade k8s1.28

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
relates to ministryofjustice/cloud-platform#5610
[release notes](https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.25.6)
> chore: 🤖 bump concourse for route53 resolver permissions

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
> perf: Bump OS EBS Volume

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
release notes:
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.17.3
> chore: 🤖 bump logging for temp disabling of OS outputs

- terraform/global-resources/elasticsearch.tf
this PR increases the jvm memory pressure alert threshold from default value of 80% to 90%, whilst reducing the threshold pressure period from default of 15 to 10 mins. This is based on viewing jvm pressure spike patterns and to focus lower priority alert attention on the pressure remaining high for abnormal lengths of time
> chore: 🤖 tune cloudwatch elasticsearch jvmpressure alert

- terraform/global-resources/elasticsearch.tf
it looks like we are experiencing a similar issue on elastic search, despite documents are being deleted correctly. Whilst we figure out a proper fix we need some breathing room.
> perf: ⚡️ bump storage

- terraform/global-resources/elasticsearch.tf
- Increase warm storage space
- Bump number of warm nodes from 8 to 16
-
> feat: bump number of warm elasticsearch nodes to 16

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- ism hot/warm/cold storage failing because we don't have enough warm nodes
> perf: ⚡️ increase warm node count

- terraform/global-resources/elasticsearch.tf
- This adds a new index tempalte for live_kubernetes_cluster index. This should break down the file sizes so that they can be moved to warm. We've seen errors where the index is too large to move.
- Add index template
-Adds an index template for live_kubernetes_cluster_* index
> feat: Add index template for es

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
This change stops the `hoodaw` irsa role from failing when adding concourse to a test cluster by adding a count on the module and resource so that they are not created. The role isn't needed for the concourse as it only creates a role for the `hoodaw` reports to be pushed to the S3. The reason it's in the concourse module was due to the reports being ran from concourse namespace.
> feat(tf): concourse module bump to fix issue hoodaw irsa is causing in test cluster creation

- test/user_app_logging_test.go
- this int test was turned off whilst opensearch indexes were being fixed
- this turns the int test back on
> chore: 🤖 turn on opensearch int tests now os is up again

- terraform/global-resources/elasticsearch.tf
We had implemented monitoring the ElasticSearch storage size at single node level. This is to turn on alert for monitoring ElasticSearch storage size at total node level as well.
Relates to ministryofjustice/cloud-platform#5928
> chore: Turn on alert for elasticsearch node total storage

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
This PR will bump the Kuberhealthy module version to include the change in priority for Daemonset test to 'cluster-critical'.
Module has been tested on a test cluster.
> Bumping Kuberhealthy module to include Daemonset test priority change

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- Added an alert to monitor OpenSearch storage size across all nodes.
- Alert Threshold:
- Based on the [OpenSearch CloudWatch alarm guide](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cloudwatch-alarms.html), the alarm triggers at 25% of the storage space for each node.
- Calculated threshold:
- Formula: (size-in-gb * instance count * 25% * 1024)
- The value is in MiB, so it needs to be multiplied by 1024.
- Code Improvement:
- Updated to use attribute references instead of hardcoding the storage threshold.
- Relates to [cloud-platform/issues/5928](https://github.com/ministryofjustice/cloud-platform/issues/5928)
> chore: Turn on alert for OpenSearch total node storage

- terraform/global-resources/elasticsearch.tf
- Update alert to monitor ElasticSearch storage size for total node storage.
- Alert Threshold:
- Based on the [OpenSearch CloudWatch alarm guide](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cloudwatch-alarms.html), the alarm triggers at 25% of the storage space for each node.
- Calculated threshold:
- Formula: (size-in-gb * instance count * 25% * 1024)
- The value is in MiB, so it needs to be multiplied by 1024.
- Updated to use attribute references instead of hardcoding the storage threshold.
- Relates to [cloud-platform/issues/5928](https://github.com/ministryofjustice/cloud-platform/issues/5928)
> chore: Update ElasticSearch CloudWatch Rule

- terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf
- Update alert to monitor ModSec OpenSearch total node storage size.
- Alert Threshold:
- Based on the [OpenSearch CloudWatch alarm guide](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cloudwatch-alarms.html), the alarm triggers at 25% of the storage space for each node.
- Calculated threshold:
- Formula: (size-in-gb * instance count * 25% * 1024)
- The value is in MiB, so it needs to be multiplied by 1024.
- Updated to use attribute references instead of hardcoding the storage threshold.
- Relates to [cloud-platform/issues/5928](https://github.com/ministryofjustice/cloud-platform/issues/5928)
> chore: Update ModSec OpenSearch CloudWatch Alert

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
The overprovision daemonset pods are no longer required as kuberhealthy daemonset tests are now passing with higher cluster priority.
This change removes the creation of all Overprovision Daemonset pods.
This change has been tested on a test cluster, before change:
After change applied:
> Update autoscale module to latest that removes overprovision daemonset pods

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
This PR adds `backup-storage:*` permissions to the concourse IAM role.
This will allow concourse to create AWS Backup resources.
[Failed apply due to not having these permissions](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-live/jobs/apply-namespace-changes-live/builds/6691#L66bd1fd7:26) - this policy already contains `kms:*`
> Bump concourse module to give concourse correct permissions for AWS Backups

- terraform/aws-accounts/cloud-platform-aws/vpc/transit-gateway/vpc-attachment.tf
We can only associate 1 subnet per az to tgw (from there this subnet should be able to route to the other subnets)
This reverts commit b69a76b1b7282e7ae5818dd687c3391301b9272d.
> Revert "adding new EKS-Private subnets to tgw attachments (#3351)"

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
This change is expected to drop networking for a couple of minutes. It doesn't bring up any nodes in the new subnets yet, it just adds the new subnets to the cluster.
> feat: 🎸 add EKS-Private subnets to cluster

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Now all workloads have moved onto the new node groups in the new subnets successfully, remove the old node groups from code
> chore: 🤖 remove old node groups

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/calico.tf
- See https://github.com/ministryofjustice/cloud-platform-terraform-tigera-calico/releases/tag/0.1.9
- See https://github.com/orgs/ministryofjustice/projects/65/views/3?pane=issue&itemId=81539621
> feat: bump calico module to 0.1.9

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
While showing this off to someone, I noticed that Steve's IAM account still exists here.
This pull request includes a change to the `terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf` file to update the list of users in the EKS cluster configuration.
User management updates:
* Removed the user configuration for `SteveMarshall` from the EKS cluster. (`terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf`)
> :fire: Remove Steve Marshall from auth users

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/cert_manager.tf
Removing the 60 second wait from the build for cert manager due to the separation of core and components. [#5886](https://github.com/orgs/ministryofjustice/projects/65/views/3?pane=issue&itemId=71051417)
> Update to use latest module which removes cert manager wait

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[Release notes](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.14.0)
relates to ministryofjustice/cloud-platform#6277
> chore: 🤖 bump monitoring for elasticache metrics

- terraform/aws-accounts/cloud-platform-aws/account/main.tf
Bumping sso module to release [1.5.8](https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/releases/tag/1.5.8) for ECR Console read-only access
[#6036](https://github.com/ministryofjustice/cloud-platform/issues/6036)
> Bump sso module version to include ecr read only

- terraform/aws-accounts/cloud-platform-aws/account/main.tf
Fixing typo for issue [#6036](https://github.com/ministryofjustice/cloud-platform/issues/6036)
> Fixing ecr document typo from DescribeRepository to DescribeRepositories

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- bump manager instance size
- pass `limit_active_tasks` var to concourse
> perf: ⚡️ increase default manager instance size

- terraform/aws-accounts/cloud-platform-aws/account/main.tf
This will grant the ability to list the backup vaults, jobs, and protected resources and be able to get more details for the ones within the users namespace through the SSO read only AWS console.
This relates to the S3 buckets AWS Backup restore process issue https://github.com/ministryofjustice/cloud-platform/issues/6039
> Bump sso module version to include Backups Read only for SSO

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[Release notes](https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/releases/tag/1.16.0)
relates to ministryofjustice/cloud-platform#6383
> chore: 🤖 bump external dns release

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[Release notes](https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/releases/tag/1.16.1)
relates to ministryofjustice/cloud-platform#6383
> chore: 🤖 bump external-dns for more memory

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- users need perms to use the reporting functionality
> chore: 🤖 give users perms to use reporting

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[Release](https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/releases/tag/1.16.2)
relates to ministryofjustice/cloud-platform#6383
> chore: 🤖 bump external-dns for resource increases

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[Release](https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/releases/tag/1.17.0)
> chore: 🤖 rollback external-dns to functional release

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
NO-OPS!
this removes the deprecated template provider dependency
[Release](https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.13)
> chore: 🤖 bumping all ingress modules

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
NO-OPS!
update terraform lockfile
[Release](https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/releases/tag/1.18.8)
> chore: 🤖 bump eks-addons for template provider removal

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/.terraform.lock.hcl
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/gatekeeper.tf
This bump adds a GK check for empty string external-dns annotations:
https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/commit/879de3bc86153f2958ba5b7c46ab31abf0523ab7
> chore: 🤖 bump gatekeeper and update terraform lockfile

- test/external_dns_test.go
- test/fixtures/external-dns-ingress.yaml.tmpl
using complete deployment template for external-dns test to avoid erroring ingress resource missing referenced svc object, update test logic
> fix: 🐛 external-dns test

- terraform/global-resources/elasticsearch.tf
```
ValidationException: 1 validation error detected: Value 't3.small.search' at 'elasticsearchClusterConfig.instanceType' failed to satisfy constraint: Member must satisfy enum value set
```
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/infrastructure-global-resources/jobs/terraform-apply/builds/58
> fix: 🐛 instance type not satisfied by enum

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[release](https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/releases/tag/1.17.2)
> chore: 🤖 bump external-dns

- terraform/global-resources/elasticsearch.tf
- keep node count the same until the indexes are resized
> fix: 🐛 node count

- terraform/aws-accounts/cloud-platform-aws/account/main.tf
no-ops, required terraform imports have been carried out
> chore: 🤖 bump velero s3 bucket module to latest release

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
now we have anti-affinity for controllers (1 per node), live-2 node count has increased dramatically. we don't need a large number of controllers on this cluster so this PR should fix that issue
> chore: 🤖 update live workspace condition for ingress replicas

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[release notes](https://github.com/ministryofjustice/cloud-platform-terraform-descheduler/releases/tag/0.9.1)
relates to ministryofjustice/cloud-platform#6509
> chore: 🤖 bump descheduler to latest compatible release

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[release
notes](https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/releases/tag/1.17.3)
relates to ministryofjustice/cloud-platform#6509
> chore: 🤖 bump external-dns module

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- terraform/global-resources/elasticsearch.tf
- terraform/global-resources/main.tf
- we don't need these alerts anymore as es isn't critical
> chore: 🤖 remove es monitoring/ alerts

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
relates to ministryofjustice/cloud-platform#6387
[release notes](https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.9.0)
> chore: 🤖 bump all ingress controller modules to latest

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
We are overprovisioning monitoring node group, which only needs to match prometheus x3 requirement in non prod clusters.
relates to ministryofjustice/cloud-platform#6681
> Mon group count

- terraform/global-resources/elasticsearch.tf
- I incorrectly tried to upgrade the warm nodes and that failed, I try again with the instance nodes
> fix: 🐛 data node not warm node bump

- .gitignore
- capture `<name>.env` filename patterns
> fix: 🐛 capture more .env file patterns

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- revert trivy bump temporarily to avoid high priority alarm flood
> fix: revert trivy bump to avoid high priority alarm flood

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/gatekeeper.tf
- there are high resource tracking in gatekeeper audit pod log
- gatekeeper audit pod was `OOMKilled` and `CrashLooping` frequently
- relates to https://github.com/ministryofjustice/cloud-platform/issues/6817
> perf: Bump gatekeeper audit pod memory

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
This PR establishes a new hosted zone and associated ns delegation records for the parent cloud-platform zone, so that we have a dedicated zone for running external-dns test suites against.
> feat: 🎸 add route53 hosted zone for external dns testing

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/main.tf
So that test cluster external-dns IAM policy has permission to control the ext-dns testing hosted zone
> feat: 🎸 add ext-dns hosted zone for test cluster access

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/gatekeeper.tf
- bump gatekeeper to allow duplicate hostname across namespace
- https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/releases/tag/1.13.0
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/6785
> feat: bump gatekeeper to allow duplicate hostname across ns

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch-index-templates.tf
See context in https://github.com/ministryofjustice/cloud-platform/issues/6870#issuecomment-2700633965
A `time` field is found in documents indexed with OpenSearch. Having an explicit mapping for it will allow to query documents based on it, check that it is present in all documents and also compare with '@timestamp'
> Adding explicit mapping of time field in template for OpenSearch index

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- we've ran out of space on our warm nodes
- temporarily ramp up nodes to cope
> perf: ⚡️ running out of warm node space

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
This pr bumps the monitoring module as per this merged https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/32 to remove unneeded duplicate prometheus rule
> bump monitoring module

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
This pr is to add the github team filter api key as an input for the concourse module
> feat: add github-team-filter-input

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch-index-templates.tf
- we have a bunch of warm indices stuck that can't move because they are too large, we need to reindex these but first we should make sure future indices are correctly shared.
```
{
"index": "live_kubernetes_cluster-2024.07.12",
"state": true,
"cause": "Rejecting migration request for index [live_kubernetes_cluster-2024.07.12] because the shard size [100 GiB] exceeds the warm migration shard size limit of [100 GiB]. To avoid migration failures, reindex your data to reduce shard sizes, then migrate it to UltraWarm storage.",
"message": "Failed to start warm migration [index=live_kubernetes_cluster-2024.07.12]"
},
```
> perf: ⚡️ ingress indices are large (and growing)

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- still not seeing logs so are increased warm node capacity temporarily
> perf: ⚡️ try increased warm nodes

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Update vpc_cni to v1.19.3-eksbuild.1 as a part of the upgrade work to Kube 1.30 - [#6715](https://github.com/ministryofjustice/cloud-platform/issues/6715)
> Update vpc_cni to v1.19.3-eksbuild.1

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- test/os_logging_test.go
-  we aren't getting the right instances for our monitoring ng in live, update the instance types
n.b this will add a new monitoring node group to each cluster.
⚠️ ~~In Manager do not use the pipeline to remove the old ng as concourse is running on it.~~ (n/a only for default ng on manager)
> perf: ⚡️ add another monitoring ng

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
This was a temporary measure during migration issues
> Reduce os hot warm

- test/config/config.go
this is to firm up tests in prep for kuberhealthy decommissioning
> test: 💍 improve ns and daemonset test coverage

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.19.0
> chore: 🤖 bump logging, use current_time_index for index date

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
We no longer need the `production-only` ingress controller.
But we do need a `default-non-prod` to mimic the setup we have with modsec.
There are some minor config optimisations that are different to the current `default` ingress, this is intentional as it would be nice to roll those optimisations out to prod, once they are rolled and validated against non-prod workloads.
- there are no workloads affected by this change
> chore: 🤖 rename prod-only -> default-non-prod

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
The role ARN has changed, probably with the creation of the new GitHub team. This amends it to the correct ARN
> Amend admin role ARN to match actual

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/main.tf
```
Error: creating SSM Parameter (/cloud-platform/alertmanager_slack_receivers_import): ValidationException: 1 validation error detected: Value at 'value' failed to satisfy constraint: Member must have length less than or equal to 32768
```
We'll need to look at something like splitting the data somehow to get this working.
> chore: 🤖 delete ssm slack webhook block

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/ssm.tf
this PR sets up ssm parameters for each of our sensitive `components` level `tfvars`, as part of our git-crypt migration work.
> feat: 🎸 prepare ssm parameters for tfvars migration

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/s3.tf
bucket module defaults to `BucketOwnerEnforced` which disables ACLs (recommended AWS practice)
> chore: 🤖 fix s3 bucket config

- terraform/global-resources/elasticsearch.tf
Downscale the live-2 OpenSearch cluster:
- Reduce from 3 to 2 availability zones
- Change to r5.large.search instances from r6g.xlarge.elasticsearch
- Increase data nodes from 3 to 2
- Decrease EBS storage to 50GB per node
- Reduce warm storage instance type to ultrawarm1.medium.elasticsearch
- Changed instance type from r6g.xlarge.elasticsearch to r5.large.search (memory optimized)
- Decreased instance count from 3 to 2
- Maintained dedicated master nodes (3 nodes)
- Maintained zone awareness (reduced from 3 to 2 AZs)
- Changed warm storage from ultrawarm1.large.elasticsearch to 2 nodes of ultrawarm1.medium.elasticsearch
- Decreased EBS volume size from 500GB to 50GB
- Maintained cluster reliability with essential features
- Configuration allows for future upscaling if needed
Related to …
> chore: Downscale live-2 OpenSearch cluster

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- bump prometheus pod memory limit
- https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.21.1
> chore: bump monitoring

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/main.tf
Moving default tags out of the provider to local variables so they can be passed into modules.
Bumping non-prod ingress controllers to include default tags.
> Ingress finops tag

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
Including changes for finops tagging (1.10.6) and logging format changes (1.10.5)
Been tested on live using the non-prod ingress controllers.
> Bumping prod ingress controllers to module 1.10.6

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
network policy additions for calling thanos internally
[release](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.22.0)
> chore: 🤖 bump monitoring module

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[release](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.23.0)
relates to ministryofjustice/cloud-platform#6550
> chore: 🤖 bump monitoring and update subnet-exporter image

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.11.4
> fix: 🐛 modsec syntax

- terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- test/helpers/search.go
- test/modsec_logging_test.go
- test/os_logging_test.go
- test/user_app_logging_test.go
- bump ingresses to pick up logging fix
- add aws sso arn to modsec (so we can run the int tests from local)
- parameterise opensearch delay request
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.12.2
> param opensearch req delay

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
Bump monitoring module to the latest version. This creates an alert that indicates when we are running low on remaining IP Prefixes for the cluster, triggering at 10% remaining.
Relevant issue: [#6571](https://github.com/ministryofjustice/cloud-platform/issues/6571)
> Bump monitoring module to include low ip prefix alert 

- terraform/aws-accounts/cloud-platform-aws/transit-gateway/backend.tf
- terraform/aws-accounts/cloud-platform-aws/transit-gateway/providers.tf
- terraform/aws-accounts/cloud-platform-aws/transit-gateway/transit-gateway.tf
- terraform/aws-accounts/cloud-platform-aws/transit-gateway/versions.tf
Creates a Transit Gateway with three route tables and no attachments.
This will later be peered with the another MOJ transit gateway and the inspection VPC.
> Create cloud platform transit gateway

- terraform/aws-accounts/cloud-platform-aws/transit-gateway/transit-gateway.tf
When we specify the behaviour for default route table attachment/propagation directly in the `transit-gateway` module it is obeyed when a VPC is attached. However, when terraform is run after the attachment this behaviour is overridden by the defaults.
This PR specifies the behaviour in `local.vpc_attachments` to ensure it is obeyed.
> Amend Transit Gateway attachment behaviour

- terraform/aws-accounts/cloud-platform-aws/transit-gateway/transit-gateway.tf
This PR uses a local value to flatten out a map of route table names to routes and attachment IDs.
This ensures that:
* Attachments associated with the `external` route table send traffic via the inspection VPC
* Attachments associated with the `inspection` route table understand all paths traffic can take
* Attachments associated with the `internal` route table send traffic via the inspection VPC
> Supply static routes to TGW route tables

- terraform/aws-accounts/cloud-platform-aws/transit-gateway/transit-gateway.tf
Apparently `name` doesn't result in anything visible in the console, so this PR amends the case of the tag..
> Update tag used to name transit gateway route tables

- terraform/aws-accounts/cloud-platform-aws/vpc/transit-gateway-routes/vpc-attachment.tf
This PR does the following:
* Uses data calls to populate values in the VPC attachment resources
* Modifies the subnets used to hold endpoints to dedicated `transit` subnets
No routing is changed as a consequence of this PR.
> Move `live-1` and `live-2` TGW endpoints to dedicated subnets

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[release notes](https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/releases/tag/1.18.1)
> chore: 🤖 bump external dns module

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- create opensearch s3 snapshot repository with [new opensearch s3 snapshot repository module](https://github.com/ministryofjustice/cloud-platform-terraform-opensearch-snapshot-repository) 
- relates to https://github.com/ministryofjustice/cloud-platform/issues/7333
> feat: create opensearch s3 snapshot repository

- terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- pass the role to opensearch according to aws doc
> In order to register the snapshot repository, you need to be able to pass TheSnapshotRole to OpenSearch Service. You also need access to the es:ESHttpPut action. To grant both of these permissions, attach the following policy to the IAM role whose credentials are being used to sign the request
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-snapshots.html#managedomains-snapshot-registerdirectory
> chore: update iam role

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- improve mem management for operator pod
- double scan concurrency
[release](https://github.com/ministryofjustice/cloud-platform-terraform-trivy-operator/releases/tag/0.13.0)
> chore: 🤖 bump trivy module

- scripts/opensearch/snapshots/restore_snapshots/restore_snapshot.sh
- add the waiting time to snapshot restore script
- prevent jq errors when the snapshot shard are not ready
> fix: wait sometime to prevent jq error

- terraform/aws-accounts/cloud-platform-aws/inspection/firewall_rules.json
- terraform/aws-accounts/cloud-platform-aws/transit-gateway/transit-gateway.tf
This PR achieves the following:
* Tightens the address range for ECP to `10.205.0.0/20`
* Allow traffic to an ECP TLS listening port on 2484
* Implement a DROP rule after the new rule to prevent accidental leakage on other ports
> Tighten address range for ecp

- terraform/aws-accounts/cloud-platform-aws/inspection/firewall_rules.json
- terraform/aws-accounts/cloud-platform-aws/transit-gateway/transit-gateway.tf
This PR restricts traffic so that, instead of broad access to ECP, only access to the specific VPC in ECP that expects incoming traffic is allowed.
> Further ECP tightening

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/gatekeeper.tf
See release details here:
https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/releases/tag/1.16.9
> Bump gatekeeper version to remove canary app

- terraform/aws-accounts/cloud-platform-aws/vpc/transit-gateway-routes/data.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/transit-gateway-routes/routes.tf
Fixes my mistakes from a previous PR.
This PR uses a data call to retrieve the ID of the CP transit gateway, and then routes to ECP via that TGW. This ensures that traffic is routed correctly and moves through the CP inspection VPC on the way out.
> Route to ECP via CP transit gateway

- terraform/aws-accounts/cloud-platform-aws/inspection/firewall_rules.json
- terraform/aws-accounts/cloud-platform-aws/transit-gateway/transit-gateway.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/transit-gateway-routes/routes.tf
This PR adds the following:
* Adds a firewall rule allowing HTTPS traffic to ECP
* Adds a route sending ECP connection test traffic to the CP TGW
* Adds a route to the CP TGW Inspection route table to send ECP connection test traffic to the ECP TGW
The flow in question would be from an EKS node > to the CP TGW > in and out of the inspection VPC > to the **E**CP TGW
> Allow traffic to ECP connection test VPC

- terraform/aws-accounts/cloud-platform-aws/vpc/transit-gateway-routes/vpc-attachment.tf
Apologies; this fixes an error introduced in #4204 
Because the names of the subnets have been changed to prefix the VPC name, the data call needed to be updated too.
> Fix data call to pick transit subnets

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/cluster_autoscaler.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/vpa-crds.tf
For `manager` workspace only in first iteration:
- install VPA CRDs
- deploy VPA recommender helm chart
[release](https://github.com/ministryofjustice/cloud-platform-terraform-cluster-autoscaler/releases/tag/1.14.0)
> chore: 🤖 bump autoscaler for vpa recommmender

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/trivy_operator.tf
[release notes](https://github.com/ministryofjustice/cloud-platform-terraform-trivy-operator/releases/tag/0.14.0)
relates to ministryofjustice/cloud-platform#7421
> chore: 🤖 bump trivy to 0.30.0 chart

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/cert_manager.tf
[release notes](https://github.com/ministryofjustice/cloud-platform-terraform-certmanager/releases/tag/1.18.0)
relates to ministryofjustice/cloud-platform#7420
> chore: 🤖 bump certmanager to latest release

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/logging.tf
[release notes](https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.28.0)
relates to ministryofjustice/cloud-platform#7594
> chore: 🤖 bump logging module for internal ingress logs

- scripts/iam-policy-usage/iam_policy_usage.go
- test/fixtures/internal-ingress-curl.yaml.tmpl
- test/internal_ingress_controller_test.go
This PR adds an integration test and supporting fixture for verifying internal ingress class works as expected.
- deploys usual smoketest ns, helloworld nginx service
- `internal-laa` class based ingress
- `curl-jq` job to check ingress routes internally via a cluster pod
Additional things here:
- fix line break for iam_policy_usage script (stops gofmt lint action fail)
- add `securityContext` fields to helloworld-job template to reduce the amount of warnings we get in other int test runs from gatekeeper violations
relates to ministryofjustice/cloud-platform#7594
> feat: 🎸 add internal ingress available test

- terraform/aws-accounts/cloud-platform-aws/inspection/firewall_rules.json
- terraform/aws-accounts/cloud-platform-aws/transit-gateway/transit-gateway.tf
- terraform/aws-accounts/cloud-platform-aws/vpc/transit-gateway-routes/routes.tf
To support a blue/green deployment approach for the CWA database on ECP, routes and firewall rules for two new VPCs are required.
> Added routes and firewall rules for two new ECP VPC

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/calico.tf
- Install `3.29.x` CRDS
```
crd.projectcalico.org_tiers
policy.networking.k8s.io_adminnetworkpolicies
```
relates to ministryofjustice/cloud-platform#7416
> chore: 🤖 install new tiers and adminnwp CRDs

- terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/calico.tf
- Upgrade Calico Helm release to `3.29.6`
[Release notes](https://github.com/ministryofjustice/cloud-platform-terraform-tigera-calico/releases/tag/0.3.0)
relates to ministryofjustice/cloud-platform#7416
> chore: 🤖 bump calico module for 3.29.6 release

- terraform/aws-accounts/cloud-platform-aws/vpc/main.tf
EIPs, NAT Gateways, and other VPC resources in eu-west-2 are missing the `service-area` tag, which is required for compliance and cost allocation.
Current state:
- 39 EIPs have 4/5 mandatory tags (missing `service-area`)
- 33 NAT Gateways have 4/5 mandatory tags (missing `service-area`)
- Other VPC resources similarly affected
Add `service-area = "Hosting"` to the AWS provider default_tags in the VPC configuration.
This ensures all resources created by this provider automatically receive the tag.
- **Resources affected:** All VPC resources created via this provider (EIPs, NAT Gateways, Route Tables, etc.)
- **Change type:** Tag addition only (no resource recreation)
- **Downtime:** None
Addresses mandatory tagging requirements:
- ✅ business-unit
- ✅ application
- ✅ service-area (added)
- …
> feat: add missing service area tag
