ministryofjustice/cloud-platform-infrastructure

cluster-config/rbac/webops-cluster-admin.yml
Maps github WebOps group members to cluster admin role
=> Make GitHub webops team members cluster admins

README.md
Documenting code in Confluence means that people have to know to look there, and that the documentation can't be reviewed with the code it's meant to document. This can mean that the documentation either doesn't get updated, is updated too soon, or isn't reviewed properly. To that end, we should always document our work as close to the code as possible.
This also clarifies the instructions on committing code and submitting pull requests.
=> Document how we should document our work

concourse/README.md
Rough write up of the concourse ci deployment decision.
=> Concourse ci deployment decision

terraform/cloud-platform/main.tf
Connects to https://github.com/ministryofjustice/cloud-platform/issues/214
=> Disable VPN gateway creation for kube VPC

terraform/global-resources/s3.tf
Connects to https://github.com/ministryofjustice/cloud-platform/issues/74
=> S3 bucket for environments' tfstate

kops/cloud-platform-docs.yaml
**WHAT**
PR to create a new cluster
**WHY**
Creating a cluster as part of the DR documentation tickets.
=> Create 'cloud-platform-docs' cluster

cluster-components/external-dns/cloud-platform-docs-helm-values.yaml
**WHAT**
Add external-dns to 'cloud-platform-docs' cluster
**WHY** 
As part of DR documentation ticket
=> Add external-dns

cluster-components/nginx-ingress/cloud-platform-docs-helm-values.yaml
**WHAT**
Add nginx-ingress to 'cloud-platform-docs' cluster
**WHY**
As part of DR documentation ticket
=> Add nginx-ingress

README.md, docs/logging/README.md, docs/logging/kibana-auth-proxy.md
connects to https://github.com/ministryofjustice/cloud-platform/issues/286
**WHAT**
Added a new directory for logging information, created a README for a landing page and created a kibana auth doc. 
**WHY**
As per https://github.com/ministryofjustice/cloud-platform/issues/286.
=> Add logging directory, create landing page and kibana auth doc

kops/cloud-platform-live-0.yaml, kops/cloud-platform-test-1.yaml
Enables SSH access on all nodes.
Connects to https://github.com/ministryofjustice/cloud-platform/issues/256
=> Replace bastion host on test-1 and live-0

kops/cloud-platform-test-1.yaml
Upgraded version of kubernetes to 1.11 via kops
=> upgraded kubernetes version

cluster-components/nginx-ingress/cloud-platform-test-1-helm-values.yaml
Connects to ministryofjustice/cloud-platform#364
=> Configure ingress-nginx to export prometheus metrics

cluster-components/nginx-ingress/cloud-platform-live-0-helm-values.yaml
Connects to ministryofjustice/cloud-platform#364
=> live-0: configure ingress-nginx to export prometheus metrics

cluster-components/nginx-ingress/cloud-platform-live-0-helm-values.yaml, cluster-components/nginx-ingress/cloud-platform-test-1-helm-values.yaml
**WHY**
Connects to ministryofjustice/cloud-platform#358
=> Increased ingress proxy_buffer_size and client_max_body_size values

kops/cloud-platform-live-0.yaml
Connects to https://github.com/ministryofjustice/cloud-platform/issues/309
=> Enable audit logs on live-0

terraform/cloud-platform-components/external-dns.tf, terraform/cloud-platform-components/helm.tf, terraform/cloud-platform-components/kuberos.tf, terraform/cloud-platform-components/main.tf, terraform/cloud-platform-components/nginx-ingress.tf
- Remove duplicate remote states
- Simplify dependencies
- Add lifecycle rules for helm_release resources
=> Component terraform cleanup

terraform/cloud-platform-components/nginx-ingress.tf
Also remove invalid & unused configuration option.
=> Fix nginx-ingress chart version

heptio_ark/README.md, heptio_ark/config.yaml, heptio_ark/credentials-ark, heptio_ark/deployment.yaml, heptio_ark/helm/values.yaml, heptio_ark/heptio-ark-policy.json, heptio_ark/kube-system-schedule.yaml, heptio_ark/prereq.yaml
heptio ark place holder for future work
=> heptio ark place holder for future work

haproxy/haproxy.tf, haproxy/userdata.sh.tpl, haproxy/variables.tf, haproxy/vpc.tf, haproxy/weights.tpl
**Why**
https://cbonte.github.io/haproxy-dconv/1.9/configuration.html#5.3
=> Fix HAproxy DNS

terraform/cloud-platform-components/templates/kube-prometheus.yaml.tpl
Setting limits and requests to the same value should also place this Pod in the guaranteed QoS class.
=> Increase CPU and memory requests & limits for prom

README.md
A few minor changes to the README mainly from Paul after going through the cluster creation part of the instructions
=> Additions and Changes to README

haproxy/alb.tf, haproxy/cert.tf, haproxy/cloudwatch.tf, haproxy/haproxy.tf, haproxy/sg.tf, haproxy/variables.tf, haproxy/vpc.tf, haproxy/weights.tpl
* Unique names for ALB and targets
* AWS ACM: refine cert validation
* haproxy config: prefer ipv4 addresses
* AWS resource tagging
* Cloudwatch alerts for the ALB
=> Update haproxy module

terraform/cloud-platform/templates/kops.yaml.tpl
* disable anonymous access for kubelet
* change cloudLabel from boolean to string
=> Disable anon access for kubelet

terraform/cloud-platform-components/main.tf, terraform/cloud-platform-components/prometheus.tf
Also add missing lifecycle rules for helm_release resources.
=> Remove hardcoded config paths

terraform/README.md, terraform/cloud-platform-dr/README.md, terraform/cloud-platform-dr/etcd_ebs.tf, terraform/cloud-platform-dr/outputs.tf, terraform/cloud-platform-dr/variables.tf
**WHAT**
Create an automated process to restore etcd ebs volumes 
**WHY**
We need a process to be able to restore etcd data in a disaster scenario where live data is either corrupted or not accessible for any reason.
**What does this PR do?**
This PR contains terraform code to identify and restore the latest snapshot from all 6 etcd ebs volumes and tag accordingly. 
There is also documentation on the steps required.
=> Etcd EBS volume restore from snapshots

terraform/cloud-platform-components/main.tf
Add default AWS region to Main.tf file for cloud-platforms-components
=> Add Default AWS region on Main.tf

terraform/global-resources/elasticsearch.tf
This is to improve performance and stability of the cluster.
=> Increase es-live storage and add dedicated masters

terraform/cloud-platform-components/nginx-ingress.tf
Increased proxy-body-size to 50m as it fails when file is more than 16m
=> Increased proxy-body-size to 50m as it fails when file is more than 16m

terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
Overview
---
To allow us to provide appropriate actions on alarms this PR will enable a nice output in Slack.
=> Formatting slack alerts

terraform/cloud-platform-components/README.md
Changes made to the instructions to be inline with the new stable prometheus chart
=> changes to instructions to match new prom chart

terraform/cloud-platform-components/cert-manager.tf
This brings in a new version of cert-manager that addresses some issues.
=> Upgrade cert-manager chart

bin/terraform-container.sh
new script in the bin/  :
- the script ensure mandatory environment variables are there. 
- Run a docker container, mounting the relevant files as volume.
=> add script that runs a docker container

terraform/cloud-platform-components/cert-manager-dsd.tf, terraform/cloud-platform-components/external-dns-dsd.tf, terraform/cloud-platform-components/external-dns.tf, terraform/cloud-platform-components/main.tf, terraform/cloud-platform-components/nginx-ingress-acme.tf, terraform/cloud-platform-components/nginx-ingress.tf
Connects to https://github.com/ministryofjustice/cloud-platform/issues/737
=> live-0: external-dns for dsd

terraform/cloud-platform-components/cert-manager-dsd.tf, terraform/cloud-platform-components/external-dns-dsd.tf, terraform/cloud-platform-components/external-dns.tf, terraform/cloud-platform-components/main.tf, terraform/cloud-platform-components/nginx-ingress-acme.tf
This PR includes the changes from #205 and #212
=> Reconcile live-1 with live-0 config

terraform/cloud-platform-components/resources/prometheusrule-alerts/Custom-Alerts.md, terraform/cloud-platform-components/resources/prometheusrule-alerts/application-alerts.yaml, terraform/cloud-platform-components/resources/prometheusrule-alerts/node-alerts.yaml
WHAT
Application alerts for CP team namespaces and node alerts for K8s cluster 
Also changes to current alerts and documentation 
WHY
CP Team need to be alerted when there are possible issues with cluster application and resources
=> Application and Node Alerts for CP Team - live1

terraform/cloud-platform/main.tf
**Why**
New provider release, used to trim empty strings now now just sends them to auth0
https://github.com/yieldr/terraform-provider-auth0
=> Fix auth0 callbacks

terraform/cloud-platform-components/opa.tf, terraform/cloud-platform-components/resources/opa/opa-default-system-main.yaml, terraform/cloud-platform-components/resources/opa/policy-ingress-conflicts.yaml, terraform/cloud-platform-components/templates/opa/values.yaml.tpl
Reverts ministryofjustice/cloud-platform-infrastructure#250
=> Install Open-policy-agent and create a ingress-conflicts policy

cloudformation/aws-account-baseline-templates/aws-iam-suspend-inactive-users/README.md, cloudformation/aws-account-baseline-templates/aws-iam-suspend-inactive-users/package_template.sh, cloudformation/aws-account-baseline-templates/aws-risk-credentials-exposed/README.md, cloudformation/aws-account-baseline-templates/aws-s3-enable-encryption-block-public-access/README.md, cloudformation/aws-account-baseline-templates/aws-s3-enable-encryption-block-public-access/aws-s3-enable-encryption-and-block-public-access.yaml, cloudformation/aws-account-baseline-templates/aws-s3-enable-encryption-block-public-access/lambda/s3-bucket-block-public-access.py, cloudformation/aws-account-baseline-templates/aws-s3-enable-encryption-block-public-access/lambda/s3-bucket-enable-default-encryption.py, cloudformation/aws-account-baseline-templates/aws-sns-slack-integration/README.md
fix commands in readme, sns topic, add s3 exception to public access block, lambda
=> fix template

terraform/cloud-platform-components/README.md
This README.md is under cloud-platform-components. Updated README.md with Open-Policy-Agent information.
=> Updated README.md with Open-Policy-Agent information

cloudformation/aws-account-baseline-templates/aws-iam-user-roles-groups/README.md
=> Minor typo.

terraform/cloud-platform-components/resources/opa/policy-ingress-conflicts.yaml
This is to allows users to make changes to their ingress definitions
Relates to #862
=> Alter policy-ingress-conflicts

terraform/cloud-platform/main.tf
Required to get the proxy working, see also https://github.com/ministryofjustice/cloud-platform-environments/pull/786
=> Add kibana-audit callback url in auth0 client

terraform/cloud-platform-account/main.tf
Change AWS region for tfstate to correct region
=> Change AWS region for tfstate

terraform/cloud-platform-components/resources/tzcronjobber/cronjobber-crd.yaml, terraform/cloud-platform-components/resources/tzcronjobber/cronjobber-deploy.yaml, terraform/cloud-platform-components/resources/tzcronjobber/cronjobber-rbac.yaml, terraform/cloud-platform-components/tzcronjobber.tf
**What**
Deploy TZ cronjobber (copied from https://github.com/hiddeco/cronjobber). Image is built by Concourse.
**Why**
Requested in https://github.com/ministryofjustice/cloud-platform/issues/804
=> Cronjobber

create-cluster.sh, terraform/cloud-platform-components/prometheus.tf
* Remove .terraform directory before each `terraform apply`
* Run `helm repo update` before installing components
* Remove a cyclic dependency, by creating 'monitoring' namespace
The build script still fails to install fluentd, because of https://github.com/ministryofjustice/cloud-platform/issues/1030
=> Cluster build fixes

terraform/cloud-platform-components/resources/storageclass.yaml
Add encryption to EBS volume on creation by adding to `encrypted: "true"` to storageclass parameters
=> Add encryption to dynamic storage creation

kops/live-1.yaml
This is to apply the change to increase node disk size to 256
=> Apply the change increase node size rootVolumeSize: 256

kops/live-1.yaml, terraform/cloud-platform/kops.tf, terraform/cloud-platform/main.tf, terraform/cloud-platform/templates/kops.yaml.tpl, terraform/cloud-platform/variables.tf
- Increase default node count to 18
- Upgrade kubernetes version to 1.11.10
- Override non-live cluster node count to `3` nodes.
- Simplify some expressions
=> Increase default node count, upgrade to 1.11.10 plus some refactoring

terraform/cloud-platform-components/nginx-ingress-acme.tf, terraform/cloud-platform-components/opa.tf, terraform/cloud-platform-components/resources/opa/policies/cloud_platform_admission.rego, terraform/cloud-platform-components/resources/opa/policies/cloud_platform_admission_test.rego, terraform/cloud-platform-components/resources/opa/policies/ingress_clash.rego, terraform/cloud-platform-components/resources/opa/policies/ingress_clash_test.rego, terraform/cloud-platform-components/resources/opa/policies/service_type.rego, terraform/cloud-platform-components/resources/opa/policies/service_type_test.rego, terraform/cloud-platform-components/templates/opa/values.yaml.tpl
Connects to https://github.com/ministryofjustice/cloud-platform/issues/1027
=> Create OPA policy to block LoadBalancer type Services

kops/live-1.yaml, terraform/cloud-platform/templates/kops.yaml.tpl
This PR closes https://github.com/ministryofjustice/cloud-platform/issues/1043.
=> Bump Kubernetes version to 1.12.10

kops/live-1.yaml, terraform/cloud-platform/templates/kops.yaml.tpl
Change kops instance template and live-1 manifest.
=> Bump master instance size

terraform/cloud-platform-components/nginx-ingress-acme.tf
This is related to 
https://github.com/ministryofjustice/cloud-platform-infrastructure/issues/328
Also updated the dependency for  nginx-errors service as ingress controllers release is failing as it is looking for nginx-errors service.
=> Nginx add error

create-cluster.rb
Simplify the cluster build script
=> Simplify build script

terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
- Increasing the PVC request to 500Gi. 
- This change has already been applied.
=> bump PVC from 100Gi to 500Gi

smoke-tests/makefile
We have added AWS gems to the project, so the
docker image needed to be updated.
=> Bump the docker image version

create-cluster.rb
**Why**
Things go awry if the script is started from the Macos env
=> sanity check if running in container

smoke-tests/.gitignore, smoke-tests/Dockerfile, smoke-tests/makefile
* Improve the build process
* Bump the docker image version
* Install latest bundler, inside the docker image
=> Update the docker image, and its build process

smoke-tests/spec/kiam_helper.rb
When I ran the integration tests for a new cluster
the kiam test failed.
On investigation, this was because the "trust
relationships for the relevant IAM role are
specific to a cluster.
https://console.aws.amazon.com/iam/home?region=eu-west-2#/roles/integration-test-kiam-iam-role?section=trust
i.e. whichever cluster is being tested when the
role is created, only that cluster's nodes were
allowed to assume the role.
This commit queries the list of 'principals' in
the role's trust relationships, and adds the
current cluster if its nodes are not listed.
This has to be done by tweaking and replacing the
whole policy as a JSON document, because of
limitations in the AWS API.
I tried setting a wildcard pattern in the list of
principals, to avoid having to do this for every
new cluster, but AWS …
=> Fix kiam test for new clusters

terraform/cloud-platform-components/nginx-ingress-acme.tf
Depends on: https://github.com/ministryofjustice/cloud-platform-custom-error-pages/pull/3
=> Use cloud-platform-custom-error-pages:0.4

smoke-tests/spec/namespace_annotations_spec.rb
Now that
https://github.com/ministryofjustice/cloud-platform-environments/pull/1200
has been merged, this test now passes in live-1
=> Enable the namespace annotations test

terraform/global-resources/elasticsearch.tf
As part of this change we will implement a curator to purge data after
one year.
=> Increase ebs volume size on live-1 audit cluster

smoke-tests/spec/modsec_spec.rb
increased wait time to 20 for ingress creation as getting a service 503 unavailable when 10
=> increased wait time to 20 for ingress creation

terraform/cloud-platform-components/cluster-backup-checker.tf
Related to: https://github.com/ministryofjustice/cloud-platform-cluster-backup-checker/pull/7
=> Bumped the version to include standardrb fixes

terraform/cloud-platform-components/fluentd.tf, terraform/cloud-platform-components/prometheus.tf
What:
Creating logging namespace as part of infrastructure
Adding annotations for logging and monitoring
Why:
Creating test cluster failed to deploy monitoring and logging OPA need the namespace annotations for monitoring and logging to schedule workload in master.
=> Add ns annotations

terraform/cloud-platform-components/fluentd.tf, terraform/cloud-platform-components/prometheus.tf
What:
Adding "component" labels for monitoring and logging
Why:
To avoid conflicts from environment repo. 
Update to PR: https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/409
=> Add ns labels component

terraform/cloud-platform-components/external-dns.tf
=> correct chart version - external-dns

create-cluster.rb
This will search for all alertmanager slack webhook and replace with a dummy value.
Update to: https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/406
=> Replace all webhook with dummy values

terraform/cloud-platform-components/eventrouter.tf
- adds Eventrouter helm release
- Eventrouter gathers events from all namespaces and output them to stdout, for them to be picked up by fluentd.
=> add eventrouter helm_release

create-cluster.rb, terraform/cloud-platform/templates/kops.yaml.tpl, terraform/cloud-platform/variables.tf
**Why**
live cluster is upgraded to 1.13, new tests will be deployed with the same release
=> Build 1.13

smoke-tests/spec/external_dns_helper.rb
- fix method renaming gone wrong.
=> Extdns test fix

terraform/cloud-platform-components/resources/prometheusrule-alerts/application-alerts.yaml, terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
=> Correct spelling of KubePersistentVolumeFullInFourDays

smoke-tests/spec/external_dns_helper.rb, smoke-tests/spec/external_dns_spec.rb
- Removed test, that was adding too much complexity.
=> clean up, remove unecessary test

recycle-node.rb
This is related to https://github.com/ministryofjustice/cloud-platform/issues/1153
This recycle-node.rb script will replace the oldest worker node.
-> Drain the oldest node
-> Terminate the drained node.
=> Recycle node

smoke-tests/spec/error_page_spec.rb, smoke-tests/spec/fixtures/default-backend.yaml.erb, smoke-tests/spec/kubernetes_helper.rb
This is related to https://github.com/ministryofjustice/cloud-platform/issues/1151
=> Default backend integration tests

helm-charts/fluentd-es/config/output.conf, terraform/cloud-platform-components/nginx-ingress-acme.tf
**Why**
right now all the log values get to ES as String and can't be sorted properly
seems the index must be renamed, the existing one refuses to update
=> correct Ingress Numeric values 

helm-charts/fluentd-es/Chart.yaml, helm-charts/fluentd-es/config/output.conf, helm-charts/fluentd-es/values.yaml
**Why**
logs exception better
had to change Nginx index name, to persuade ES to update
=> upgrade fluentd

terraform/cloud-platform-components/metrics-server.tf
- copied the variables from the eks-component repo
=> add extra networking variable

smoke-tests/spec/certificates_spec.rb, smoke-tests/spec/kubernetes_helper.rb
This PR introduces a certificate check to confirm the essential certs exist in the cluster. 
Right now, it checks the certificate resources : 
- ingress-controller cert
- cert-manager certs
=> certificates.certmanager.k8s.io spec

smoke-tests/spec/kubernetes_helper.rb, smoke-tests/spec/prometheusrules_spec.rb
The PR introduces an integration test to ensure all essential Prometheus Rules exist.
=> prometheusrules.monitoring.coreos.com

smoke-tests/spec/kubernetes_helper.rb
This PR slightly reduces the duplication of code in the kubernetes_helper
file, and hopefully makes it a little easier to read.
=> Refactor the kubernetes_helper file

smoke-tests/spec/error_page_spec.rb
This clarifies the intention of the method.
=> Rename `open_url` to `expect_open_url`

terraform/cloud-platform-network/main.tf, terraform/cloud-platform-network/outputs.tf, terraform/cloud-platform/outputs.tf
- Moved outputs
- Added manually tags (pending to set them as variables)
=> Minor changes in outputs and tags

terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
This was requested under https://github.com/ministryofjustice/cloud-platform/issues/1382
=> Add PrometheusTargetScrapesDuplicate alarm to null

kops/live-1.yaml
This was requested in https://github.com/ministryofjustice/cloud-platform/issues/1316
=> Upgrade Kubernetes to 1.13.12

smoke-tests/Dockerfile, smoke-tests/makefile
* fix binstubs for rspec
* update tag version
* improve the makefile
* add aws-iam-authenticator
=> Fix integration tests

smoke-tests/spec/fixtures/tzcronjob.yaml.erb, smoke-tests/spec/tzcronjob_spec.rb
This integration test confirms that TZcronjob are being scheduled as expected.
=> Tzcronjob spec

terraform/cloud-platform-components/resources/cloudwatch-exporter.yaml
- Add SQS and SNS metrics which was removed in the PR #468.
- Remove ES Metrics to bare minimum 
To keep overall metrics count to minimum in order to reduce the API load.
=> Add SQS and SNS metrics

recycle-node.rb
Before draining a node, delete any pods running on
it which are in "ImagePullBackOff" or 
"CrashLoopBackOff" state.
Such pods prevent the node from being drained (you
get a misleading error message about not evicting
the pod because it would violate its pod
disruption budget).
This change should stop the node recycler script
from failing due to this problem.
closes https://github.com/ministryofjustice/cloud-platform/issues/1549
=> Delete stuck pods when recycling oldest node

terraform/global-resources/iam/main.tf
- Updated password policy to 12 characters
- Updated Poornima's username to the one that matches AWS Console
=> Updated password policy and username

terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
Updated with the right selectors for kubeScheduler and kubeControllerManager
=> Enable kubeScheduler and kubeControllerManager

smoke-tests/spec/master_nodes_spec.rb
* 3 master nodes
* All running standard master node pods
* One running a dns-controller pod
=> Add tests for master nodes

terraform/global-resources/s3.tf
This is for prometheus-thanos to save the metrics in this bucket
=> Create bucket for thanos

recycle-node.rb
This was changed as part of the 1.14.10 upgrade
=> Change WORKER_NODE_INSTANCE_GROUP constant to reflect new name

create-cluster.rb
Removed conditional `if` for the sleep() because now we have a default value
=> Update sleep() function

terraform/cloud-platform-components/prometheus.tf
New release module 0.0.6, more information in the module release page.
=> New prometheus module release

terraform/cloud-platform/main.tf
This call back is for kibana in dsd account.
=> Added call back for dsd-kibana

terraform/cloud-platform-components/logging.tf
This version comes with a new Helm chart version of fluentd which supports tolerations.
=> New module logging module version

smoke-tests/spec/kubernetes_helper.rb, smoke-tests/spec/starterpack_spec.rb
Add tests for checking whether starter pack has deployed correctly by checking their ingress urls
=> Tests for starter pack

kops/live-1.yaml, makefile, recycle-node.rb, terraform/cloud-platform/templates/kops.yaml.tpl
Kops and k8s 1.15 upgrade in live-1
This is related to 
`https://github.com/ministryofjustice/cloud-platform/issues/1715`
=> Kops and k8s 1.15 upgrade live-1

terraform/global-resources/iam/main.tf
Give Imran access to AWS Console.
=> Added Imran to AWS

smoke-tests/spec/cert_manager_spec.rb, smoke-tests/spec/certificates_spec.rb, smoke-tests/spec/crds_spec.rb, smoke-tests/spec/issuers_spec.rb
Updated Integration tests, considering cert-manager 1.14 upgrade.
Will merge this PR after the cert-manager upgrade
=> Updated cert-manager tests

terraform/cloud-platform-components/cert-manager.tf
This module have a dependency for prometheus.
=> Update cert-manage to use the latest module

terraform/cloud-platform-components/monitoring.tf
Updated to the latest monitoring module, which has support for EKS and other improvements. Besides that, it also changes how the module works internally.
=> Updated to the latest the Monitoring module

terraform/cloud-platform-components/nginx-ingress-acme.tf, terraform/cloud-platform-components/velero.tf
More details in https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/0.0.4
=> Fixing sharing memory issue

terraform/cloud-platform-components/opa.tf, terraform/cloud-platform-eks/components/main.tf
bumped to latest opa module and eks-comp module
=> Opa valid hostname

terraform/cloud-platform-components/main.tf
=> Deleted DSD's AWS Terraform Provider

terraform/cloud-platform-eks/components/main.tf
An issue was identified and fixed in PR https://github.com/ministryofjustice/cloud-platform-terraform-eks-components/pull/17
=> Bump EKS components version to fix interpolation issue

smoke-tests/spec/prometheusrules_spec.rb
This PR fixed the integration tests fails due to Prometheus Helm Chart Upgrade.
=> Fix integration tests due to Prometheus Upgrade

terraform/cloud-platform-components/starter-pack.tf
More information about this change here: https://github.com/ministryofjustice/cloud-platform-terraform-starter-pack/commit/18e712aeefd9661844891c87a819fa4e09c9b8c3
=> Fixed dependency between NS creation and secret creation

terraform/cloud-platform-components/starter-pack.tf
More information here: https://github.com/ministryofjustice/cloud-platform-terraform-starter-pack/releases/tag/0.0.7
=> Apply changes Poornima did to starter pack

smoke-tests/spec/external_dns_spec.rb
We have sync configured in external-dns. This test will cover deleting the A record, when ingress is deleted.
=> Add integration test for external-dns

makefile
=> Use tools image version 1.17

smoke-tests/spec/kiam_helper.rb
Add wait time for add_principal to update_assume_role_policy.
=> Update Kiam integration test

create-cluster.rb
This PR gives `create-cluster.rb` script support for creating EKS clusters.
=> Adding support for creating EKS clusters

terraform/cloud-platform-components/monitoring.tf
This new version of the monitoring module introduces new ES metrics
=> bump monitoring module

terraform/cloud-platform-eks/components/components.tf
Add missing permissions to concourse
=> Add missing permissions to concourse

terraform/cloud-platform-components/kuberos.tf
Update kuberos.tf to use the module
https://github.com/ministryofjustice/cloud-platform-terraform-kuberos
=> Update kuberos.tf to use the module

recycle-node.rb, smoke-tests/spec/kubernetes_helper.rb, terraform/cloud-platform-components/README.md, terraform/cloud-platform-eks/README.md
We are going to change the default branch of the
cloud-platform-infrastructure repository to be
"main" rather than "master".
This change anticipates that one.
NB: This PR should not be merged until after the default branch of the infrastructure repo. has been changed.
=> Master to main

terraform/cloud-platform-components/logging.tf
This cronjob runs every day to delete indices older than 30 days
=> Add elastic-search curator cronjob in logging

terraform/cloud-platform/main.tf
In the previous PR to include the template changes done to kops manifest due to the upgrade against 1.15.12
=> Updated kops module with kops 1.15.12 changes

create-cluster.rb, terraform/cloud-platform/variables.tf
Cluster size logic moved to terraform and cleaned up the create-cluster script.
=> Cluster size is now detected automatically

terraform/cloud-platform-eks/components/components.tf, terraform/cloud-platform-eks/main.tf, terraform/cloud-platform-eks/outputs.tf, terraform/cloud-platform/outputs.tf
This PR is to update auth0 to create multiple application (kubernetes and components)
Install sonarqube from module
https://github.com/ministryofjustice/cloud-platform-terraform-sonarqube
=> Update auth0 to use the latest module and install sonarqube in EKS

recycle-node.rb
I put the wrong kubernetes version number in #806
=> Use the right version number this time

kops/live-1.yaml, terraform/cloud-platform-eks/main.tf, terraform/cloud-platform/main.tf, terraform/cloud-platform/outputs.tf, terraform/cloud-platform/variables.tf
Update Auth0 to use latest module
* Add kubernetes auth0_client with kuberos login callback
* Remove kuberos login call back from components
* Add outputs for auth0_client kubernetes
=> Update Auth0 to use latest module

terraform/cloud-platform-eks/main.tf, terraform/cloud-platform/main.tf
This will enable Auth0 module to maintain a seperate callback URL for EKS
=> Update Auth0 module to set callback for EKS.

terraform/cloud-platform-components/components.tf
It can be easily disabled setting `enable_fluent_bit` to false.
=> Added fluentbit

terraform/cloud-platform-components/components.tf
- Fixed  nginx path's names
- Removed under filters 
- More info here: https://github.com/ministryofjustice/cloud-platform-terraform-logging/pull/8/files
=> Second iteration of fluent-bit

terraform/cloud-platform/main.tf
Add dsd-kibana call back url in auth0 module v1.1.2
=> Add dsd-kibana call back url in auth0 module v1.1.2

terraform/cloud-platform-components/components.tf
To fix error, required key not provided @ data['timestring']
=> Updated source in curator cronjob to creation_date

terraform/cloud-platform-eks/README.md
GitHub Actions outlined the following errors in the EKS directory, which
are fixed in this commit:
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/827/checks?check_run_id=944549517
=> Fix linting errors outlined in GitHub Action

terraform/cloud-platform-components/components.tf
To use source as name and timestring, this will delete the index older than 30 days with timestring "%Y.%m.%d"
=> Update elasticsearch-curator filter

terraform/cloud-platform-account/main.tf
Also, this PR clean up resources and provider configurations that are not in use anymore.
=> Updated baselines to the up to date terraform module

terraform/cloud-platform-components/components.tf
We need to start testing the ownership of an ingress controller. We decided to start with our monitoring namespace
=> Added ingress controller for the monitoring namespace.

create-cluster.rb
Add disable_alerts to install_components_kops.
This is related to [2187](https://github.com/ministryofjustice/cloud-platform/issues/2187)
=> Update create-cluster script.

terraform/cloud-platform-eks/components/components.tf, terraform/cloud-platform-eks/outputs.tf
- Add dependency for prometheus to install concourse
- Add CreateOpenIDConnectProvider role, for concourse manager user to create eks cluster
- Set oidc client_secret to sensitive
=> Update concourse to use latest module version 1.2.3

create-cluster.rb
Add "AWS_REGION" for eks update-kubeconfig
=> Update create-cluster script

terraform/cloud-platform-components/components.tf
More information about changes [here](https://github.com/ministryofjustice/cloud-platform-terraform-certmanager/pull/9)
=> Upgraded certmanager module to latest

terraform/cloud-platform-components/components.tf
Ingress controller to look/watch monitoring namespace.
=> Ingress controller for monitoring namespace

terraform/cloud-platform-eks/components/components.tf
Add AttachUserPolicy permission for concourse user
=> Add additional permissions for concourse user

terraform/cloud-platform-components/components.tf
More information about this PR here: https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/44
=> Update the monitoring module to include multiple alerts

terraform/cloud-platform-components/components.tf
More information about this here: https://github.com/ministryofjustice/cloud-platform-terraform-logging/pull/13
=> Updated fluentbit regex to include all ingress controller pods

kops/live-1.yaml
Update node count to 25, this is already updated in the template, this is after applying the change in cloud-platform repo
=> Update node count to 25

terraform/cloud-platform-eks/components/components.tf
* Removed persistence for sonarqube
* Add sonar-build-breaker plugin for sonarqube
=> Updated terraform-sonarqube to v0.0.2

terraform/cloud-platform-components/components.tf
More info here: https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/49
=> Fixing indentation

terraform/cloud-platform-eks/components/components.tf
See https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/10/files
=> Use cloud-platform-terraform-concourse v1.2.8

terraform/cloud-platform-eks/components/components.tf
Fixes hoodaw-secret -> IAM user dependency
=> use concourse module 1.2.9

recycle-node.rb
* Replace hard-coded strings with a constant
* Reduce code duplication via shared method
=> Refactor the recycle-node.rb script

terraform/cloud-platform-eks/components/components.tf
Add "iam:TagUser" for concourse user
=> Add "iam:TagUser" for concourse user

terraform/cloud-platform-components/components.tf
More information about this in  https://github.com/ministryofjustice/cloud-platform-environments/pull/3432 and https://github.com/ministryofjustice/cloud-platform-terraform-kuberos/pull/2
=> Including network policies within kubero's terraform module

terraform/cloud-platform-components/components.tf
More information [here](https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/0.1.5)
=> Added network policies inside logging's terraform module

terraform/cloud-platform-components/components.tf
Including resourceQuotas and LimitRange
=> New Prometheus module version

terraform/cloud-platform-components/components.tf
More information in https://github.com/ministryofjustice/cloud-platform-terraform-kuberos/pull/4
=> Update Kuberos module to the latest (Limits, Quotas, Ingress)

terraform/cloud-platform-components/components.tf
This is fallback ingress-controller
=> Add ingress_controllers_k8snginx_fallback module

terraform/cloud-platform-components/components.tf
This PR includes the latest version of the logging module, which set up fluentbit to handle the audit logs in a new index.
=> Fluentbit handling Audit logs

terraform/cloud-platform-components/components.tf
Version bump that has owasp rules enabled and increase replicas to 4
=> module version bump to 0.0.3 - Enable owasp rules 

smoke-tests/spec/daemonsets_spec.rb, smoke-tests/spec/prometheusrules_spec.rb, terraform/cloud-platform-components/components.tf, terraform/cloud-platform-eks/components/components.tf
- Fix the integration tests
- Make fluent-bit enabled by default in both sides (EKS and KOPS)
=> fluent-bit fixes

terraform/cloud-platform-components/docker-registry-cache.tf
change ns annotations for monitoring the namespace
=> Change annotation for docker-registry-cache 

terraform/cloud-platform-components/components.tf
module upgrade for various components which have had a new NS annotation added to monitor everything within the NS
=> Module version upgrades for NS annotations

terraform/cloud-platform-components/components.tf
New monitoring module with changes to annotations and rules
=> New monitoring module with changes to annotations and rules

terraform/cloud-platform-account/main.tf
latest release (update) cloud-platform-terraform-awsaccounts-iam
=> refresh iam-user-list

terraform/cloud-platform-eks/components/components.tf
Update all EKS components modules to latest releases
=> Update all EKS components modules

terraform/cloud-platform-components/components.tf
This version suppresses the "Server" header in http responses
=> Use v0.1.3 of teams ingress controller

terraform/cloud-platform-eks/components/components.tf
This should suppress the "Server" header in HTTP responses
=> Use v0.0.11 of ingress-controller module

terraform/cloud-platform-components/components.tf
update version to 0.0.5 which has the validation webhook enabled
=> Update modsec ic module version

terraform/cloud-platform-components/components.tf
This enables cross-zone load-balancing on the NLB
=> Use teams-ingress-controller module v0.1.4

terraform/cloud-platform-components/components.tf
This enables cross-zone load-balancing on the NLB
=> Use v0.0.6 of the modsec ingress controller module

terraform/cloud-platform-components/components.tf
This enables cross-zone load-balancing on the NLB
=> Use k8s ingress controller module 0.0.2

terraform/cloud-platform-components/components.tf
This enables cross-zone load-balancing on the NLB
=> use ingress-controller module v0.0.12

terraform/cloud-platform-eks/components/components.tf
This concourse release just renamed a field. More information [here](https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/19)
=> Upgraded to the latest concourse module

terraform/cross-account-IAM/pathfinder-to-analytical-platform-prod.tf
Following https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/access-cross-aws-resources.html
=> PAT-1480 Create cronjob to push national extract to analytical platform

terraform/cross-account-IAM/pathfinder-to-analytical-platform-prod.tf
`s3.PutObject` -> `s3:PutObject` etc.
=> Fix policy actions

terraform/cloud-platform-account/main.tf, terraform/cloud-platform-eks/components/components.tf
- Update to the latest module version
- New version of concourse module
=> new release concourse module

terraform/cloud-platform-account/main.tf
=> Update to the latest module versionn

terraform/cloud-platform-eks/components/components.tf
=> Update concourse module

terraform/cloud-platform-eks/components/components.tf
Added athena permissions to concourse user in the module
=> Bump concourse module version 1.5.3

terraform/cloud-platform-eks/components/components.tf
Added permissions to concourse user to have full access to AWS glue
=> Bump concourse module version 1.5.4

terraform/global-resources/elasticsearch.tf
- Change EBS volume size to 1.5TB
- Increase data instance size & EBS volume size
=> Embiggen ES node types & EBS volumes

smoke-tests/spec/kiam_annotations_spec.rb, smoke-tests/spec/kubernetes_helper.rb
This test checks for kiam annotations in the namespaces that requires it.
=> Kiam annotation spec

terraform/cloud-platform-components/components.tf, terraform/cloud-platform-components/main.tf, terraform/cloud-platform-eks/components/components.tf
More information about the change in https://github.com/ministryofjustice/cloud-platform-terraform-logging/pull/29
=> Updated logging module to latest version (hopefully will fix divergence)

terraform/cloud-platform-eks/components/components.tf
Changes [here](https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/28). Added authenticated pulls to avoid hitting API limits in concourse.
=> Upgraded concourse to latest

terraform/cross-account-IAM/pathfinder-to-analytical-platform-preprod.tf
Reverts ministryofjustice/cloud-platform-infrastructure#1052
The policy is needed in both accounts
=> Revert "fix pf s3"

terraform/cloud-platform-eks/components/components.tf
New Prometheus Operator version, more information in https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/65
=> Update EKS components.tf with the new Prometheus Operator

terraform/cross-account-IAM/pathfinder-to-analytical-platform-prod.tf
=> fix pf s3 prod

terraform/cloud-platform-components/components.tf, terraform/cloud-platform-components/k8s-resources.tf
- New storage class
- Upgrade to latest Prometheus
This fix the divergence pipeline for components
=> Prometheus Upgrade

terraform/cloud-platform-components/components.tf
It isn't a release yet because it is just a test, if everything goes fine and we are happy I will do the proper release
=> Update Prometheus Operator - split Prometheus

terraform/cloud-platform-components/components.tf, terraform/cloud-platform-eks/components/components.tf
This release include  PRs:
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/69
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/75
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/76
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/77
=> Update monitoring module to 1.2.0

terraform/cloud-platform-components/components.tf, terraform/cloud-platform-eks/components/components.tf
This will include the fix for elasticsearch curator.
=> Bump logging versions to 1.0.7

terraform/cloud-platform-account/main.tf
As I had problems with pipeline for 3  separate terraform plans - splitting https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1090 into 3 commits
=> remove-iam-mourad-david-leavers-terraform-cloud-platform-account

terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-account/main.tf
As I had problems with pipeline for 3  separate terraform plans - splitting https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1090 into 3 commits
=> remove-iam-mourad-david-leavers-terraform-aws-accounts

terraform/cloud-platform-account/main.tf
This was requested in this PR:
https://github.com/ministryofjustice/cloud-platform-environments/pull/4388
=> Add new bucket to the list of public access exceptions

terraform/cloud-platform-account/main.tf, terraform/cloud-platform-account/outputs.tf, terraform/cloud-platform-eks/main.tf, terraform/cloud-platform/main.tf, terraform/cloud-platform/outputs.tf
IMHO they shouldn't even exist but because it might be controversial this change update the route and follow the same method that was before.
=> Updated terraform remote state (a.k.a fixing divergence pipelines)

terraform/aws-accounts/README.md
As discussed [here](https://mojdt.slack.com/archives/C514ETYJX/p1615284802014500)
=> Update network -> VPC

terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-components/components.tf, terraform/cloud-platform-components/components.tf
* newer chart
* Dynamo metrics
=> upgrade cloudwatch_exporter

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/cloud-platform-components/components.tf, terraform/cloud-platform-components/components.tf
Use latest monitoring module 1.6.2 that removes NodeFilesystemSpaceFillingUp alert
=> Use latest monitoring module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Tested in cp-0904-0800 test cluster
=> Update external-dns Helm Chart in EKS to latest

terraform/cloud-platform-components/components.tf
More info in https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/89
=> Adding resource quotas to Prometheus pod

kops/live-1.yaml, terraform/cloud-platform/main.tf
=> Upgrading Kubernetes to 1.18.2

kops/live-1.yaml, terraform/cloud-platform/main.tf
This fixes kops divergence pipeline
=> Disable ingress instance group in kops

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/variables.tf
Update hostedzone of manager cluster. 
Enable is_live_cluster for manager
=> hostzone changes and enable is_live_cluster for manager

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Add VijayVeeranki user to the list of users to access EKS
=> Add VijayVeeranki user to the list of users to access EKS

create-cluster.rb, destroy-cluster.rb
As we now moved to the new terraform directory structure.
=> Update create and destroy cluster script with new folder structure

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
More details in PR: https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/40
=> Bump concourse release version

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/k8s-resources.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/variables.tf
Also refactor the code to use maps
=> Using data resources to lookup hostzones (instead of hardcodding them) 

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf
=> Removed remote state global

tests/e2e/external_dns_test.go, tests/e2e/live-1.yaml, tests/e2e/nginx_ingress_test.go, tests/pkg/helpers/externaldns.go
The idea of the condition is they are not executed always, instead they are only executed when defined in the YAML file.
=> Added conditional to e2e tests

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
Reverts ministryofjustice/cloud-platform-infrastructure#1226
=> Revert "upgrade modsec"

terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
This variable  cannot accept null by default as the type is list(any)
=> Pass default to [""]. 

terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
Mode details in PR: https://github.com/ministryofjustice/cloud-platform-terraform-auth0/pull/12
=> Bump auth0 module version

tests/README.md
Small iteration to the tests readme containing a neat Ginkgo trick I found.
=> Add "Running individual tests" section to the README

terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
Add depends_on for the wait_for_active_associate to create the association, Increase time for wait to 25 mins
=> Add depends_on for the wait_for_active_associate

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Increase max nodes to above desired nodes count for live
=> Increase max nodes to above desired nodes count for live

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf, terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/2945
=> Add kuberos to EKS, Bump kuberos chart version for kops and EKS

tests/config/live.yaml, tests/e2e/fixtures/helloworld-deployment-modsec.yaml.tmpl, tests/e2e/modsec_ingress_test.go, tests/pkg/config/config.go, tests/pkg/config/nginx_ingress_controller.go
Create integration test for EKS - modsec, using the new test structure for Go
=> Mod sec integration tests

tests/e2e/modsec_ingress_test.go
Otherwise, it is the only test that is going to be executed.
=> Remove focus within modsec e2e test

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/resources/calico-global-policies.yaml
for https://github.com/ministryofjustice/cloud-platform/issues/2942
=> block AWS API

makefile
This uses terraform binary 0.14.8
=> Bump tools image to 1.43

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Update sonarqube and concourse module to allow minor upgrades for rds
=> Update sonarqube and concourse module to allow minor upgrades for rds

terraform/aws-accounts/cloud-platform-aws/account/main.tf
Also added Vij to the account's users
=> Importing DynamoDB table used for locking within the environment repo 

terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/main.tf
For manager and live they are within the infra repo, but not for live-1: it is in  https://github.com/ministryofjustice/cloud-platform-concourse/blob/main/pipelines/manager/main/build-environments/main.tf#L26-L56.
The plan is to execute terraform import so no changes in the credentials happen.
=> Migrate concourse serviceAccount creation to infra repo

terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/k8s-resources.tf, terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/main.tf
Last PR they were written within main.tf file, it was a mistake and they should be inside k8s-resources.tf
=> Moved ServiceAccounts to the right file

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
=> Remove metrics endpoint for ingress controller defaultBackend

terraform/aws-accounts/cloud-platform-aws/vpc/kops/variables.tf
Why:
[Persisting the changes](https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/new/persist-add-nodes-to-cluster) - Add nodes to the cluster
=> persist add nodes to cluster

kops/live-1.yaml
Why:
[Persisting the changes](https://runbooks.cloud-platform.service.justice.gov.uk/add-nodes-to-the-cluster.html#3-push-review-merge) - Add nodes to the cluster
=> persist add nodes to cluster to yaml file

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/2962
=> Add System Manager permissions to the worker nodes

kops/live-1.yaml, terraform/aws-accounts/cloud-platform-aws/vpc/kops/main.tf
https://github.com/ministryofjustice/cloud-platform/issues/3156
=> Create new tag for kops monitoring node group

terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
This version includes:
- Increase memory limit for prometheus
- User new node tag for affinity
=> Update prometheus to use the latest version

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
It includes validation of external-dns identifier annotations to follow the regex within the ingress
=> Update OPA with the latest module 

smoke-tests/spec/external_dns_spec.rb, smoke-tests/spec/fixtures/external-dns-ingress.yaml.erb, smoke-tests/spec/fixtures/helloworld-deployment-modsec.yaml.erb, smoke-tests/spec/fixtures/helloworld-deployment.yaml.erb, smoke-tests/spec/fixtures/invalid-nginx-syntax.yaml.erb, smoke-tests/spec/ingress_spec.rb, smoke-tests/spec/kubernetes_helper.rb, smoke-tests/spec/modsec_spec.rb
This is to fix rspec tests failures in live.
=> Update all fixtures to have correct set-identifier

smoke-tests/spec/fixtures/helloworld-deployment-modsec.yaml.erb, smoke-tests/spec/modsec_spec.rb
This is by providing ingress_name to fixtures
=> Fix modsec ingress integration tests

terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
Changes are already in EKS, this is to update to the latest OPA in live-1. It should involve any real changes.
=> Update OPA in live-1 to latest

terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
Similar to [this PR](https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1367) but for live-1
=> Update external-dns to latest in LIVE-1

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Updating the external-dns component to latest
=> Update external-dns to latest

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/107/files
=> Add dashboard link to AlertManager slack template

terraform/aws-accounts/cloud-platform-aws/account/main.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Remove Ale from cloud-platform-eks
=> Alejandro Garrido - Leaver Revoke Access

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
This is for EKS to version "20.0.1"
=> Upgrade promethues to use the latest chart version

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
This is within the module as we have a separate helm release for eks
=> Fix helm_release prometheus dependency

makefile, terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/versions.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/versions.tf
- Maintain different versions for clusters, 
- Upgraded Kubernetes provider version
- Upgrade tools image to use the latest
=> Enable to maintain different cluster version

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/main.tf
Added  load_config_file = false, to fix below error
dial tcp 127.0.0.1:80: connect: connection refused
=> Fix load_config

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to fix concourse OOM issue
This is temp as we are looking into running a job to clear volume and recycle pods.
=> Upgrade concouse to use the latest version

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.8.1
=> Bump concourse module to 1.8.1

terraform/README.md
Trying to fix up this README which is clearly out of date, although I'm not very familiar with this area, so please review carefully...!
=> Fix README

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Maintenance, and also an attempt to get rid of errors mentioned in https://github.com/ministryofjustice/cloud-platform/issues/3493
=> Upgrade Velero

tests/e2e/nginx_ingress_test.go
This is to introduce wait before running the expected check
=> Update ingress test for golang

tests/Dockerfile, tests/makefile
This is to fix awscli, using the similar docker file used in cli image
=> Update docker file for golang test image

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Upgrade manager cluster config to kubernetes 1.21
=> Upgrade manager cluster config to 1.21

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Update EKS version for 1.21 for live and test clusters
=> Update EKS version to 1.21 for live

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Module 1.0.1:
-  Ingress controller v1
- Modsec config
=> Add 2 new ingress controllers using latest module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This version got fix for this:
https://github.com/kubernetes/ingress-nginx/issues/7546
* Condition to enable external-dns annotation for svc
=> Upgrade ingress controller to latest

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
This is to upgrade managed EKS Add-ons for v1.21
=> Upgrade coredns and kube-proxy addon

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, terraform/aws-accounts/cloud-platform-aws/vpc/kops/components/components.tf
This is to remove aws_redirect  as we are using SSO
=> Update kuberos module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Mode details : https://github.com/ministryofjustice/cloud-platform-kuberos/tree/2.1
https://github.com/ministryofjustice/cloud-platform-helm-charts/pull/37
=> Bump kuberos module for ingress api and kuberos image

kops/live-1.yaml
New live-1 yaml with 1 node per region
=> New live-1 yaml with 1 node per region

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Adding user to the cluster to allow connecting to the cluster via aws
=> FEAT: Add new user

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Update the module to remove any references to live-1
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/3665
=> Live-1 clean-up external-dns

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Update the module to remove any references to live-1
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/3668
https://github.com/ministryofjustice/cloud-platform/issues/3667
=> Live-1 clean-up monitoring module

terraform/global-resources/elasticsearch.tf
This is to match with the currently applied config
=> Update es current

destroy-cluster.rb
Remove kops reference in the destroy-cluster script
=> Updated destroy-cluster script

terraform/global-resources/versions.tf
=> Update auth0 provider to auth0/auth0

terraform/aws-accounts/cloud-platform-aws/account/main.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/account/main.tf
Adding Steve.
https://github.com/ministryofjustice/cloud-platform-terraform-awsaccounts-iam/releases/tag/0.0.11
=> Bump awsaccounts-iam to 0.0.11

terraform/aws-accounts/cloud-platform-aws/account/main.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/account/main.tf
=> Bump awsaccounts-iam to 0.0.12

smoke-tests/spec/fixtures/external-dns-ingress.yaml.erb, smoke-tests/spec/fixtures/helloworld-deployment-modsec.yaml.erb, smoke-tests/spec/fixtures/helloworld-deployment.yaml.erb, smoke-tests/spec/fixtures/invalid-nginx-syntax.yaml.erb, test/fixtures/external-dns-ingress.yaml.tmpl, test/fixtures/helloworld-deployment.yaml.tmpl
This is to get the tests run with out any issue over weekend
=> Revert v1 changes for smoke tests

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform/issues/3627
=> Switch kuberos and starter pack to v1 ic

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform/issues/3409
=> upgrade monitoring auth proxies

go.mod, test/certmanager_test.go, test/daemonsets_test.go, test/external_dns_test.go, test/helpers/certificates.go, test/helpers/deploy.go, test/modsec_ingress_test.go, test/namespaces_test.go, test/nginx_default_ingress_ctl_test.go, test/nginx_ingress_test.go, test/nginx_modsec_ingress_ctl_test.go, test/servicemonitors_test.go, test/services_test.go, test/tests_suite_test.go
Overview
---
This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/3821
=> Migrate ginkgo to v2

test/certmanager_test.go
gomega provides an Eventually that checks that an assertion eventually passes. This will be useful here as we're relying on arbitory sleeps. This commit also provides a statement in the test signature that requests it runs 3 times on failure.
=> Improve certificate invocation in test suite

test/starterpack_test.go
- build(starterpack): add condition to skip test if on "manager" cluster
- fix(starterpack): skip test on the live cluster
=> Skip the starterpack test on the live cluster

terraform/aws-accounts/cloud-platform-aws/account/main.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/account/main.tf
Adds policies from https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/releases/tag/1.1.0
=> update SSO module

terraform/aws-accounts/cloud-platform-ephemeral-test/account/outputs.tf
This is in "terraform/aws-accounts/cloud-platform-ephemeral-test/account/outputs.tf"
=> Delete output related to kops butcket

terraform/aws-accounts/cloud-platform-aws/vpc/kops/.terraform.lock.hcl, terraform/aws-accounts/cloud-platform-aws/vpc/kops/main.tf, terraform/aws-accounts/cloud-platform-aws/vpc/kops/variables.tf, terraform/aws-accounts/cloud-platform-aws/vpc/kops/versions.tf
=> Remove unused providers, variables and locals from cloud-platform-aws/vpc/kops

test/platform_test.go
The aftersuite doesn't play nicely with parallelism, and was trying to run the cleanup after each thread. This way the defer runs the cleanup post exitval.
Without this change we introduced a bug that creates errors such as the one here.
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/live-integration-tests/builds/5002
=> Remove aftersuite and add defer to main function

destroy-cluster.rb
This is to exclude smoke test namespaces
=> Update destroy cluster script

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
[1.9.0 pipelines and new IAM privs](https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.9.0) [Latest](https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/latest)
What's Changed
Split the infrastructure pipeline by live/production cluster name by @jasonBirchall in https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/120
Change how infrastructure reports status to GitHub by @jasonBirchall in https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/121
Add context to the pending GitHub status by @jasonBirchall in https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/122
Trigger recycle node job three times per morning by @jasonBirchall in …
=> Concourse updates

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This version has dependency for modsec config map
=> Upgrade ingress-controller to latest

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Will be replaced by an ISM policy in global-settings
=> delete ES curator job

terraform/aws-accounts/cloud-platform-aws/account/main.tf
Schedule Amazon RDS stop and start using AWS Systems Manager
=> RDS auto-start-stop

terraform/global-resources/elasticsearch.tf
permit only read actions and adding data, specifically this excludes `es:ESHttpDelete`
=> allow only adding data in ES logs

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
This is by using service thanos-query-frontend.
=> Create proxy for Thanos

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Fix is to have ingress_controllers module dependency for ingress_controllers_v1, as namespace and default cert is created in the main module.
This dependency will be removed, once ingress_controllers is deleted, when all users switch to v1 IC
https://github.com/ministryofjustice/cloud-platform/issues/4026
=> Update dependency for ingress controller

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
=> update ingress module

terraform/global-resources/elasticsearch.tf, terraform/global-resources/resources/opensearch/ism-policy.json.tpl, terraform/global-resources/resources/opensearch/ism-policy.tpl.json, terraform/global-resources/variables.tf, terraform/global-resources/versions.tf
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/4068
=> Add ism policy

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Release details here: https://github.com/ministryofjustice/cloud-platform-terraform-concourse/tree/1.10.1
=> Split policy as there are chars restrictions of 6144

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/storage.tf
also make it default for PVs unless otherwise specified
=> add GP3 SC

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to fix the issue:
The "count" value depends on resource attributes that cannot be determined until apply
=> Use dependence_prometheus for kuberhealthy

terraform/global-resources/elasticsearch.tf
Why [Create new OS (Open search) cluster for Live-2 Beta#4125](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/4125)
=> adding opensearch to live-2

terraform/global-resources/elasticsearch.tf, terraform/global-resources/variables.tf
This is to have "hot-warm-cold-delete"
=> Add ism for live-2

terraform/global-resources/elasticsearch.tf, terraform/global-resources/resources/opensearch/mapping-template.json.tpl
This is by taking samples from live data.
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/4125
=> Create index template for live-2

terraform/global-resources/elasticsearch.tf
=> Scale down elastic search clusters

terraform/global-resources/elasticsearch.tf
This is to fix ES status turing yellow.
Threshold Crossed: 1 out of the last 1 datapoints
=> Scale up ES audit clusters

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to add additional metrics related to dynamodb
=> Update monitoring module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform/issues/4159
=> Add ssl-ciphers for v1 ingress controllers

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Add descheduler module to components
[
https://github.com/ministryofjustice/cloud-platform-terraform-descheduler
=> Add descheduler module to components

test/certmanager_test.go, test/fixtures/external-dns-ingress.yaml.tmpl, test/helpers/deploy.go
This is to use the latest v1 version.
=> Update Integration tests

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, test/config/config.go
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1934
=> Upgrade monitoring to latest version

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Set labelValue is set to "", as by default it is looking for "1"
=> This is to fix the dashboard not showing up

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
This is for all the 3 addons
https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/pull/13
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/4203
=> Upgrade addon to match with K8's version 1.22

terraform/aws-accounts/cloud-platform-aws/account/main.tf
This PR updates two Terraform modules (output: no-op).
=> Update Terraform modules

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
re:
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4294
=> feat: update OPA module version for domain label length policy changes

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to upgrade metrics servicer to use kubernetes-sigs.github.io
=> Update monitoring for metrics server

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Related to:
https://github.com/ministryofjustice/cloud-platform/issues/3768
=> Create alerts for hoodaw cronjobs

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is for HOODAW reports running in concourse
=> Create alert for crashloop pods

terraform/aws-accounts/cloud-platform-aws/account/main.tf
Removes `kops` and `SteveMarshall`.
=> Bump cloud-platform-terraform-awsaccounts-iam to v0.0.16

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
This will create a new template and new nodes using the template created
=> Apply docker change to manager cluster

terraform/global-resources/outputs.tf, terraform/global-resources/versions.tf, terraform/modules/cluster_dns/versions.tf
https://github.com/ministryofjustice/cloud-platform/issues/3982 https://github.com/ministryofjustice/cloud-platform/issues/3981
=> Upgrade terraform version in global and modules

terraform/aws-accounts/cloud-platform-aws/account/main.tf, terraform/aws-accounts/cloud-platform-aws/account/versions.tf, terraform/aws-accounts/cloud-platform-dsd/versions.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/account/versions.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/versions.tf, terraform/global-resources/auth0.tf, terraform/global-resources/versions.tf, terraform/modules/cluster_dns/versions.tf
Add user JaskaranSarkaria in cloud-platform-terraform-awsaccounts-iam
=> Upgrade to terraform 1.2.5

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
revert cpu and memory requests to default for live clusters
=> update trivy-operator module version

README.md
We use the infrastructure spin-off Dockerfile for GinkGo tests.
=> Change the Dockerfile location

makefile
=> Upgrade tools to 2.3.0

terraform/aws-accounts/cloud-platform-aws/account/main.tf
update iam module to latest release for tom smith addition
=> add tom smith admin user

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
This PR brings EKS level module releases up to terraform 1.2.5 versions
=> update to latest  module releases for tf 1.2.5

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/storage.tf
This PR brings components level module releases up to terraform 1.2.5 versions
=> update components to latest module releases for tf 1.2.5

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/networking.tf
This is for tigera calico module
=> Use version 1.29.1 from calico operator

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This PR covers issue:
Fix descheduler module version #4427
=> update descheduler release

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is move logs to modsec.config
=> Update ingress controller

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
This is to fix the PrometheusOperatorReconcileErrors in concourse namespace
=> Update prometheus alert for cronjob

terraform/global-resources/elasticsearch.tf, terraform/global-resources/variables.tf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4439
=> Add Opensearch for live - modsec logs

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
increase memory requests/limits for live cluster from 100/500 to 500/1000
=> bump trivy operator version

terraform/aws-accounts/cloud-platform-aws/account/.terraform.lock.hcl, terraform/aws-accounts/cloud-platform-aws/account/main.tf, terraform/aws-accounts/cloud-platform-aws/account/opensearch.tf, terraform/aws-accounts/cloud-platform-aws/account/resources/auth0-rules/add-github-teams-to-opensearch-saml.js, terraform/aws-accounts/cloud-platform-aws/account/resources/opensearch/ism-policy.json.tpl, terraform/aws-accounts/cloud-platform-aws/account/variables.tf, terraform/aws-accounts/cloud-platform-aws/account/versions.tf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4439
=> feat: 🎸 add saml based opensearch cluster for modsec logs

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Closes: https://github.com/ministryofjustice/cloud-platform/issues/4448
=> Bump concourse to 1.12.0

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- bump the ingress module to push logs to new opensearch
- bump logging module to pass modsec logs to separate index
=> chore: 🤖 push modsec logs to stdout -> opensearch

terraform/aws-accounts/cloud-platform-aws/account/opensearch.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/account/.terraform.lock.hcl, terraform/aws-accounts/cloud-platform-ephemeral-test/account/opensearch.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/account/versions.tf
tested in ephemeral, see https://et-logs.et.cloud-platform.service.justice.gov.uk/_dashboards
=> feat: 🎸 add vanity url for opensearch cluster

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- Bump ingress controller to 1.2.3, revert audit logs stdout
=> Bump ingress controller to 1.2.3

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
=> feat(TF): Update test cluster node group instance type

terraform/global-resources/elasticsearch.tf
To go in after #2231 (removes fluent-bit integration) but before #2232 (OAuth proxy) so we don't inadvertently expose ES to the internet.
This terminates the `cloud-platform-audit-live` domain as the logs (audit and otherwise) are stored in CloudWatch.
The latest indice in this domain is:
```
kubeapi_audit-2022.04.07
```
=> Remove deprecated cloud-platform-audit-live ElasticSearch domain

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Reduce min node count to 2 for live-2 until we start hosting user applications
=> Reduce min node count to 2 for live-2

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
scan image from filesystem, not registry pull
=> bump trivy-operator release

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
ignore daemonset utilisation in scaling calculation
=> bump autoscaler module version

terraform/aws-accounts/cloud-platform-aws/account/main.tf
=> bump awsaccounts-iam module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
=> Descheduler 0.3.0 release

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- turns off the opa rule for service type
- turns on the gatekeeper constraint for service type
=> feat: 🎸 turn gatekeeper service type constraint on

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Turn on modsec snippet class constraint
=> feat: 🎸 turn on gatekeeper modsec snippet constraint

terraform/aws-accounts/cloud-platform-ephemeral-test/account/.terraform.lock.hcl, terraform/aws-accounts/cloud-platform-ephemeral-test/account/elasticsearch.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/account/main.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/account/secrets.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/account/variables.tf
- Add missing circleCI secrets
- Add test elasticsearch to replicate live elasticsearch in et account
=> Add test Elasticsearch to Ephemeral account

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
=> bump eks-addons module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
The min node count and desired node count has been increase to temporarily accomodate the "ContainerCreating" issue. Now the issue is fixed, update the count to how it was before
=> Update node count to pre incident state

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Upgrade gatekeeper to 1.4.0 module and include warn_service_account_secret_delete dryrun value
=> Upgrade gatekeeper to 1.4.0

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.9.3
=> chore: 🤖 bump logging version

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.9.4
=> chore: 🤖 bump logging module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/releases/tag/1.5.3
=> chore: 🤖 bump gatekeeper again to rework deploy order

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/releases/tag/1.5.4
=> chore: 🤖 bump gatekeeper delay

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.9.9
=> chore: 🤖 bump logging -- lower chunks in mem

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.9.11
=> chore: 🤖 bump logging tweak alert

README.md, go.mod, go.sum, test/docker/curl-jq.Dockerfile, test/fixtures/helloworld-job.yaml.tmpl, test/fixtures/logging-job.yaml.tmpl, test/logging_test.go, test/modsec_logging_test.go
default logging and modsec
- check that we have a 100 log entries in elastic search
- check that we have 100 log entries for modsec logs in opensearch
=> test: 💍 add testing to check to see if logs are being dropped for

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.4.0
=> chore: 🤖 bump ingress controllers

test/modsec_logging_test.go
Check elastic search for the correct number of modsec audit logs
=> test: 💍 for dropped modesc audit logs

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.4.1
=> chore: 🤖 bump ingress controller to add logrotate to modsec

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.9.14
=> chore: 🤖 increase fluent-bit alert limit and regex -> alphanum

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
=> Update Velero to v1.11

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/releases/tag/1.7.0
=> chore: 🤖 bump gatekeeper to include psa label constraint

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Ticket:
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4873
=> bump autoscaler to 1.24.3

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Ticket:
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4873
=> bump autoscaler for overprovision upgrade

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/gh/ministryofjustice/cloud-platform/4875
=> bump descheduler

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
- Bump monitoring node to r6i.8xlarge
- Bump monitoring module for increase prometheus limits
=> Bump monitoring node and prometheus limits

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/2.10.4
=> chore: 🤖 bump monitoring

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/releases/tag/1.11.5
=> chore: 🤖 bump external dns

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/releases/tag/1.8.0
=> chore: 🤖 bump gatekeeper to inc init and eph container mutation

terraform/aws-accounts/cloud-platform-aws/vpc/eks/psp.tf
prep to remove custom psp by shifting all to a 0-super-privivleged
=> feat: 🎸 create 0-super-privileged rolebinding

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Closes ministryofjustice/cloud-platform#4966
=> bump trivy helm release

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
in prep for https://github.com/ministryofjustice/cloud-platform-environments/pull/18005/
=> chore: 🤖 bump gatekeeper module

terraform/aws-accounts/cloud-platform-aws/account/main.tf
https://github.com/ministryofjustice/cloud-platform-terraform-awsaccounts-iam/releases/tag/0.0.28
=> Bump awsaccount-iam to 0.0.28

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- create new node groups with new root volume size and type upgrade
=> chore: 🤖 create new node group for volume upgrade

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- In preparation to migrating to the new ng
=> chore: 🤖 raise default ng node count

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/releases/tag/1.9.5
=> chore: 🤖 bump gatekeeper

test/certmanager_test.go, test/fixtures/namespace.yaml.tmpl, test/helpers/deploy.go, test/psa_priv_init_test.go, test/psa_priv_test.go, test/psa_restricted_eph_test.go, test/psa_restricted_init_test.go, test/psa_restricted_test.go, test/psa_serviceaccount_test.go
Related to: https://github.com/ministryofjustice/cloud-platform/issues/4942
=> Remove bypassPspRoleName references and rolebinding from tests

terraform/aws-accounts/cloud-platform-aws/account/main.tf
https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/releases/tag/1.5.1
=> Bump aws-sso module to 1.5.1

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/variables.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.9.20
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.6.0
=> chore: 🤖 bump ingress and logging

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.6.3
=> chore: 🤖 bump nginx-ingress

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.10.0
=> chore: 🤖 bump logging

terraform/aws-accounts/cloud-platform-aws/account/main.tf
https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/compare/1.5.1...1.5.2
=> Bump AWS SSO to 1.5.2

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/releases/tag/1.10.2
=> chore: 🤖 bump gatekeeper -- add deny kubectl create sa

terraform/global-resources/kibana-alerts.tf
I expect to tweak these alerts in follow up PRs as they are triggered
=> chore: 🤖 add external dns kibana alerts

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf, terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/cluster.tf
=> Remove Jake

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/cluster.tf
https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/releases/tag/1.17.0
=> chore: 🤖 bump coredns addon

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/releases/tag/1.17.1
=> Bump addon module to 1.17.1

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/releases/tag/1.17.2
=> chore: 🤖 bump vpc-cni add on

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/releases/tag/1.17.4
=> chore: 🤖 bump vpc cni addon version

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/2.10.21
the plan is large so here's a screenshot
=> chore: 🤖 bump monitoring (kube-state-metrics)

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-cluster-autoscaler/releases/tag/1.7.0
=> Upgrade cluster autoscaler to 1.7.0

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.12.0
=> chore: 🤖 logging (input eventrouter tail -> kubernetes_events)

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.12.3
=> chore: 🤖 bump logging remove unused helm eventrouter

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.7.1
=> chore: 🤖 bump ingress limits

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.7.4
=> chore: 🤖 bump nginx ingress

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
closes: #[5328](https://github.com/ministryofjustice/cloud-platform/issues/5328)
=> Reduce ic on non live

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
related to ministryofjustice/cloud-platform#5343
=> bump kube-proxy to v1.26.13-eksbuild.2

test/psa_restricted_test.go, test/psa_serviceaccount_test.go
relates to ministryofjustice/cloud-platform#5366
=> update string checks for psa violations

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
bump vpc-cni to v1.16.4-eksbuild.2
=> related to ministryofjustice/cloud-platform#5342

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
=> switch certman module to alekc kubectl provider

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
=> switch ingress modules to alekc kubectl provider

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
=> switch to alekc kubectl provider

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
=> switch concourse module to alekc kubectl provider

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.2
=> feat: 🎸 turn on proxy response buffering for prod-only ingr

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.3
=> perf: ⚡️ pass proxy-response-buffering to prod-only ingress

terraform/aws-accounts/cloud-platform-aws/vpc/eks/components/components.tf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/5372
=> Bump gatekeeper for 1.11.1

test/gatekeeper_mutations_test.go, test/psa_priv_test.go, test/psa_restricted_test.go
Related to: https://github.com/ministryofjustice/cloud-platform/issues/5373
=> Remove seccomp annotation tests and fix error message

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Relates to ministryofjustice/cloud-platform#5347
Relates to ministryofjustice/cloud-platform#4856
=> update manager to kubernetes 1.27

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Relates to ministryofjustice/cloud-platform#4849
Relates to ministryofjustice/cloud-platform#5347
=> update live to kubernetes 1.27

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.4
=> chore: 🤖 bump ingress and configure keepalive time

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Relates to ministryofjustice/cloud-platform#5348
=> bump eks add on module to update vpc-cni to v1.17.1-eksbuild.1

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Relates to ministryofjustice/cloud-platform#5349
=> bump eks add on module to update kube-proxy to v1.27.10-eksbuild.2

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Relates to ministryofjustice/cloud-platform#5350
=> bump eks add on module to update coredns to v1.10.1-eksbuild.7

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.6.0
=> chore: 🤖 upgrade thanos

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.6.1
=> chore: 🤖 bump monitoring, unpin kube-state-metrics

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-descheduler/releases/tag/0.7.0
=> chore: 🤖 bump descheduler

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
relates to ministryofjustice/cloud-platform#5398
=> bump kuberhealthy

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/storage.tf
relates to ministryofjustice/cloud-platform#4877
=> remove redundant efs csi driver module

terraform/aws-accounts/cloud-platform-aws/account/main.tf
https://github.com/ministryofjustice/cloud-platform-terraform-awsaccounts-iam/releases/tag/0.0.31
=> Bump awsaccounts-iam to 0.0.31

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch-alerts-cp.tf
Disable live Openserach monitoring for now and enable it after migration.
=> Disable live Openserach monitoring for now and enable it after migration

scripts/generate_cluster_vuln_report.sh, scripts/update_obj.sh
- move report scripts here
- refactor out bash loop to increase performance
=> feat: 🎸 add security team report scripts

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.24.0
=> chore: 🤖 bump concourse

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.15.0
=> chore: 🤖 bump logging to reformat github_teams field

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
relates to ministryofjustice/cloud-platform#5449
=> bump ingresses and modsec fluentbit version

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/storage.tf
relates to https://github.com/ministryofjustice/cloud-platform/issues/5455
=> bump eks-csi module to latest release

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
Related to: https://github.com/ministryofjustice/cloud-platform/issues/5529
=> Set prometheus default request to accomodate the spike during startup

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.17.1
=> fix: 🐛 tweak lua bool logic

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
=> chore: 🤖 move to new ecr

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/releases/tag/1.18.4
=> chore: 🤖 upgrade vpc-cni addon

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch-alerts-cp.tf
- Enable OpenSearch Alert
- Update alert severity (1 is highest in OpenSearch)
- Update alert message to:
- perform query in app logs OpenSearch
- redirect to OpenSearch alert page
Relates to ministryofjustice/cloud-platform#5515
=> chore: Enable OpenSearch alert and update alert contents to fit OpenSearch

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Updated the module reference to version 1.18.5
=> updated eks add-on module from 1.18.4 to 1.18.5

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.25.2
=> chore: 🤖 bump concourse for increase worker limit

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.7.12
=> chore: 🤖 bump thanos resource compactor

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-kuberos/releases/tag/0.6.0
https://github.com/ministryofjustice/cloud-platform-kuberos/releases/tag/2.7.0
=> Bump kuberos module to 0.6.0

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.8.5
=> chore: 🤖 bump monitoring (thanos compactor)

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
relates to ministryofjustice/cloud-platform#5577
[release](https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/releases/tag/1.18.6)
=> chore: 🤖 bump eks-addons for vpc-cni update

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Addon Pull Request: https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/pull/61
Addons Release: https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/releases/tag/1.18.7
=> feat(EKS): update addons

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.9.3
=> chore: 🤖 bump thanos

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
https://mojdt.slack.com/archives/C8QR5FQRX/p1719817977347219
=> perf: ⚡️ bump storage for data nodes

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/infrastructure-account/jobs/terraform-apply/builds/66
=> fix: 🐛 throughput limit

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.10.1
=> chore: 🤖 bump thanos compact

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.11.0
=> chore: 🤖 remove cw exporter add yace

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/prometheus-crds.tf
relates to ministryofjustice/cloud-platform#5581
=> chore: 🤖 bump prometheus CRDs for post k8s 1.28 upgrade

terraform/aws-accounts/cloud-platform-aws/account/main.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/account/main.tf
relates to ministryofjustice/cloud-platform#5784
[release notes](https://github.com/ministryofjustice/cloud-platform-terraform-awsaccounts-iam/releases/tag/0.0.33)
=> chore: 🤖 bump iam accounts for user removal

terraform/aws-accounts/cloud-platform-aws/vpc/main.tf, terraform/aws-accounts/cloud-platform-aws/vpc/outputs.tf
relates to ministryofjustice/cloud-platform#5610
=> feat: 🎸 add route53 query log module to vpc

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
release notes https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.25.3
=> chore: 🤖 bump concourse for iam permissions update

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.25.4
=> chore: 🤖 bump concourse iam permissions

terraform/aws-accounts/cloud-platform-aws/account/sqs.tf
relates to ministryofjustice/cloud-platform#5610
=> feat: 🎸 add sqs and iam resources for route53 logging to XSIAM

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- **feat(TF): Ingress module upgrade for custom-error-pages**
- **feat(TF): Update ingress controller module to use new custom error pages**
=> ingress module update

terraform/aws-accounts/cloud-platform-aws/account/main.tf
relates to ministryofjustice/cloud-platform#5727
=> feat: 🎸 add r53 readonly iam role for ops-eng access

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/pull/99
=> feat(TF): Update ingress module for latest custom error pages fix

makefile
=> chore: bump image in makefile

terraform/global-resources/elasticsearch.tf
=> fix: 🐛 volume limit

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.13.1
=> chore: 🤖 bump monitoring to add compactor alerts

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.25.8
=> chore: 🤖 bump concourse for worker anti-affinity

test/config/config.go, test/monitoring_test.go
fixes failing manager monitoring int test
=> extend expected promrule testing for new manager resources

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://mojdt.slack.com/archives/C8QR5FQRX/p1723040662183909
=> perf: ⚡️ bump to attempt to fix node major page faults

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.17.5
=> chore: 🤖 re-intro opensearch logging cluster

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/1.13.2
=> chore: 🤖 bump monitoring for thanos compactor

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.13.3
=> chore: 🤖 bump thanos query resources & timeout

terraform/aws-accounts/cloud-platform-aws/vpc/subnet-tags.tf, terraform/aws-accounts/cloud-platform-aws/vpc/transit-gateway/vpc-attachment.tf
Relates to [EKS in-place subnet modification](https://github.com/ministryofjustice/cloud-platform/issues/6030)
=> adding new EKS-Private subnets to tgw attachments

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/calico.tf
relates to ministryofjustice/cloud-platform#5698
=> bump tigera module

Dangerfile
Removed Dangerfile from cloud-platform-infrastructure Repo after checking there are no references
=> remove file Dangerfile from repo

terraform/aws-accounts/cloud-platform-aws/vpc/eks/.terraform.lock.hcl, terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/versions.tf
https://github.com/ministryofjustice/cloud-platform-terraform-auth0/releases/tag/2.0.1
=> fix: 🐛 auth0 default var value has changed

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
**Release notes**
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.13.6
relates to ministryofjustice/cloud-platform#5994
=> chore: 🤖 bump monitoring for KIAM annotation removal

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
**Release notes**
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.17.6
relates to ministryofjustice/cloud-platform#5994
=> chore: 🤖 bump logging for KIAM annotation removal

terraform/aws-accounts/cloud-platform-aws/account/main.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/account/main.tf
relates to ministryofjustice/cloud-platform#6284
=> chore: 🤖 bump awsaccounts-iam module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
relates to ministryofjustice/cloud-platform#6203
=> chore: 🤖 bump external-dns

terraform/aws-accounts/cloud-platform-aws/account/main.tf
[Release notes](https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/releases/tag/1.5.7)
relates to ministryofjustice/cloud-platform#6142
=> chore: 🤖 bump sso module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-kuberhealthy/releases/tag/1.5.1
=> chore: 🤖 bump-kuberhealthy for debug logs

terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf, terraform/aws-accounts/cloud-platform-aws/account/resources/auth0-actions/add-github-teams-to-opensearch-saml.js
We need to move all of our rules over to actions before November 18 when rules are removed
=> chore: 🤖 move opensearch saml over to auth0 action

terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf, terraform/aws-accounts/cloud-platform-aws/account/resources/auth0-actions/add-github-teams-to-opensearch-saml.js, terraform/global-resources/auth0.tf
- we can pull the github teams from a previous action and save on gh API calls
=> feat: 🎸 migrate auth0 opensearch saml rule to action

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch-index-templates.tf
- add shard size for new ipamd indices
- correct typos on index patterns
=> feat: 🎸 add shard size for new ipamd indices

terraform/aws-accounts/cloud-platform-aws/account/.terraform.lock.hcl, terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf, terraform/aws-accounts/cloud-platform-aws/account/main.tf, terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf, terraform/global-resources/.terraform.lock.hcl, terraform/global-resources/auth0.tf, terraform/global-resources/versions.tf
- move gh org rule into global-resources module and convert to action
- move the aws saml rule to the sso module and convert to action
- remove stale action definitions
=> chore: 🤖 move last 2 auth0 rules to actions

terraform/global-resources/auth0.tf
https://github.com/ministryofjustice/cloud-platform-terraform-global-resources-auth0/releases/tag/2.1.6
=> chore: 🤖 bump global auth0

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.26.4
=> chore: 🤖 bump concourse placement strategy

.github/dependabot.yml
remove obsolete folder checks, ignore major release for eks module
=> chore: 🤖 update dependabot config

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.14.1
relates to https://github.com/ministryofjustice/cloud-platform/issues/5121
=> chore: 🤖 remove kibana proxy and url

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
relates to https://github.com/ministryofjustice/cloud-platform/issues/5121
=> feat: 🎸 add redirect from elastic search to opensearch

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- fix opensearch ui permissions issue
=> fix: 🐛 fix ui permissions issue

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-label-pods/releases/tag/1.1.3
=> Update user roles

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
redirect is defined https://github.com/ministryofjustice/cloud-platform-environments/pull/27268
=> chore: 🤖 remove unused cname

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- lower task limit to prep increasing apply pipeline concurrency
=> perf: ⚡️ prep for increasing concurrency for apply live

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.26.6
=> chore: 🤖 bump concourse resources

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
relates to ministryofjustice/cloud-platform#6366
[Release}(https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.11)
=> chore: 🤖 bump modsec ingress module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[Release](https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.11)
elates to ministryofjustice/cloud-platform#6366
=> chore: 🤖 bump prod-only ingress controller module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.12
=> chore: 🤖 bump ingresses

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/.terraform.lock.hcl, terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/cert_manager.tf
NO-OPS!
also updating terraform lock hcl
=> chore: 🤖 bump certmanager for template provider removal

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/gatekeeper.tf
relates to https://github.com/ministryofjustice/cloud-platform/issues/6045
[Release](https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/releases/tag/1.12.3)
=> chore: 🤖 bump gatekeeper for kuberhealthy ns mutate exclusion

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
updating deployment check replicaset to 2
[Release](https://github.com/ministryofjustice/cloud-platform-terraform-kuberhealthy/releases/tag/1.5.2)
=> chore: 🤖 bump kuberhealthy module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/.terraform.lock.hcl, terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/.terraform.lock.hcl
- **feat(K8): 1.29 upgrade branch**
- **feat(TF): live-2/manager upgrade**
- **feat(tf): update live cluster version**
=> 1.29 upgrade

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.14.3
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.14.3
=> chore: 🤖 bump monitoring and logging

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[Release
notes](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.14.5)
=> chore: 🤖 bump monitoring module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
"v1.28.8-eksbuild.5" -> "v1.29.10-eksbuild.3"
https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html
=> chore: 🤖 bump kube-proxy

scripts/generate_cluster_vuln_report.sh
- fix block bug
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/vulnerability-report/jobs/live/builds/30
=> fix: 🐛 failing concourse job

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.14
=> chore: 🤖 add debug modsec logging

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.15
=> fix: 🐛 debug volume

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.16
=> chore: 🤖 bump ingress for debug logs

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[Release: 0.9.0](https://github.com/ministryofjustice/cloud-platform-terraform-descheduler/releases/tag/0.9.0)
=> feat(bump): deschedular upgrade

terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.19
=> chore: 🤖 bump ingress controllers (for modsec)

terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.20
=> style: 💄 modsec debug log level

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.16.4
=> chore: 🤖 bump thanos vol to max

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/cert_manager.tf
[Release
notes](https://github.com/ministryofjustice/cloud-platform-terraform-certmanager/releases/tag/1.13.0)
relates to ministryofjustice/cloud-platform#6367
=> chore: 🤖 bump certman for HA in prod

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[Release](https://github.com/ministryofjustice/cloud-platform-terraform-trivy-operator/releases/tag/0.9.0)
=> chore: 🤖 bump trivy module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-label-pods/releases/tag/1.1.4
=> chore: 🤖 bump label-pods controller

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
https://docs.aws.amazon.com/ebs/latest/userguide/general-purpose.html#gp3-ebs-volume-type
=> perf: ⚡️ increase throughput

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
LimitExceededException: Throughput must be set to 593
=> fix: 🐛 throughput

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[Release](https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.28.0)
=> chore: 🤖 bump concourse for additional IAM permissions

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
=> chore: 🤖 bump concourse for iam permissions

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[Release](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.17.0)
=> chore: 🤖 bump monitoring for subnet-exporter

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/v3.17.1
=> chore: 🤖 bump compactory memory limit

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.17.2
=> chore: 🤖 bump compactor

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
=> chore: 🤖 remove modsec response body inspection

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.17.5
=> chore: 🤖 bump

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
Change velero release to 2.4.0
=> change velero release from 2.3.0 to 2.4.0

go.mod, test/os_logging_test.go
relates to ministryofjustice/cloud-platform#6456
=> test: 💍 update es standard logging test for opensearch

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
Thanos is on an instance one size too small bump it
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.17.12
=> Resize thanos node

go.mod
fix failing int tests post dependabot merge
=> chore: 🤖 update go.mod for version bumps

terraform/global-resources/elasticsearch.tf
firstly downsize the live es
In a follow up PR I will start removing the live 2 es
=> chore: 🤖 downsize legacy elasticsearch

terraform/global-resources/elasticsearch.tf
- there are warm indexes stuck so we can't get rid of them yet
- reduce the size as much as possible of the nodes and in another pr have another pass at reducing the number of warm nodes
=> fix: 🐛 keep warm but prep to reduce

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
[Release notes](https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/releases/tag/1.18.9)
=> chore: 🤖 bump eks-addons module for iam submodule update

terraform/global-resources/elasticsearch.tf
- remove warm instances
- revert size for remaining instance
=> Remove warm

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[Release
notes](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.17.13)
=> chore: 🤖 bump monitoring module for iam module updates

terraform/aws-accounts/cloud-platform-aws/account/.terraform.lock.hcl, terraform/aws-accounts/cloud-platform-aws/account/versions.tf
prep for updating s3 bucket modules to compatible aws version
=> chore: 🤖 bump terraform aws provider at account level

terraform/aws-accounts/cloud-platform-aws/account/ecr.tf
[Follow-up ticket
here](https://github.com/ministryofjustice/cloud-platform/issues/6646)
=> chore: 🤖 bump ECR module calls at account level to latest ver

terraform/global-resources/elasticsearch.tf
- increase number of shards that will decrease shard sizes
=> fix: 🐛 decrease shard sizes

terraform/global-resources/elasticsearch.tf
- duplicate index template name
=> fix: 🐛 shard policy name

terraform/aws-accounts/cloud-platform-aws/account/main.tf
=> chore: 🤖 bump account kubeconfig s3 bucket module ver

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.22
=> chore: 🤖 bump ingress controller

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf, terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf
account level dependabot issues work
=> chore: 🤖 bump acm module versions across account level

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.8.23
=> feat: 🎸 only implement anti-affinity on live ing controllers

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-kuberos/releases/tag/0.6.1
=> chore: 🤖 bump kuberos replicas

terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
[release](https://github.com/ministryofjustice/cloud-platform-terraform-auth0/releases/tag/2.1.0)
relates to ministryofjustice/cloud-platform#6682
=> chore: 🤖 bump EKS auth0 module to latest

.gitignore
=> chore: 🤖 ignore .env

terraform/aws-accounts/cloud-platform-aws/account/main.tf
[release](https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/releases/tag/1.6.0)
=> chore: 🤖 bump readonly sso module

terraform/aws-accounts/cloud-platform-aws/account/main.tf
[release](https://github.com/ministryofjustice/cloud-platform-terraform-awsaccounts-iam/releases/tag/0.1.0)
=> chore: 🤖 bump iam module for emma iam user

terraform/global-resources/elasticsearch.tf
- I have opened a case with aws about indexes moving over to warm
- they suggest that we add more data nodes to help with reindexing
=> perf: ⚡️ aws recommend that we increase data nodes to help with index transfers

terraform/global-resources/elasticsearch.tf
=> fix: 🐛 hitting InsufficientInstanceCapacity errors for new node

terraform/aws-accounts/cloud-platform-aws/account/ecr.tf
relates to ministryofjustice/cloud-platform#6368
=> feat: 🎸 add ecr for github-teams-filter service

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/6782
=> chore: bump trivy operator

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[Release notes](https://github.com/ministryofjustice/cloud-platform-github-teams-filter/releases/tag/1.0.0)
relates to ministryofjustice/cloud-platform#6368
=> feat: 🎸 add github teams filter service to components

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[release](https://github.com/ministryofjustice/cloud-platform-github-teams-filter/releases/tag/1.1.1)
=> chore: 🤖 bump filter-teams module

terraform/aws-accounts/cloud-platform-aws/account/main.tf, terraform/aws-accounts/cloud-platform-aws/account/outputs.tf
relates to ministryofjustice/cloud-platform#6461
=> feat: 🎸 add s3 bucket config for apply-live namespace reports

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[release](https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.29.0)
relates to ministryofjustice/cloud-platform#6461
=> chore: 🤖 bump concourse module

terraform/aws-accounts/cloud-platform-aws/account/outputs.tf
relates to ministryofjustice/cloud-platform#6461
=> chore: 🤖 update env-reports bucket output to use bucket name

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/main.tf
=> feat: 🎸 add addtional test ext-dns zone to clusters

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf, terraform/aws-accounts/cloud-platform-aws/account/variables.tf
- `organisation-security-audit` give access to our cluster
- correct move to warm storage down from 14d to 7d
=> chore: 🤖 give os perms to org-sec-audit

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[release](https://github.com/ministryofjustice/cloud-platform-terraform-kuberos/releases/tag/0.6.2)
=> chore: 🤖 bump kuberos module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[release](https://github.com/ministryofjustice/cloud-platform-terraform-starter-pack/releases/tag/0.2.6)
=> chore: 🤖 bump starter-pack module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/gatekeeper.tf
=> chore: 🤖 temp freeze of ingresses via gatekeeper

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/gatekeeper.tf
relates to ministryofjustice/cloud-platform#6572
=> chore: 🤖 unfreeze gatekeeper ingress

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- fix constant upsert by removing the hostname on prod only
- reduce replica count for prod only
=> fix: 🐛 constant upsert issue

test/external_dns_test.go
=> refactor: 💡 test log

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
=> fix: 🐛 revert

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- add more data nodes to cope with increase resource usage on cluster
=> perf: ⚡️ bump instance sizes

test/github_team_filter_test.go
This pr is add an integration test for the github team filter api
=> feat:github team filter api test

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Updating the cluster versions in Terraform to match the current version of the cluster.
=> Update cluser versions to match console

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Upgrading kube-proxy to latest version post upgrade - [#6710](https://github.com/ministryofjustice/cloud-platform/issues/6710)
=> Update kube-proxy to 1.30.9 to match cluster version

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
Upgrade core-dns-addon to v1.11.4-eksbuild.2 as per issue https://github.com/ministryofjustice/cloud-platform/issues/6711
=> upgrade core-dns-addon to v1.11.4-eksbuild.2

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
- remove old monitoring node group after draining the old one
=> chore: remove old monitoring node group

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
=> chore: 🤖 retrigger unstale plan

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
=> chore: 🤖 bump nginx to 1.12.1

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- bump ingress controllers again (not modsec yet)
=> chore: 🤖 bump default & add dev only modsec

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.10.2
=> Bump nginx version 12.1 3

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/main.tf
this PR assigns a specific single subnet for thanos nodegroup to deploy into to counter issues with node group recycles and compactor PV AZ issues
=> feat: 🎸 constrain thanos compactor nodegroup to single az

terraform/global-resources/elasticsearch.tf
- match tf to the changes made in the console
=> chore: 🤖 downscale es

terraform/global-resources/elasticsearch.tf
=> fix: 🐛 ebs size

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.18.5
=> chore: 🤖 bump logging with flb tweak

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/gatekeeper.tf
[release](https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/releases/tag/1.15.0)
=> chore: 🤖 bump kuberhealthy

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.10.4
=> chore: 🤖 bump controller to fix configmap to correct controller

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/3876
=> chore: 🤖 add sso admin to cluster

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch-alerts-cp.tf
relates to ministryofjustice/cloud-platform#7038
=> feat: 🎸 add opensearch monitor alert for acme-challenge clash

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/compare/1.9.0...1.10.4
https://mojdt.slack.com/archives/CH6D099DF/p1743679136065029
=> chore: 🤖 upgrade modsec controller

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/3887
=> chore: 🤖 stale plan

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch-alerts-cp.tf
- Update acme challenge alert monitor query
- Relates to https://github.com/ministryofjustice/cloud-platform/issues/7038
=> fix: Update acme challenge alert monitor query

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/eks-csi.tf
Bumping eks csi module to latest module version.
Issue relating to PR: [#6718](https://github.com/ministryofjustice/cloud-platform/issues/6718)
=> Updating eks csi driver to 1.41.0 post 1.30 kube upgrade

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-label-pods/releases/tag/1.2.0
=> chore: 🤖 bump label-pods container

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/main.tf
non-destructive PR to see about importing the current state of webhook variable into a secure SSM param.
=> chore: 🤖 importing the slack receivers into an ssm json block

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.21.0
=> chore: 🤖 tweak alerts

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- bump controller to update nginx log format
- relates to https://github.com/ministryofjustice/cloud-platform/issues/7111
- https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.10.5
=> chore: bump controller to update nginx log format

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
This allows us to curl the opensearch API via sso
=> chore: 🤖 add sso role to opensearch

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- users couldn't download reports from the ingress index https://mojdt.slack.com/archives/C57UPMZLY/p1746089805310609
=> chore: 🤖 allow users to download reports from all indices

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- added perms to the wrong role
=> fix: 🐛 perms to correct role

terraform/aws-accounts/cloud-platform-aws/account/main.tf
[release](https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/releases/tag/1.8.0)
relates to ministryofjustice/cloud-platform#7161
=> chore: 🤖 bump sso module for dynamodb console access

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
- debug flb logging timestamp issue
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.20.1
=> chore: 🤖 debug flb containers

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
Push modsec ingress access logs to app logs opensearch from nginx flb
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.11.0
=> chore: 🤖 bump non prod modsec ingress

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.11.0
=> chore: 🤖 bump modsec prod

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
=> fix: 🐛 pass opensearch url

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.21.0
=> Bump prod modsec

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
=> fix: 🐛 revert logging for modsec prod

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.11.7
=> chore: 🤖 bump ingress

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.21.2
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.11.7
=> chore: 🤖 bump prod modsec and loggging

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.12.1
=> fix: 🐛 flb input tag

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/3989
=> chore: 🤖 rollout flb modsec fix

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.12.1
=> chore: 🤖 no-op keep all ingress versions in sync

test/helpers/search.go, test/modsec_logging_test.go
- add modsec ingress int test
- be more specific with modsec error logs
=> test: 💍 add modsec int tests

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.13.0
=> chore: 🤖 bump modsec ingress controllers

terraform/aws-accounts/cloud-platform-aws/inspection/vpc.tf
This PR does the following:
* Introduces local values to name subnet resources (eg. route tables) appropriately
* Updates the filtering used to pick route tables for the data call `intra`
=> Amend route table naming and filter syntax

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
[release
notes](https://github.com/ministryofjustice/cloud-platform-terraform-concourse/releases/tag/1.31.0)
=> chore: 🤖 bump concourse release

terraform/aws-accounts/cloud-platform-aws/inspection/vpc.tf
This PR adds a simple data source and route table entry to route traffic from private subnets via cloud platform transit gateway.
=> Add route via transit gateway to inspection VPC

terraform/aws-accounts/cloud-platform-aws/account/main.tf
[release](https://github.com/ministryofjustice/cloud-platform-terraform-awsaccounts-iam/releases/tag/0.2.0)
=> chore: 🤖 bump awsaccount iam module

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/gatekeeper.tf
- Bumps gatekeepers memory limits/request 8Gi/4Gi
=> chore: bump gatekeeper mem limit/req 8/4Gi

cloudformation/aws-limit-monitor/limit-monitor.template
Add mandatory tags to dynamo table as a part of [#6981](https://github.com/ministryofjustice/cloud-platform/issues/6981)
=> Adding mandatory tags to Serverless-Limit-Monitor dynamodb table

scripts/opensearch/stuck-indices/warm/get_all_cold_and_warm_indices.sh, terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.14.2
=> chore: 🤖 bump nginx modsec emit buf limit

scripts/opensearch/stuck-indices/hot/fix.sh
- bump batch size
- reindex only indices that have shards that are too large
=> Hotfix ensure correct index reindexed

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.14.3
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.25.1
=> chore: 🤖 bump monitoring and modsec

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.14.5
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.25.3
https://github.com/ministryofjustice/cloud-platform-terraform-logging/releases/tag/1.26.0
=> chore: 🤖 bump monitoring, logging and modsec ingress

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
This relates to https://github.com/ministryofjustice/cloud-platform/issues/7095
=> pre upgrade add on bump for vpc-cni

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
this relates to issue relates to https://github.com/ministryofjustice/cloud-platform/issues/7097
=> upgrade coredns prior to upgrade

terraform/aws-accounts/cloud-platform-aws/account/live-2-opensearch.tf
=> fix: set 3 master nodes

scripts/opensearch/alert/cold_indices_alert.sh
=> fix: update os cold indices threshold

terraform/aws-accounts/cloud-platform-aws/account/live-2-opensearch.tf
- Set IOPs to 16000 to prevent failure
=> fix: set iops to 16000

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/3.25.7
=> chore: 🤖 nginx alert monitoring

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- rollback the opensearch s3 snapshot repo update
=> chore: rollback the opensearch s3 snapshot repo update

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
this pr relates to https://github.com/orgs/ministryofjustice/projects/65/views/3?pane=issue&itemId=107766272&issue=ministryofjustice%7Ccloud-platform%7C7100
=> update terraform code to match cluster

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
relates to ministryofjustice/cloud-platform#7102
=> chore: 🤖 update kubeproxy add-on post k8s 1.31 upgrade

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
relates to ministryofjustice/cloud-platform#7101
=> chore: 🤖 update vpc-cni add-on post k8s 1.31 upgrade

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- create opensearch s3 snpashot repo with [new module](https://github.com/ministryofjustice/cloud-platform-terraform-opensearch-snapshot-repository)
=> chore: create opensearch s3 snpashot repo

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf, terraform/aws-accounts/cloud-platform-aws/account/live-2-opensearch.tf, terraform/aws-accounts/cloud-platform-aws/account/modsec-opensearch.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf, terraform/aws-accounts/cloud-platform-ephemeral-test/vpc/eks/cluster.tf
- I am leaving, remove references to me
=> feat: 🎸 remove Jaskaran

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch-snapshot-s3.tf
- create opensearch s3 snpahshot repo
=> feat: create opensearch s3 snpahshot repo

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch-snapshot-s3.tf, terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- update opensearch access role with s3 permission
=> chore: update opensearch access role with s3 permission

terraform/aws-accounts/cloud-platform-aws/account/app-opensearch-snapshot-s3.tf, terraform/aws-accounts/cloud-platform-aws/account/app-opensearch.tf
- cleanup unused code as they are not needed for opensearch s3 snapshot repository
=> chore: cleanup unused code

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/.terraform.lock.hcl, terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/components.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/main.tf, terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/versions.tf
relates to ministryofjustice/cloud-platform#7386
=> chore: 🤖 bump components helm provider and modules

scripts/opensearch/snapshots/restore_snapshots/restore_snapshot.sh
- fixup the syntax for the opensearch restore script
=> fix: Fix opensearch snapshot restore script

terraform/aws-accounts/cloud-platform-aws/vpc/transit-gateway-routes/routes.tf
=> Add route to ECP via ECP TGW

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/external_secrets_operator.tf
- bump eso
https://github.com/ministryofjustice/cloud-platform-terraform-external-secrets-operator/releases/tag/0.2.0
- relates to https://github.com/ministryofjustice/cloud-platform/issues/7417
=> chore: bump eso

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/external_dns.tf
This pr is related to issue https://github.com/orgs/ministryofjustice/projects/65?pane=issue&itemId=120717229&issue=ministryofjustice%7Ccloud-platform%7C7379
[Release ](https://github.com/orgs/ministryofjustice/projects/65?pane=issue&itemId=120717229&issue=ministryofjustice%7Ccloud-platform%7C7379)
=> temporarily change image to the external-dns bitnami legacy

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/gatekeeper.tf
https://github.com/ministryofjustice/cloud-platform-terraform-gatekeeper/releases/tag/1.16.11
=> point to gk module source 1.16.11

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/velero.tf
[release](https://github.com/ministryofjustice/cloud-platform-terraform-velero/releases/tag/2.5.2)
=> chore: 🤖 bump velero for cpu limit increase

terraform/aws-accounts/cloud-platform-aws/vpc/main.tf
This PR will update the names of transit gateway endpoint subnets to fit existing style
=> Update names of transit gateway endpoint subnets

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/monitoring.tf
Update node scale up/down lower priority alert to use info severity to stop some noise.
=> Bump monitoring module to include changes to node scale alert

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/starter_pack.tf
[release notes](https://github.com/ministryofjustice/cloud-platform-terraform-starter-pack/releases/tag/0.3.1)
=> chore: 🤖 bump starter pack for bitnami legacy image

test/ingress_class_deny_test.go
relates to ministryofjustice/cloud-platform#7594
=> test: 💍 add int test for gatekeeper deny bad ingress class

terraform/aws-accounts/cloud-platform-aws/account/firehose.tf
Pointing Firehose Mod Calls to Latest Release.
=> Bump Mod Version Referenced for Firehose to 1.1.0

terraform/aws-accounts/cloud-platform-aws/vpc/eks/core/components/ingress.tf
[Release notes](https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/releases/tag/1.18.0)
relates to ministryofjustice/cloud-platform#7606
=> chore: 🤖 bump internal ingress modules

terraform/aws-accounts/cloud-platform-aws/vpc/eks/cluster.tf
[Release notes](https://github.com/ministryofjustice/cloud-platform-terraform-eks-add-ons/releases/tag/1.19.0)
relates to ministryofjustice/cloud-platform#7621
=> chore: 🤖 bump eks add-ons module

terraform/aws-accounts/cloud-platform-aws/account/main.tf
- https://github.com/ministryofjustice/cloud-platform-terraform-aws-sso/releases/tag/1.12.1
- relates to https://github.com/ministryofjustice/cloud-platform/issues/7616
=> chore: bump sso
