ministryofjustice/cloud-platform-infrastructure

- .travis.yml
- Dangerfile
We should use [our existing Danger configuration](https://github.com/ministryofjustice/danger) to make sure our pull requests and commits are in line with the MOJ's standards (as much as we can, anyway).
> Configure Danger to review pull requests

- cluster-components/external-dns/helm-values.yml
Configures external-dns to manage records in the cloud-platforms-sandbox.k8s.integration.dsd.io DNS zone only, and only for Service objects as we’ll be using a single shared ELB with a wildcard DNS record for now.
> Adds Helm values file for external-dns

- cluster-components/nginx-ingress/helm-values.yml
- terraform/acm.tf
- terraform/dns.tf
- terraform/main.tf
We want to use nginx-ingress to handle all inbound traffic, with SSL termination at its ELB, forcing HTTP->HTTPS redirection, preserving source IP address, and with a wildcard DNS entry (*.apps.cluster) pointing to the ELB. This PR:
- adds an ACM certificate with Terraform for attachment to the ELB, using DNS request validation 
- adds a HTTP->HTTPS redirect to all applications' nginx server{} directive
- adds a DNS record annotation for the Service ELB, for use by external-dns
- adds an annotation containing an ACM ARN (cert must already exist and match the DNS name specified for external-dns)
- configure the ELB to handle SSL traffic on port 443 only
- configure the ELB to use non-SSL HTTP for instance traffic (so SSL is terminated on the ELB)
- configure the ELB to also send non-HTTP …
> Configure nginx-ingress SSL handling and DNS

- cluster-components/helm/rbac-config.yml
Helm requires a `ClusterRoleBinding` in RBAC-enabled cluster, included in this PR.
> Adds RBAC config for Helm

- terraform/cloud-platform/main.tf
- terraform/cloud-platform/variables.tf
- terraform/global-resources/dns.tf
- terraform/global-resources/main.tf
- terraform/global-resources/outputs.tf
- terraform/global-resources/s3.tf
- terraform/global-resources/variables.tf
- terraform/modules/cluster_dns/dns.tf
- terraform/modules/cluster_dns/outputs.tf
- terraform/modules/cluster_dns/variables.tf
- terraform/modules/cluster_ssl/acm.tf
- terraform/modules/cluster_ssl/outputs.tf
- terraform/modules/cluster_ssl/variables.tf
- terraform/modules/kops_state/s3.tf
- terraform/modules/kops_state/variables.tf
As we're about to start adding more Terraform resources, a more structured approach is required to allow us to separate out per-environment resources from shared "global" resources, and to allow us to apply platform/cluster-level resources repeatedly in multiple environments (e.g. production, staging, individual dev environments, etc.)
This PR:
- moves top-level Terraform resources to [Terraform modules](https://www.terraform.io/docs/modules/usage.html) 
- makes use of [Terraform workspaces](https://www.terraform.io/docs/state/workspaces.html), to allow us to apply the same resources to multiple environments
- splits Terraform state into "global" for resources that aren't environment specific (parent DNS, platform environment state S3 bucket), and "platform" for environment-specific …
> Refactor Terraform resources

- cluster-components/metrics-server/auth-delegator.yaml
- cluster-components/metrics-server/auth-reader.yaml
- cluster-components/metrics-server/metrics-apiservice.yaml
- cluster-components/metrics-server/metrics-server-deployment.yaml
- cluster-components/metrics-server/metrics-server-service.yaml
- cluster-components/metrics-server/resource-reader.yaml
Copied from https://github.com/kubernetes-incubator/metrics-server
The Metrics API is currently in beta, and removes Kubernetes’s hard dependency on Heapster for summary CPU and RAM metrics. This is useful for quick overviews of pod and node resource usage, with `kubectl top pods` and `kubectl top nodes`. The metrics server is also required for kubernetes autoscaler services
> Add k8s metrics-server resources

- rules/add-github-teams-to-saml-mappings.js
- terraform/cloud-platform/main.tf
- terraform/global-resources/main.tf
As the aws_federation Terraform module creates a temporary webops admin IAM role with a fixed name it currently causes an error when attempting to apply Terraform resources in multiple workspaces, as IAM role names are unique.
In the long term IAM roles should be created dynamically, either via Github events or as part of the identity broker authentication flow. For now though, the simplest thing to do is to move the federation module into the `global-resources` TF resources, as they are not workspace-specific.
As this modifies both `global-resources` and `cloud-platform` state, `terraform apply` will need to be run in the `global-resources` context, and each `cloud-platform` workspace.
> Move aws_federation TF module to global resources

- terraform/global-resources/ecr_credentials.tf
this pr is related to bullet point 
An ecr_credentials.tf file has been added to global-resources in kubernetes-investigations which imports and uses the module to create a user, policy and credentials
of issue:
https://github.com/ministryofjustice/cloud-platform-reference-app/issues/29
the ecr_credentials.tf file create the user , ecr repo and credentilas for the demo app
> added ecr creds creation in global resources

- terraform/README.md
- terraform/global-resources/ecr_credentials.tf
This documentation is part of bullet point:
`These instructions have been read and tested for clarity and correctness by a third party (not the developer or reviewer).`
of issue
https://github.com/ministryofjustice/cloud-platform-reference-app/issues/29
This document should cover all terraform code within the terraform directory of this repo, however to keep the focus of the issue https://github.com/ministryofjustice/cloud-platform-reference-app/issues/29 it is only centered in the ECR credentials part of it, outlining only the structure for future documentation of other parts.
this document covers instructions for cloud platforms team to create ecr credentials for other teams when requested
> Ecr terraform module documentation

- kops/cloud-platform-test-0.yaml
connects to https://github.com/ministryofjustice/cloud-platform/issues/164
I need a separate test cluster to do concourse work on without stepping
on Mitch's toes. When I commissioned the `test-1` cluster, I **should**
have named it `test-0`. This fills that gap in the sequence.
TODO: Remove the `cloud-platforms-test` cluster.
> Add test-0 cluster

- dns-redirect.md
connects to https://github.com/ministryofjustice/cloud-platform/issues/215
**WHAT**
This PR contains relevant information to perform a DNS redirect via AWS Route53.
**WHY**
If the live environment fails we have the ability to redirect URL's pointing to the failed cluster.
> Add instructions on DNS Failover

- docs/disaster-recovery/Create-Cluster.md
**WHAT**
- Cluster creation document amended with a single line asking to only include the Github connection. 
**WHY**
-Because of a recent issue with our auth0 setup, it was noticed that some auth0 applications had been setup with basic username and password selected as a connection method.
> Add additional security step to cluster creation doc

- cluster-components/kuberos/cloud-platform-live-0/kuberos.yml
connects to ministryofjustice/cloud-platform#121
**WHAT**
- Change kuberos port to 443 instead of 80
- Update deployment image to point to the new kuberos
**WHY**
Switching over the image, deploys the new kuberos to `cloud-platform-live-0`.
> Switch over Kuberos image and secure connection

- kops/cloud-platform-test-1.yaml
Amended Kops clusterspec to include audit-logging. Defining where logs are stored / size. 
Added fileAssets to include audit policy - defining what events should be included.
> kops audit logs 

- kops/cloud-platform-live-0.yaml
Due to the nature of EBS volumes being tied to a single AZ in AWS, when performing a rolling-update in nodes there is a period between terminating a node and when the replacement is launched during which, pods using EBS volumes are unable to schedule.
This change doubles the number of nodes so that there is always at least one available per zone during a rolling update.
> Increase live-0 node count

- cluster-components/nginx-ingress/cloud-platform-live-0-helm-values.yaml
- cluster-components/nginx-ingress/cloud-platform-test-1-helm-values.yaml
WHAT
HTTP requests reaching a service to include an X-Request-Id header.
WHY
Able to send back a unique request ID with every response; useful for debugging projects but also for offering support to any third parties who might use the service
> Add generate request id to ingress-controllers

- kops/cloud-platform-live-0.yaml
After some investigation, it was discovered that we aren't utilising the full capacity of the cluster. We've decided that we can cut the instance size in half and scale horizontally if required.
> Change the worker nodes size in Kops

- terraform/cloud-platform-components/metris-server.tf
WHAT
Use terraform to automate installation of metrics server on k8s clusters
WHY
Able to run kubectl top nodes/pods on cluster
> Automate metrics-server install

- kops/cloud-platform-live-0.yaml
**Overview**
---
It has come to light that our current node size on live-0 is far too small. Whilst investigating a Prometheus issue a node size of 7.5MiB is far too small. Prometheus itself is asking for ~4.5. 
This causes scheduling problems when a node reaches a certain limit and cannot be resolved by horizontally scaling. 
**Implementation**
---
The implementation has already taken place and is now active in Live-0. This PR is to record the change and the state.
> Change kops node size to allow for greater memory use

- terraform/cloud-platform/templates/kops.yaml.tpl
**Overview**
---
Following on from PR #112 the below request was made. This PR encompasses that request along with the removal of the `component` tag, as this was duplicated.
```
stevemarshall [19:06]
@jasonb That’s ace! One minor thing: `business-unit` should be `platforms`. Also, I might argue for `MOJ Cloud Platform` for `application`, and `infrastructure-support` is optional (for cases like this).
So that was three things, actually. Still: thanks for doing this so quickly!
```
> Kops template label change

- terraform/cloud-platform/templates/kops.yaml.tpl
It was decided that we need to keep the kops label in nodelabels
> Add tag to all nodes in kops template

- terraform/cloud-platform-components/kuberos.tf
This PR changes the replica count for the kuberos app from 1 to 2 so there is redundancy if one of the pods fails for any reason.
> Add second pod for Kuberos app

- haproxy/dns.tf
- haproxy/outputs.tf
- haproxy/variables.tf
This is a boolean value to determine whether the module will manage the top-level DNS record. This is for cases where this record is already managed (eg. cloudformation) and we don't want to manage it in two places.
> Add manage_dns variable for haproxy module

- terraform/cloud-platform/templates/kops.yaml.tpl
* disable read-only port
* enable `authentication-token-webhook` (allows prom to properly scrape kubelets and authenticated users to hit the api, see [here](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet-authentication-authorization/#kubelet-authentication))
> Kubelet updates

- haproxy/cloudwatch.tf
Fixes an error when the count is zero.
> Replace list() with splat syntax

- terraform/cloud-platform-components/README.md
- terraform/cloud-platform-components/external-dns.tf
- terraform/cloud-platform-components/kiam.tf
- terraform/cloud-platform-components/resources/kiam-servicemonitor.yaml
- terraform/cloud-platform-components/templates/kiam.yaml.tpl
- terraform/cloud-platform/kops.tf
- terraform/cloud-platform/templates/kops.yaml.tpl
Connects to https://github.com/ministryofjustice/cloud-platform/issues/564
In order to simplify the setup, kiam agent `Pods` run only on node hosts. This allows other `Pods` running on master hosts to assume the host's IAM role as before and avoids breaking any of the kubernetes components. We do not intent to run user workload on master nodes so this should be safe. However, it is probably now worth enabling the [`PodTolerationRestriction` admission controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podtolerationrestriction) to actually prevent user workload from being scheduled on a master node.
Because the trust (assume) policy uses an instance role as a principal (see the example in the README), we need to run kiam server `Pods` on a specific …
> Kiam cluster component

- haproxy/cloudwatch.tf
This will allow the alarms to close when they're missing data.
> haproxy: handle alarm missing data

- terraform/global-resources/elasticsearch.tf
**Why**
Cluster IPs were forgotten in the ES/Kibana ACL
> Remove test-1 IPs

- terraform/cloud-platform-components/nginx-ingress.tf
**WHAT**
Update the helm chart for nginx-ingress to v1.1.4
**WHY**
We want to try to always use the latest chart, or at the very least not fall too far behind and make use of latest features
**What this PR does?**
This PR simply changes the version on the terraform to use v1.1.4 of the chart
> Update nginx-ingress to helm v1.1.4

- haproxy/README.md
This is useful when changing weights, to ensure a zero downtime transition.
> Add instructions for a rolling update of haproxy

- helm-charts/oidc-proxy/.helmignore
- helm-charts/oidc-proxy/Chart.yaml
- helm-charts/oidc-proxy/README.md
- helm-charts/oidc-proxy/templates/NOTES.txt
- helm-charts/oidc-proxy/templates/_helpers.tpl
- helm-charts/oidc-proxy/templates/configmaps.yaml
- helm-charts/oidc-proxy/templates/deployment.yaml
- helm-charts/oidc-proxy/templates/ingress.yaml
- helm-charts/oidc-proxy/templates/secret.yaml
- helm-charts/oidc-proxy/templates/service.yaml
- helm-charts/oidc-proxy/values.yaml
**Overview**
---
This PR contains the OIDC-proxy Helm chart as outlined in https://github.com/ministryofjustice/cloud-platform/issues/583. The idead behind this Helm chart is to create a 'plug and play' template for applications wishing to use an auth proxy. Initially the team will use this to create an auth layer in front of Prometheus and Alert Manager. This will be written in Terraform and will be presented in a separate PR. 
**What's in this PR?**
---
- The oidc-proxy helm chart stored in the `/helm-charts` directory.
- A supporting `values.yaml` file containing default values, which are to be populated at run time.
- A README displaying proper use of the Helm chart.
**What does it do?**
---
This PR will enable the team to automate the process of including an OIDC proxy authenticator.
> Add OIDC Proxy Helm Chart

- terraform/cloud-platform-components/prometheus.tf
- terraform/cloud-platform-components/templates/oidc-proxy.yaml.tpl
**Overview**
---
This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/583, which builds upon and utilises the OIDC-proxy Helm chart created in https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/144. 
**What does this PR contain?**
---
An amendment to the `prometheus.tf` file in `/terraform/cloud-platform-components`.
**Why perform this change?**
---
The `cloud-platform-components` state allows us to bootstrap the Cloud-Platform to a point of instant usage. This addition will enable the automation of the AlertManager and Prometheus proxies, linking up with the OIDC client created at cluster build. This saves engineers time at creation.
> Add AlertManager and Prometheus proxies to Terraform components

- terraform/global-resources/README.md
url link to GuardDuty readme not working correctly
> correct-guardduty-readme-link

- terraform/cloud-platform-components/README.md
WHAT
Need a way to route specific alerts to named slack channels 
WHY 
Custom alerts should only notify the teams/channels that want to know about it
> Add AM alerting routes documentation

- terraform/cloud-platform-components/external-dns.tf
- terraform/cloud-platform-components/main.tf
Fixes an issue where external-dns assumes the node's role which has no access to edit the route53 zone.
> Specify role for external-dns

- terraform/cloud-platform-components/templates/oauth2-proxy.yaml.tpl
It's a known fact that helm chart quality is seemingly random.
Because of https://github.com/helm/charts/blob/master/stable/oauth2-proxy/templates/deployment.yaml#L38-L42
> Convert booleans to strings

- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
Overview
---
This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/653 and resolves the alert blindness and fatigue we currently get in our low priority slack channel. It was decided in a team gathering that the best way to solve this is to null the alert and add a new custom alarm containing the relevant namespaces.
What
---
Add the appropriate alert name to receiver `null` (i.e. ignored)
Why
---
So we can be more precise with relevant namespaces.
> Add cpu threshold receiver 'null'

- terraform/global-resources/elasticsearch.tf
Connects to https://github.com/ministryofjustice/cloud-platform/issues/658. Due to a legitimate lack of disk space it has been decided that we'll bump the disk space. As we've hit max EBS capacity we've had to increase the node count.
> Increase ES node count in live

- terraform/cloud-platform-components/prometheus.tf
- `recreate_pod` introduces a lot of unnecessary pod bouncing when changes are applied. It's best used for development
or special cases (the old oidc-proxy for example)
- upgrade the prometheus chart to latest which also pulls latest grafana and fixes a race condition with datasources
https://github.com/helm/charts/pull/9842
> Upgrade prometheus chart and remove recreate_pods

- cloudformation/cloud-platform-security/aws-iam-suspend-inactive-users/README.md
- cloudformation/cloud-platform-security/aws-iam-suspend-inactive-users/check_inactive_users.yaml
- cloudformation/cloud-platform-security/aws-iam-suspend-inactive-users/lambda/delete_users_in_suspendedusersgroup.py
- cloudformation/cloud-platform-security/aws-iam-suspend-inactive-users/lambda/disable_unused_credentials.py
- cloudformation/cloud-platform-security/aws-iam-suspend-inactive-users/lambda/slack_integration.py
- cloudformation/cloud-platform-security/aws-iam-suspend-inactive-users/package_template.sh
To increase the security of the AWS account, we need to remove IAM user credentials (that is, passwords and access keys) that are not needed.
The template deactivates unused credentials and then moves the user accounts to the suspended user group with deny all policy
> add inactive user check template

- README.md
The Grafana Terraform in cloud-platform-components now creates a secret and the aggregator is no longer required.
> Remove unwanted grafana references

- terraform/global-resources/elasticsearch.tf
This PR connects to ministryofjustice/cloud-platform#639
This PR contains an update to the AWS hosted ElasticSearch cluster terraform configuration. 
The ES cluster version has been changed from 6.2 to 6.4 for the `Live` and `Audit` clusters.
> Upgraded ES version from 6.2 to 6.4

- terraform/cloud-platform-components/nginx-ingress.tf
This prevents any kind of update to nginx-ingress which is going to be decommissioned in favour of nginx-ingress-acme.
> Set version of nginx-ingress to the current one

- terraform/cloud-platform-components/cert-manager-external.tf
- terraform/cloud-platform-components/cert-manager.tf
- terraform/cloud-platform-components/main.tf
- terraform/cloud-platform-components/nginx-ingress-acme.tf
- terraform/cloud-platform-components/nginx-ingress.tf
- terraform/cloud-platform-components/templates/cert-manager/letsencrypt-production.yaml
- terraform/cloud-platform-components/templates/cert-manager/letsencrypt-staging.yaml
- terraform/cloud-platform-components/templates/nginx-ingress/default-certificate.yaml
This is to enable certificate validation for externally-managed route53 zones.
> Setup cert-manager with access to a list of dsd zones

- terraform/cloud-platform-components/external-dns.tf
The `roleArn` chart attribute is only used when the chart is supplied with a set of IAM keys.
This ensures external-dns will assume the correct role.
> Use external-dns cli flag to set role

- terraform/cloud-platform/templates/kops.yaml.tpl
It is causing issues with the cert-manager validation webhook being unreachable.
See https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/276 for details on the issue.
Further reading:
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#enable-initializers-alpha-feature
https://github.com/kubernetes/kops/blob/master/docs/cluster_spec.md#runtimeconfig
> Enable dynamic admission controller registration API

- terraform/cloud-platform-components/nginx-ingress-acme.tf
- terraform/cloud-platform-components/nginx-ingress.tf
- terraform/cloud-platform/templates/kops.yaml.tpl
**Why**
https://grafana.apps.cloud-platform-live-0.k8s.integration.dsd.io/d/6581e46e4e5c7ba40a07646395ef7b23/k8s-compute-resources-pod?refresh=10s&orgId=1&var-datasource=Prometheus&var-namespace=ingress-controllers was showing high res usage and users were reporting 504 errors
> increase node and ingress limits

- terraform/cloud-platform-components/resources/prometheusrule-alerts/Custom-Alerts.md
WHAT
Runbook for node level custom alarms 
WHY
Runbook to be used to look into Actions to take when an alert is triggered. 
Runbook will also used to create links at add to each alert annotation
> Add Custom Alarm Runbook

- terraform/cloud-platform-components/resources/prometheusrule-alerts/node-alerts.yaml
WHAT
Add node level custom alerts for Prometheus on a node level
WHY
Admins need to have alerts for node level resources such as CPU and Memory
> Add node level Prometheus alerts

- terraform/cloud-platform-components/cert-manager-external.tf
- terraform/cloud-platform-components/nginx-ingress-acme.tf
- terraform/cloud-platform-components/nginx-ingress.tf
Connects to https://github.com/ministryofjustice/cloud-platform/issues/721
Also related to https://github.com/ministryofjustice/cloud-platform/issues/685
> live-0: allow cert-manager to issue domains for checklegalaid.service.gov.uk.

- terraform/cloud-platform-components/external-dns.tf
This breaks external dns:
1. kiam gives the Pod credentials for the correct role (controlled by the Pod annotation)
2. external-dns tries to assume the role which fails
We don't need step (2) since (1) gives us the correct set of credentials.
> live-0: Remove aws-assume-role from external-dns config

- terraform/cloud-platform-components/cert-manager-external.tf
- terraform/cloud-platform-components/nginx-ingress-acme.tf
> live-1: allow cert-manager to issue domains for checklegalaid.service.gov.uk.

- terraform/cloud-platform-components/external-dns.tf
This breaks external dns:
1. kiam gives the Pod credentials for the correct role (controlled by the Pod annotation)
2. external-dns tries to assume the role which fails
We don't need step (2) since (1) gives us the correct set of credentials.
> live-1: Remove aws-assume-role from external-dns config

- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
These are based on current usage (and are generous values!) but they are still a lot less than the defaults in
LimitRange which cause scheduling problems.
> live-0: define node-exporter resources

- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
These are based on current usage (and are generous values!) but they are still a lot less than the defaults in
LimitRange which cause scheduling problems.
> Define node-exporter resources

- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
The actual chart is prometheus-node-exporter and the definition needs to be moved accordingly.
> Redefine node-exporter resources

- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
The actual chart is prometheus-node-exporter and the definition needs to be moved accordingly.
> live-0: Redefine node-exporter resources

- terraform/cloud-platform-components/external-dns-dsd.tf
- terraform/cloud-platform-components/external-dns.tf
- terraform/cloud-platform-components/nginx-ingress-acme.tf
Some more detail beyond the commit messages.
Upgrading the version of external dns seems to address an issue I saw with external-dns going in a loop because the
owner of the record was `""`! Unfortunately, I don't see anything that directly references this in the changelog.
> Hotfixes that came up during the FALA migration.

- terraform/cloud-platform-components/resources/psp/pod-security-policy.yaml
**Overview**
---
This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/749 and ensures that Pod Security Policies work in live-1. 
**What does it include and why**
---
It adds namespaces that require privileged pods to the clusterrole which uses the privileged psp.
> Allow critical namespaces access to the Privileged PSP

- terraform/cloud-platform-components/resources/cert-manager/servicemonitor.yaml
This will allow the `ServiceMonitor` to detect scrapable endpoints.
> live-0/cert-manager: add labels to the metrics service

- terraform/cloud-platform-components/resources/cert-manager/servicemonitor.yaml
This will allow the `ServiceMonitor` to detect scrapable endpoints.
See #214 also
> live-1/cert-manager: add labels to the metrics service

- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
WHAT
Deactivate 2 default prometheusrules set by prometheus-opertaor 
WHY
The general and application default rules set by prometheus-operator have been deactivated and we will create our own custom alerts for application monitoring in specific namespaces
> Change PrometheusRules default rules

- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
**Overview**
---
Now PSPs are enabled in the cluster, Grafana immediately tries to use apparmor. It has been decided this will not be enabled and thus breaks the Grafana install. This PR removes the apparmor configuration using the instruction here: https://github.com/helm/charts/tree/master/stable/prometheus-operator#grafana
> Remove apparmor from Grafana

- terraform/cloud-platform-components/prometheus.tf
This PR is to add a resource to apply custom-alerts to current Prometheus installation in Terraform (https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/terraform/cloud-platform-components/prometheus.tf).
> Added resource in prometheus.tf to apply alerts

- terraform/cloud-platform-components/prometheus.tf
Add local exec within the prometheus-oprator resource to add custom alerts as part of the install and not make it an option using a dedicated resource
>  Add custom rules within operator resource

- terraform/global-resources/resources/auth0-rules/add-github-teams-to-oidc-group-claim.js
This should now take into account only teams within the ministryofjustice org.
> Revisit the auth0 oidc group script

- terraform/cloud-platform-components/prometheus.tf
- terraform/cloud-platform-components/resources/prometheusrule-alerts/Custom-Alerts.md
- terraform/cloud-platform-components/resources/prometheusrule-alerts/application-alerts.yaml
- terraform/cloud-platform-components/resources/prometheusrule-alerts/node-alerts.yaml
- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
WHAT
Add custom alerts to Prometheus and apply rules as part of the prometheus-operator install
WHY
The custom rules monitor CP team namespaces as well as system namespaces and are based on the business unit-cloud-platform annotation. The auto apply of these rules also mean they will not be missed if there is a need to reinstall prometheus-operator. Associated runbbook does have also been updated with runbook_url added to all alerts.
> Custom Alert Rules added to operator install - live0

- terraform/cloud-platform-components/resources/prometheusrule-alerts/application-alerts.yaml
- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
There is a duplicate alert in one of the default rules set which has been set to null receiver as there is a requirement for all the other rules in that set. The alert in custom alerts has had its name changes so we still get the alert
> Set Duplicate alert to Null Receiver

- terraform/cloud-platform-components/resources/prometheusrule-alerts/application-alerts.yaml
- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
There is a duplicate alert in one of the default rules set which has been set to null receiver as there is a requirement for all the other rules in that set. The alert in custom alerts has had its name changes so we still get the alert
> Set Duplicate alert to Null Receiver - live0

- terraform/cloud-platform-components/nginx-ingress-acme.tf
- terraform/cloud-platform-components/nginx-ingress.tf
This has the effect of shifting all traffic to the new nginx-ingress.
> Move wildcard external-dns annotation to nginx-ingress-acme

- terraform/cloud-platform-components/cert-manager.tf
- terraform/cloud-platform-components/external-dns.tf
- terraform/cloud-platform-components/fluentd.tf
- terraform/cloud-platform-components/kuberos.tf
- terraform/cloud-platform-components/main.tf
- terraform/cloud-platform-components/nginx-ingress-acme.tf
- terraform/cloud-platform-components/prometheus.tf
- terraform/cloud-platform-components/templates/nginx-ingress/default-certificate.yaml
- terraform/cloud-platform-components/templates/oauth2-proxy.yaml.tpl
- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
- terraform/cloud-platform/main.tf
**Why**
We don't want the main monitoring/login page address to change when we switch clusters
> Shorter hostnames for live ingresses

- docs/rotate-git-crypt.md
Documents the process of rotating the `git-crypt` encryption key.
> Add runbook for rotating git-crypt key

- cloudformation/aws-account-baseline-templates/README.md
Update references to `security-guidance` and the formal baseline published location (https://ministryofjustice.github.io/security-guidance/standards/baseline-aws-accounts/#baseline-for-amazon-web-services-accounts)
> Update README.md for `security-guidance` refs

- terraform/cloud-platform/main.tf
**Why** 
Seems the new Kuberos actually follows the JWT expiration as set in auth0 and users must regenerate it every 10 hours
> increase Kuberos token to 30 days

- terraform/cloud-platform-components/resources/opa/opa-default-system-main.yaml
- terraform/cloud-platform-components/resources/opa/opa-psp-rbac.yaml
Being allowed to use the _privileged_ policy means binding it to the default service account of a namespace. A simple RoleBinding resource needs to be created.
>  PSP RoleBinding resource created for OPA

- terraform/cloud-platform-components/cert-manager.tf
- terraform/cloud-platform-components/external-dns.tf
This PR is to update external-dns and cert-manager configuration, so that:
-components in live-1 can access all the Route53 zones in the cloud-platform account 
-components in other clusters are only able to access their own dedicated zone
#802
> Update external-dns and cert-manager configuration

- terraform/cloud-platform-components/opa.tf
- terraform/cloud-platform-components/resources/opa/opa-default-system-main.yaml
- terraform/cloud-platform-components/resources/opa/opa-psp-rbac.yaml
- terraform/cloud-platform-components/resources/opa/policy-ingress-conflicts.yaml
- terraform/cloud-platform-components/templates/opa/values.yaml.tpl
This PR is to deploy OPA on live-0 and apply default and policy-ingress-conflicts policy.
OPA changes are already merged and applied on Live-1, this PR will get it to live-0.
> Opa for live-0

- terraform/global-resources/elasticsearch.tf
**Why**
fluentd send chunks > 10MB which is the maximum for m4.large so logging stopped around Mar 22
`2019-04-15 17:37:34 +0000 [warn]: [elasticsearch-audit] failed to flush the buffer. retry_time=90959 next_retry_seconds=2019-04-15 17:38:02 +0000 chunk="584af69db95dfdaed0843d387485351a" error_class=Elasticsearch::Transport::Transport::Errors::RequestEntityTooLarge error="[413] {\"Message\":\"Request size exceeded 10485760 bytes\"}"`
Will catch up now that it's unblocked
> Upgrade audit ES nodes

- terraform/global-resources/elasticsearch.tf
**Overview**
The audit cluster doesn't have a curator cronjob to clear disk space so inevitably the disk will fill. This is by design to keep as many logs as possible and to give the security team the option to decided to keep logs over x number of years.
> Increase audit ES cluster EBS volume size

- terraform/cloud-platform-components/fluentd.tf
**Why**
Cluster broken when disk filled up, AWS couldn't fix it; recreating with the same IP ACLs
> change test ES address

- helm-charts/fluentd-es/config/audit.input.conf
- helm-charts/fluentd-es/config/output.conf
- helm-charts/fluentd-es/config/system.input.conf
- helm-charts/fluentd-es/templates/fluentd-es-config.yaml
- terraform/cloud-platform-components/fluentd.tf
This allows us to disable audit log scraping by fluentd, which is very useful for test clusters. The current solution
does not work properly since it's set to log both into the same ElasticSearch cluster, something that's causing issues
due to the difference in mappings and structure of logs.
> Make audit logging optional in the fluentd-es chart

- terraform/cloud-platform-components/resources/psp/pod-security-policy.yaml
- `opa` uses a container running as root
- `kiam` needs to be able to mount host volumes and bind on the host network interfaces
> Allow privileged containers in opa and kiam namespaces

- terraform/global-resources/elasticsearch.tf
**Why**
A smaller cluster where test-* k8s fluentd will send logs; can have its data wiped at any time
> create test ES cluster

- helm-charts/fluentd-es/config/containers.input.conf
- helm-charts/fluentd-es/config/output.conf
- terraform/cloud-platform-components/nginx-ingress-acme.tf
Connects to https://github.com/ministryofjustice/cloud-platform/issues/846
This brings the following two changes:
- change `nginx-ingress` logformat to produce json documents
- update `fluentd` config to parse these records properly and direct them to separate elasticsearch indices
Overall, this should bring the cloud-platform elasticsearch implementation closer to the template-deploy setup.
Access logs are now structured and fields are extracted under `nginx-ingress.` and are properly mapped, allowing for
more complex but also performant queries.
> nginx-ingress structured logs

- helm-charts/fluentd-es/Chart.yaml
- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
Version bump was missed during the update and is needed for terraform to pick up the changes.
> Update fluentd-es helm chart version

- .circleci/config.yml
- cloudformation/aws-limit-monitor/README.md
- cloudformation/aws-limit-monitor/limit-monitor.template
WHAT
Set up AWS Limit Monitor on CP account
WHY
Get prior warning when we are reaching the limit for AWS resources so we can increase before hitting the max number available
> Add AWS Limit monitor

- helm-charts/fluentd-es/Chart.yaml
- helm-charts/fluentd-es/config/audit-index-template.json
- helm-charts/fluentd-es/config/output.conf
- helm-charts/fluentd-es/templates/fluentd-es-config.yaml
The index-template is no different from any other configuration file so we can manage in a separate file for consistency.
> Extract index template in separate file in fluentd-es chart

- cloudformation/aws-limit-monitor/README.md
- cloudformation/aws-limit-monitor/limit-monitor.template
Add default entires for slack webhook and channel. Also add instructions on readme for replacing dummy entries in AWS Parameter Store for real webhook and channel name.
> Add default entries for webhook and channel for AWS Limit Monitor

- terraform/cloud-platform-components/resources/opa/policies/ingress_clash.rego
- terraform/cloud-platform-components/resources/opa/policies/ingress_clash_test.rego
- terraform/cloud-platform-components/resources/opa/policies/main.rego
It is simpler to keep all policy rules in the same package for simplicity, until we have a reason for using multiple
packages.
This is already applied on `live-1` and working as intended.
> Simplify package model for opa policies

- terraform/cloud-platform-components/opa.tf
opa will annotate policy configmaps to indicate successful parsing and terraform wants to remove this annotation since
it is not defined in code.
> Ignore opa policies annotations

- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
On user request updated the channel name from inf_alerts to cica_inf_alerts for alertmanager:config:receivers
> Update the channel name from inf_alerts to cica_inf_alerts

- terraform/cloud-platform/main.tf
Until we move to 0.12, this version will need to be pinned
> Add pinned VPC module version

- create-cluster.sh
- example.env.create-cluster
The process for building a new cluster, as documented in the current runbooks site, has several manual steps.
This PR adds a `create-cluster.sh` script which:
* Checks all pre-requisites (env. vars, software tools installed, aws profiles)
* Validates that the cluster name is acceptable (if too long, things break)
* Builds the cluster infrastructure (VMs, networks, etc.)
* Uses kops to create a kubernetes cluster
* Installs the cluster 'components'
There is also an 'example.env.create-cluster' which shows how to create
a `.env` file containing all the environment variables which the script
needs.
At the time of writing, the script takes just under 30 minutes to build a new
cluster from scratch.
> Add a script to build a cluster non-interactively

- terraform/cloud-platform-components/resources/storageclass.yaml
- terraform/cloud-platform-components/storageclass.tf
WHAT
Create a new StorageClass as part of cluster components creation
WHY
This StorageClass is required to create PVs that can be expanded. 
StorageClass name: gp2-expand
> Add creation of new StorageClass

- terraform/cloud-platform/templates/kops.yaml.tpl
This is related to https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/982
> Increased rootVolumeSize from default size of 128  to 256

- terraform/cloud-platform-components/prometheus.tf
This was causing conflicts when applying terraform, the ignore changes allows changes to be made in the environments repository.
The annotation removed (below) still needs to exist so this will be added here:
https://github.com/ministryofjustice/cloud-platform-environments/blob/master/namespaces/live-1.cloud-platform.service.justice.gov.uk/monitoring/00-namespace.yaml
> Remove monitoring namespace annotation

- helm-charts/prometheus-ecr-exporter/.helmignore
- helm-charts/prometheus-ecr-exporter/Chart.yaml
- helm-charts/prometheus-ecr-exporter/templates/_helpers.tpl
- helm-charts/prometheus-ecr-exporter/templates/deployment.yaml
- helm-charts/prometheus-ecr-exporter/templates/service.yaml
- helm-charts/prometheus-ecr-exporter/templates/servicemonitor.yaml
- helm-charts/prometheus-ecr-exporter/values.yaml
- terraform/cloud-platform-components/ecr-exporter.tf
Connects to https://github.com/ministryofjustice/cloud-platform/issues/985
Adds a custom helm chart for the ecr-exporter and adds the `helm_release` resource in components.
> Add prometheus-ecr-exporter as a component

- terraform/cloud-platform-components/fluentd.tf
- Replaced the test-elasticsearch endpoint that's applied to all non-live cluster 
- The new endpoint is a placeholder string, which seems to stop Fluentd from crashing
- If the test cluster has to be used, that string would have to be replaced manually.
> replace test ES cluster enpoint with placeholder string

- .circleci/config.yml
This has been tested by deliberately breaking one of the OPA tests:
https://circleci.com/gh/ministryofjustice/cloud-platform-infrastructure/1245
> Run opa tests in the CircleCI pipeline

- terraform/cloud-platform-components/nginx-ingress-acme.tf
- terraform/cloud-platform-components/resources/opa/policies/service_type_test.rego
The kubernetes terraform provider does not seem to be capable of properly distinguishing between an empty value annotation and a non-existing annotation.
This PR ensures that the annotation for the `ingress-controllers` namespace has a value and that our policy accepts any value.
> Minor fix to the OPA policy for LoadBalancers

- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
This will allow us to upgrade to k8s 1.12.10. An error was caught in testing, which was outlined in this issue: https://github.com/coreos/prometheus-operator/issues/2409
> Bump prometheus-operator version

- helm-charts/fluentd-es/values.yaml
- This involves the fluentd-es helm chart 
- The original repository seems to be unusable
- Going from a gcr repo to a quay
Following the change from here : [kiwigrid/helm-charts/](https://github.com/kiwigrid/helm-charts/commit/c77bb5e6eb04e1edfdc484a6365d91a4cce44582#diff-ce2053c6a9600163b2470fff5f935948)
> Update fluentd docker image, gcr -> quay

- terraform/cloud-platform-components/cert-manager-dsd.tf
- terraform/cloud-platform-components/cert-manager.tf
- terraform/cloud-platform-components/external-dns.tf
- terraform/cloud-platform-components/kiam.tf
- terraform/cloud-platform-components/nginx-ingress-acme.tf
- terraform/cloud-platform-components/opa.tf
- terraform/cloud-platform-components/prometheus.tf
When building a new cluster, during the `terraform apply` step for the
terraform/cloud-platform-components, we were seeing a lot of errors. So,
the build script executes a second pass, during which all the errors are
resolved.
This commit adds explicit dependencies in the terraform code so that the
components are installed in the correct order, meaning `terraform apply`
only needs to be executed once to install all the components.
For reference, the errors which occurred during the development of this
PR were as follows (not all in the same build, and not in order):
* helm_release.open-policy-agent: 1 error occurred:
* helm_release.open-policy-agent: error creating tunnel: "could not find a ready tiller pod"
* kubernetes_secret.cert_manager_dsd: 1 error occurred:
* …
> Fix component dependencies

- kops/live-1.yaml
Why? 
An incident occurred on 15th July 2019 that was caused by a lack of resource. It was decided that we'd expand the capacity.
> Bump number of worker nodes in instance group

- terraform/cloud-platform-components/resources/cloudwatch-exporter.yaml
- Removing the `aws_statistics` field from the FreeStorageSpace metrics 
That way, the Prometheus CloudWatch Exporter will not produce an average of the RDS disk space.
> making the FreeStorageSpace RDS metric not an average

- terraform/cloud-platform-components/templates/kiam.yaml.tpl
This fix was required as we have scaled to 40 nodes, the scale causes crashlooping of the agent pods. By increasing the gateway timeout we allow the pods enough time to create
> WIP: Change KIAM agent gatewaytimeoutcreation

- smoke-tests/Dockerfile
- smoke-tests/makefile
**Overview**
---
This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/1117 and relates to the addition of the AWS cli to the smoke-tests image.  
We would like to use the AWS cli to grab an auth token from s3. This will allow us to authenticate against live-1 for https://github.com/ministryofjustice/cloud-platform-concourse/pull/91. 
The cli is installed via pip3 which needs python3.
> Add AWS CLI to Smoke Test Image

- terraform/cloud-platform-components/cluster-backup-checker.tf
Previously, the name variable for this role evaluated to [cluster name length] + 54 characters
This only leaves 10 characters for the cluster name, because of the 64 character limit on terraform strings. The build script enforces a limit of 12 characters, so this commit reduces the name of the iam role by 2 characters, so that no additional restrictions are added.
> Reduce name length for cluster backup checker role

- create-cluster.rb
- makefile
This change reduces the possible variance in the process of building a new
cluster, e.g. due to different operating systems or package versions on
different team members' machines.
This is a step towards being able to build test clusters via a pipeline or a
kubernetes job, although more needs to be done before that is possible.
Blocked by:
https://github.com/ministryofjustice/cloud-platform-tools-image/pull/23
> Alter the build script to make it possible to build clusters from the tools image

- smoke-tests/spec/error_page_spec.rb
This spec is currently failing, on new test clusters (although it
passes on live-1).
This commit marked the failing spec so that rspec will not try to
execute it.
After the underlying problem has been fixed, this spec should be
reinstated.
related to
https://github.com/ministryofjustice/cloud-platform/issues/1182
> Skip failing error pages spec

- smoke-tests/spec/ingress_spec.rb
- smoke-tests/spec/logging_spec.rb
- smoke-tests/spec/namespace_spec.rb
- smoke-tests/spec/spec_helper.rb
Test objects are often left lying around in the cluster, if tests fail to
finish cleanly. Using human-readable values in their names makes it easier
to identify these leftovers when manually deleting them, so that we don't
accidentaly delete the objects that are being used by tests running now.
> Instead of test-namespace-1566221162, create test-namespace-20190819142557

- smoke-tests/spec/kubernetes_helper.rb
- smoke-tests/spec/namespace_annotations_spec.rb
This test is marked to be skipped, because it currently fails when run against
live-1. That's because namespaces should be annotated, but aren't. So, the test
is correct, but live-1 is wrong.
Once all the namespaces in live-1 are annotated, this test should be reinstated
related to https://github.com/ministryofjustice/cloud-platform/issues/1150
> Add a test that all namespaces are annotated

- makefile
This ensures that the latest version of the tools image is
always being used. However, the docker pull might fail if the
user needs to re-authenticate to AWS ECR.
> Add a docker pull before running the tools image

- smoke-tests/spec/error_page_spec.rb
- smoke-tests/spec/spec_helper.rb
Previously, we were using a constant string 'foobar' for this
test. Sometimes, an initial failure in this test (perhaps because
the cluster wasn't quite ready?) would then result in every
subsequent test, using the same string, getting the same 500 error,
even though any other unknown hostname would work fine.
This commit attempts to mitigate this by using a random hostname
every time this test runs.
> Use a random hostname for the error page tests

- makefile
depends on
https://github.com/ministryofjustice/cloud-platform-tools-image/pull/28
This is a step towards getting the cluster build script to run via a
kubernetes job.
> Create a shell on a non-root tools image

- makefile
This reverts commit d0108a47d43a78b80ddf430bf91c42d59f17d66e.
Running a non-root tools image breaks our concourse pipelines, so
that change has been reverted, and so this one must be reverted
also.
> Revert "Create a shell on a non-root tools image"

- smoke-tests/Gemfile
- smoke-tests/Gemfile.lock
- smoke-tests/README.md
- smoke-tests/makefile
- smoke-tests/spec/constants.rb
- smoke-tests/spec/kiam_helper.rb
- smoke-tests/spec/kiam_spec.rb
- smoke-tests/spec/kubernetes_helper.rb
- smoke-tests/spec/spec_helper.rb
- smoke-tests/tags
Connects to https://github.com/ministryofjustice/cloud-platform/issues/1112
The test proves that, if a pod and namespace have appropriate annotations (and if the corresponding IAM role and policies are set up correctly), code running in the cluster can assume AWS IAM roles.
Co-authored-by: Poornima Krishnasamy <poornima.krishnasamy@digital.justice.gov.uk>, Jason Birchall <jason.birchall@digital.justice.gov.uk>
> Add kiam integration tests

- smoke-tests/makefile
The concourse pipeline seems to only find new
docker images if they are explicitly tagged as
:latest
This commit adds that tagging to the 'make push'
target
> Tag docker image with :latest

- makefile
- smoke-tests/spec/constants.rb
Eventually, the ECR version will be removed, so we
should start using the docker hub version ASAP
> Get the tools image from docker hub

- smoke-tests/Gemfile
- smoke-tests/Gemfile.lock
- smoke-tests/spec/route53_helper.rb
- smoke-tests/spec/spec_helper.rb
- added route53_helper, to create_zone, create_delegation_set and get_zone_records.
- added aws-sdk-route53 gem as a dependency in Gemfile, and spec_helper.
- Gemfile.lock
> add route53_helper, and relevant config

- smoke-tests/spec/logging_spec.rb
The logging spec has been failing intermittently in the concourse
pipeline. e.g.
* [build 547](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/integration-tests/jobs/apply-tests-live-1/builds/547)
* [build 533](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/integration-tests/jobs/apply-tests-live-1/builds/533)
* [build 526](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/integration-tests/jobs/apply-tests-live-1/builds/526)
* [build 517](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/integration-tests/jobs/apply-tests-live-1/builds/517)
This commit is an experiment to see if a larger sleep delay makes
these intermittent failures go away.
If it does, subsequent commits will …
> Increase logging test sleep from 60 to 120 seconds

- smoke-tests/spec/route53_helper.rb
- add deletion methods to route53_helper.rb
- delete_zone deletes a route53 zone
- delete_delegation_set deletes the set of NS record pointing from a parent to a child zone
> add delete_zone and delete_delegation_set

- smoke-tests/spec/ingress_spec.rb
Around four times per day, we see this, in the integration-tests
pipeline;
```
1) nginx ingress when ingress is deployed returns 200 for http get
Failure/Error: result = URI.open(url)
OpenURI::HTTPError:
503 Service Unavailable
Finished in 5 minutes 57 seconds (files took 1.63 seconds to load)
16 examples, 1 failure, 2 pending
Failed examples:
rspec ./spec/ingress_spec.rb:34 # nginx ingress when ingress is deployed returns 200 for http get
```
Usually, a subsquent test run will pass without any failures.
This commit is an attempt to reduce the frequency of these
failures, hopefully to zero.
> Increase delay for ingress 'happy path' test

- smoke-tests/spec/fluentd_spec.rb
- smoke-tests/spec/kubernetes_helper.rb
**Why**
https://github.com/ministryofjustice/cloud-platform/issues/1134
Test with e.g. `kubectl -n logging edit daemonset fluentd-es` and change the `image` with something invalid, this will kill just 1 pod as the daemonset will not continue with the change
> Fluentd smoketest

- helm-charts/fluentd-es/templates/daemonset.yaml
Fluentd containers on the master nodes are getting
OOM killed. This change increases the allowed
memory from 500Mi to 1000Mi to attempt to fix this
> Increase fluentd container memory resource limit

- smoke-tests/spec/fluentd_spec.rb
- smoke-tests/spec/kubernetes_helper.rb
This test currently fails in live-1, but passes on a test cluster, which is
expected because one fluentd container is currently CrashLoopBackoff
> Add a test that all fluentd containers are running

- smoke-tests/spec/kiam_helper.rb
This test calls list_roles. It started failing
because we (MoJ Digital) hit 100 roles in the AWS
account, which is the maximum number of roles we
can get in the response. 
This change keeps calling list_roles until all 
defined roles have been returned, which makes the
test pass again.
> Accomodate paginated list_roles responses

- smoke-tests/spec/fluentd_spec.rb
- smoke-tests/spec/kiam_helper.rb
- smoke-tests/spec/kubernetes_helper.rb
- smoke-tests/spec/logging_spec.rb
There were a variety of different ways of getting pod information from the
cluster, in this helper file. Some of these were hacky, some were just hard to
read.
This change rationalises these methods, so that they all work in roughly the
same way (grab all the pod data as JSON and dig into it for the bits you need).
This should make it easier to create new methods by composing existing ones, as
well as making it easier for people to see what's going on, when reading the
code.
> Tidy up the kubernetes_helper methods

- smoke-tests/spec/namespace_annotations_spec.rb
This was failing all test clusters that applied annotations via the cloud-platform-environment pipeline. By adding this cluster tag, we can ensure the test will only run against live-1
> Add live-1 tag to namespace annotation test

- terraform/cloud-platform-components/cert-manager.tf
**Why**
https://github.com/ministryofjustice/cloud-platform/issues/1161
**WARNING**: the repo has moved, but as we're not on the latest release we'll need to check 2 locations: 
https://github.com/helm/charts/tree/master/stable/cert-manager
and
https://hub.helm.sh/charts/jetstack/cert-manager
**HOWTO**
using the tools image, to ensure all the bits are in place
```
make tools-shell
kops export kubecfg <cluster>
helm ls cert-manager
helm repo add jetstack https://charts.jetstack.io
helm repo update
```
a `helm search cert-manager` must return results from both repos now, one 0.6 the other at 0.10
```
terraform apply --target=helm_release.cert-manager --target=null_resource.cert-manager-crds --target=null_resource.cert_manager_webhook_label
```
at this point, the chart deleted the LE …
> upgrade cert-manager

- terraform/cloud-platform-components/cert-manager.tf
**Why**
when running `terraform apply` on a null_resource, it will do a destroy/create; we need a smarted upgrade method
> do not delete CRDS

- terraform/global-resources/elasticsearch.tf
When applying audit-1 terraform I noticed that the current deployed status was 4 nodes.
> Make audit-1 cluster source code represent actual deployment

- helm-charts/fluentd-es/templates/daemonset.yaml
This change had no effect:
https://github.com/ministryofjustice/cloud-platform-environments/commit/b79fb5505fd3689613c813752aafdd2d23c11fcb#diff-16341c618c10e25b6523a3767819dc66
This is because values in the helm chart specify
resources for the fluentd containers, overriding
the namespace default values in the limitrange.
This change alters the resource requests and
limits for the logging containers to use values
which are more representative of how they run in
production.
After this change, the daemonset will need to be
redeployed using a targeted terraform taint &
apply
> Adjust resource request/limit for fluentd pods

- smoke-tests/spec/fixtures/modsec-integrationtest.yaml.erb
- smoke-tests/spec/fixtures/modsec-smoketest.yaml.erb
- smoke-tests/spec/kubernetes_helper.rb
- smoke-tests/spec/modsec_spec.rb
This integration test is for testing ModSecurity.
The test creates a namespace and a deployment with an ingress.
The ModSec annotations are added to the ingress (during deployment via yaml) so all traffic is inspected by Modsec before traffic can get to the application pod. 
The test tries to curl the URL with a 'exec=/bin/bash' which is classed as a level 5 malicious by ModSec.
The expected return from the test should be a '403 Forbidden'.
> Add ModSec Intergration Test

- helm-charts/fluentd-es/templates/daemonset.yaml
The change to 400Mi means that the total memory requested by the
logging namespace exceeds the 12G allowed, meaning some fluentd
pods are not running . We're not using that memory anyway, so
this is not helpful.
This commit puts the memory request per container back to the
previous value of 200Mi
> Reduce fluentd pods memory requests to 200Mi

- terraform/cloud-platform-components/templates/opa/values.yaml.tpl
What and Why:
Adding admission control restrictions to pod resource to restrict the kinds of operations and resources that are subject to OPA.
Next steps to:
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/396
Related to: https://github.com/ministryofjustice/cloud-platform/issues/1028
> Adding admission control for pods

- terraform/cloud-platform-components/opa.tf
What:
Adding opa namespace resource before deploying helm chart
Why:
The namespace opa should have labels added when deploying OPA through helm chart. This will avoid errors when creating test clusters.
For live-1, terraform apply would fail because the opa namespace already exists. A terraform import should be preformed as below
```terraform import kubernetes_resource.opa opa```
> Adding opa namespace resource and dependency

- create-cluster.rb
What:
Added script to find pagerduty_config and slack_webhook and replace with dummy values
Why:
To disable alerts when building test clusters by default.
> Add disable alerts

- terraform/cloud-platform-components/cert-manager.tf
We get cert-manager from the jetstack repository now (see commit
6681b514633c91703cabb51031cd4679aa7cb88c)
This means we need the jetstack helm repository, or we get failures like
this during the components install phase of creating a test cluster;
```
Error: Error applying plan:
1 error occurred:
* helm_release.cert-manager: 1 error occurred:
* helm_release.cert-manager: repo jetstack not found
```
This commit adds the helm repository, and uses it when installing
cert-manager.
Provider documentation is here:
https://www.terraform.io/docs/providers/helm/repository.html
fixes https://github.com/ministryofjustice/cloud-platform/issues/1267
> Add the jetstack helm repository, for cert-manager

- makefile
The tools image has been updated so that it can be
used to run the cluster integration tests:
https://github.com/ministryofjustice/cloud-platform-tools-image/pull/35
https://github.com/ministryofjustice/cloud-platform-tools-image/pull/36
This change uses the correct version of the tools
image in the `make tools-shell` target, so that
the build script will automatically run the
integration tests on new test clusters
> Update makefile to pull specific tools image tag

- smoke-tests/spec/constants.rb
- smoke-tests/spec/kiam_helper.rb
- smoke-tests/spec/kiam_spec.rb
After the kiam tests have finished, remove the cluster's nodes from the
role policy trust relationships.
This avoids a problem where, after a cluster is deleted, its ARN in the
trust relationships list is replaced with a malformed value (AWS does this
by itself).
Pre-emptively removing the cluster from the trust  policy means this won't
happen.
The exception is live-1. We never remove live-1 nodes from the list, which
means we don't have to worry about the list size dropping to zero,  which
would complicate things.
> Remove cluster nodes from role policy, after tests

- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
**Why**
We set the right values in the namespace
> remove limits from template

- terraform/cloud-platform-components/opa.tf
What and why:
Adding labels to kube-system so OPA ignore kube-system namespace from policy decisions.
> null_resource to add labels to kube-system

- terraform/cloud-platform-components/external-dns.tf
upgrade both chart and app version for external-dns
~ helm_release.external_dns
values.0:   image:
-  tag: v0.5.11
+  tag: 0.5.17-debian-9-r0
sources:
- service
- ingress
provider: aws
aws:
version:    "1.7.0" => "2.6.4"
This update required a taint and apply due to a known issue:
https://github.com/operator-framework/operator-lifecycle-manager/issues/952
> upgrade externals-dns to v0.5.17

- destroy-cluster.sh
This script destroys a test cluster by reversing the steps used to
create it.
It also deletes the prometheus_operator helm release first, because
it's common to have problems with this if it happens concurrently
with deleting the rest of the components.
Finally, the script clears up terraform workspaces.
This script is deliberately NOT written to take a cluster name
as a command-line parameter, as an extra safety measure.
> Add a script to cleanly destroy a (test) cluster

- terraform/cloud-platform-components/resources/prometheusrule-alerts/application-alerts.yaml
- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
The KubePersistentVolumeFullInFourDays rule is currently set to `critical`, meaning it will alarm out of hours. This change sends the default alert to null and adds the same rule to our own application alerts manifest sending all alerts to slack as a `warning`.
> Make 'KubePersistentVolumeFullInFourDays' rule warning not critical

- terraform/cloud-platform-components/templates/opa/values.yaml.tpl
Increase opa replicas to 2 to minimise downtime when pods are cycled.
> Increase opa replicas to 2

- smoke-tests/spec/namespace_spec.rb
**Why**
RBAC error message changed in release 1.13 of k8s
> small edit for changed RBAC error

- terraform/cloud-platform-components/nginx-ingress-acme.tf
This is related to https://github.com/ministryofjustice/cloud-platform/issues/1290
Upgrade ingress-controller to latest version
Chart version: 1.24.0
appVersion: 0.26.1
Removed $the_real_ip variable  as it was removed from template and default log_format from v0.26.0
> Upgrade ingress-controller to latest version

- smoke-tests/README.md
- smoke-tests/spec/modsec_spec.rb
There is a problem in the interaction between the latest version of
ingress-controller and mod_security. So, these tests need to be disabled
until this is resolved.
> Skip all mod_security tests

- smoke-tests/spec/fixtures/modsec-integrationtest.yaml.erb
The current set up causes the following error:
Error: exit status 1
2019/10/09 09:28:16 [emerg] 113#113: "modsecurity_rules" directive Rule id: 200000 is duplicated
in /tmp/nginx-cfg152497997:41944
The change below loads the modsecurity.conf file when the true flag is set to enable modsecurity and there is no need to reference is separately.
https://github.com/kubernetes/ingress-nginx/pull/4080/files.
The current setup also breaks ingress-controllers and they can not be recycled.
> Remove file ModSecurity.conf file load

- terraform/cloud-platform-components/resources/prometheusrule-alerts/Custom-Alerts.md
- terraform/cloud-platform-components/resources/prometheusrule-alerts/application-alerts.yaml
- terraform/cloud-platform-components/resources/prometheusrule-alerts/node-alerts.yaml
Alarm to notify in high-priority channel if the nginx config is unable to reload for more than 30 seconds on any of the ingress-controller pods.
The ability to not reload nginx config makes nginx unstable and unable to update anything connected to ingress on the cluster.
Added docs on how to start investigation/info gathering if this alarm triggers.
> Add high-priority alert for nginx config reload failure

- kops/live-1.yaml
This was missed during the last upgrade under 4e75a292587c2ba7d19c3737b22ae621dad3bc7c. Nothing will actually change when this is merged.
> Update live-1 manifest to reflect actual state

- smoke-tests/spec/crds_spec.rb
- smoke-tests/spec/kubernetes_helper.rb
- smoke-tests/spec/servicemonitors_spec.rb
Related to: https://github.com/ministryofjustice/cloud-platform/issues/1299
Smoke tests to check expected Custom Resource Definitions(CRDs) and ServiceMonitors are available.
This test expects below CRDs,
` "alertmanagers.monitoring.coreos.com",
"certificates.certmanager.k8s.io",
"challenges.certmanager.k8s.io",
"clusterissuers.certmanager.k8s.io",
"issuers.certmanager.k8s.io",
"orders.certmanager.k8s.io",
"prometheuses.monitoring.coreos.com",
"prometheusrules.monitoring.coreos.com",
"servicemonitors.monitoring.coreos.com",
"tzcronjobs.cronjobber.hidde.co",`
And below ServiceMonitors
`"prometheus-operator-alertmanager",
"prometheus-operator-apiserver",
"prometheus-operator-grafana",
"prometheus-operator-kube-controller-manager",
"prometheus-operator-kube-dns", …
> Add Integration test for CRDs and ServiceMonitors

- terraform/cloud-platform/kops.tf
- terraform/cloud-platform/templates/kops.yaml.tpl
- terraform/cloud-platform/variables.tf
Instead of hard-coding EC2 instance types into
the kops config template, this change moves them 
to terraform variables.
This change by itself will not alter anything, but
it's a pre-requisite for the next change to the 
ruby script which builds test clusters. That 
change will alter the invocation of the terraform
apply step, to supply different machine type
values, so that we can build different sizes of
test cluster.
> Move node machineType to terraform variables

- terraform/global-resources/elasticsearch.tf
**Why**
We had repeated errors `could not push logs to Elasticsearch cluster: read timeout reached`
> bigger live ES nodes

- terraform/cloud-platform-components/nginx-ingress-acme.tf
WHAT
Validation webhook for nginx to make sure syntax is correct before applying to nginx config on ingress-controllers
WHY
An invalid syntax breaks nginx which affects all ingresses on cluster until resolved.
MORE INFORMATION
The Validating webhook must be served using TLS, you need to generate a certificate. This is what the 'patch' section of the chart does.
https://kubernetes.github.io/ingress-nginx/deploy/validating-webhook/
https://github.com/helm/charts/tree/master/stable/nginx-ingress (controller.admissionWebhooks.enabled section)
> Add nginx validation webhook for Syntax

- terraform/cloud-platform-components/nginx-ingress-acme.tf
**Why**
Whenever the filed is not a numeric value, nginx does not put in 0/1 but leaves an unfinished `:` that breaks the json parser
> remove compression rate from log

- terraform/cloud-platform-components/nginx-ingress-acme.tf
**Why**
named ports show up as defined string not `80`
> change nginx port field log type

- smoke-tests/spec/modsec_spec.rb
WHAT
Re-enable the modsec integration test 
WHY
This test was disabled after an ingress-controller upfate, the test required changes to how modsecurity worked. The changes were made previously (https://github.com/ministryofjustice/cloud-platform-infrastructure/commit/3a6935aed4ba1fbfdb7f4b63ccb80f81dd0b76e5), but more testing was required before adding back in.
> Re-enable ModSec integration test

- terraform/cloud-platform-components/resources/cloudwatch-exporter.yaml
WHAT
Add more metrics points and resources to export from Cloudwatch to Prometheus:
- rds,sqs,sns,elasticache redis,dynamoDB,awsmq.
WHY
Users will be able to create/monitor resrouces created in AWS using Prometheus rules and do not require direct access to aws via the console. 
INFO
update exporter version from 0.5.0 to 0.6.0
> Add more AWS resources metrics export to Prometheus

- terraform/cloud-platform-components/resources/prometheusrule-alerts/node-alerts.yaml
Nginx config can fail to reload under certain circumstances, however it is able to resolve itself within a few seconds also. This increase is so that we do not get out of ours alerts if the alert is able to resolve itself. The wait time is now 1 minute instead of 30 seconds.
> Increase wait time to 1 minute for nginx reload alert

- terraform/cloud-platform-components/prometheus.tf
The installation of prometheus operator fails the first time, when
we build a test cluster.
Error: Error applying plan:
1 error occurred:
* helm_release.prometheus_operator: 1 error occurred:
* helm_release.prometheus_operator: rpc error: code = Unknown
desc = release prometheus-operator failed: Internal error occurred:
failed calling webhook "validate.nginx.ingress.kubernetes.io": Post
https://nginx-ingress-acme-controller-admission.ingress-controllers.svc:443/extensions/v1beta1/ingresses?timeout=30s:
dial tcp 100.71.204.116:443: connect: connection refused
I think this is because the admission webhook is not ready when
the installation happens.
This change adds a dependency, so that terraform doesn't try to
install prometheus operator before the webhook is in place.
I've run the cluster …
> Add dependency on ingress-controllers

- terraform/cloud-platform/bastion.tf
- terraform/cloud-platform/kops.tf
- terraform/cloud-platform/main.tf
- terraform/cloud-platform/outputs.tf
- terraform/cloud-platform/variables.tf
- terraform/cloud-platform/versions.tf
- terraform/modules/aws_federation/iam_federation.tf
- terraform/modules/aws_federation/iam_roles.tf
- terraform/modules/aws_federation/outputs.tf
- terraform/modules/aws_federation/variables.tf
- terraform/modules/aws_federation/versions.tf
- terraform/modules/cluster_dns/dns.tf
- terraform/modules/cluster_dns/outputs.tf
- terraform/modules/cluster_dns/variables.tf
- terraform/modules/cluster_dns/versions.tf
- terraform/modules/cluster_ssl/acm.tf
- terraform/modules/cluster_ssl/outputs.tf
- terraform/modules/cluster_ssl/variables.tf
- terraform/modules/cluster_ssl/versions.tf
This is related to https://github.com/ministryofjustice/cloud-platform/issues/1368
Upgraded cloud-platform in cloud-platform-infrastructure to tfv0.12.13.
Performed tf 0.12upgrade on below:
terraform/cloud-platform
module aws_federation
module cluster_dns
module cluster_ssl
Upgraded auth0 version to 0.2.1
Updated cluster_vpc module version to 2.18.0
> Tf12 upgrade cloud platform

- terraform/cloud-platform-components/resources/cloudwatch-exporter.yaml
- Reducing the AWS resource metrics for RDS, SNS, SQS, DynamoDB, MQBroker and ElasticCache to minimum required to Cloudwatch exporter.
- Adding Elasticsearch metrics to minimum required to Cloudwatch exporter.
> Limit AWS resources metrics and add ES metrics

- terraform/global-resources/auth0.tf
- terraform/global-resources/dns.tf
- terraform/global-resources/elasticsearch.tf
- terraform/global-resources/guardduty.tf
- terraform/global-resources/main.tf
- terraform/global-resources/outputs.tf
- terraform/global-resources/s3.tf
- terraform/global-resources/saml.tf
- terraform/global-resources/variables.tf
- terraform/global-resources/versions.tf
This is related to https://github.com/ministryofjustice/cloud-platform/issues/1367
Updated terraform/global-resources to tf0.12
-> Fix tf0.12 upgrade provider issue in guardduty.tf by adding an alias, as tf0.12 upgrade failed with below error
Error: panic: missing schema for provider type "aws.member"
-> Run tf0.12upgrade command to get global-resources to tf0.12
-> Fix tf0.12 Err Incorrect attribute value type in elasticsearch.tf by removing []
-> Pinned auth0 version in the auth0 provider
> Tf12 upgrade global resources

- terraform/cloud-platform-account/cloudtrail.tf
- terraform/cloud-platform-account/cloudwatch_events.tf
- terraform/cloud-platform-account/dlm.tf
- terraform/cloud-platform-account/main.tf
- terraform/cloud-platform-account/variables.tf
- terraform/cloud-platform-account/versions.tf
This is related to https://github.com/ministryofjustice/cloud-platform/issues/1366
Updated terraform/cloud-platform-account to tf0.12.
--> Ran tf 0.12upgrade command to get cloud-platform-account changed to tf0.12
--> To fix the issue with module "cloudwatch_slack" updated the module to use version = "~> 2.0", which is created for tf0.12.
> Tf12 upgrade cloud platform account

- destroy-cluster.sh
- makefile
Now that we have upgraded infrastructure and
components to terraform 0.12, the 0.11 version of
terraform will not destroy test clusters.
This change fixes that.
> Use terraform12 to destroy test clusters

- .circleci/config.yml
We use the code-formatter github action for this, which is able
to work with terraform 0.12 or 0.11 syntax. So, rather than fix
this action to do the same thing correctly, it makes more sense
to remove the terraform steps from this job, and leave that part
to the github action.
> Remove the terraform validation & formatting steps

- create-cluster.rb
We want to replace the pagerduty token and all
slack webhooks in test clusters, so we run a `sed`
command on the terraform source to replace those
values with `dummydummy`
But, because the code is executed via ruby, we
need to escape every backslash by doubling it
(i.e. wherever you put `\` in bash, e.g. when
running the command a terminal, you need to put
`\\` in your ruby code.
I think this is why we've still been getting 
alerts from our test clusters.
> Bugfix: correct the command which disables alerts

- create-cluster.rb
Now that we have updated our terraform code to
0.12 syntax, the cluster build script also has to
be updated.
> Use terraform12 for the cluster build script

- create-cluster.rb
- makefile
We don't need to use `terraform12` anymore.
> Use `terraform` in the cluster build script

- recycle-node.rb
This is a pre-requisite for https://github.com/ministryofjustice/cloud-platform/issues/1467
Draining a node can fail for various reasons. When this happens, the drain
command loops forever (or, at least for longer than I was prepared to wait,
during testing).
This commit adds a timeout to the node drain step, so that we only wait a
fixed amount of time before giving up (and killing the spawned `kubectl`
process).
> Add a timeout to the node drain step

- destroy-cluster.sh
This change updates the cluster destroy script to invoke
terraform 0.12.13 as `terraform` instead of `terraform12`
> Use `terraform` instead of `terraform12`

- smoke-tests/spec/kiam_helper.rb
This error happens after test clusters are destroyed, leaving their
entry in the list of entities trusted by the test role.
This change adds detailed instructions on how to clear up this
problem by deleting the leftover entries in the list.
> Add a note on fixing "Invalid principal in policy"

- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
It was done a volume resize in live-1 to 750GB, this PR represents the change in components
> Updated default PVC size to match live-1.

- recycle-node.rb
We log all commands we execute, as part of this script, unless we
are executing them with a timeout. This commit adds logging to the
`exec_with_timeout` method, so that we can see those commands in
the concourse web interface.
> Log commands which are executed with a timeout

- terraform/cloud-platform/templates/kops.yaml.tpl
This additional label with add a unique key in the tag used to identify resourced created in AWS by kops for specific clusters.
Currently all tags have the same key and are identifiable by the value of the key.
The cluster-autoscaler has an auto-discover mechanism which looks to unique keys and ignores the values.
> Add unique key for tag for AWS resources created by kops

- terraform/cloud-platform-components/metrics-server.tf
- upgraded metrics-server from `2.0.4` to `2.8.8`
- moved the metrics-server deployment from `kube-system` to the `monitoring` namespace
> Metrics server uprade

- kops/live-1.yaml
- terraform/cloud-platform/variables.tf
This changes the worker nodes from r5.2xlarge to r5.xlarge
This change should still leave plenty of extra capacity to accomodate some
growth, while saving the MoJ almost $5,000/month in AWS hosting costs.
NB: After merging this change, we need to do a kops update and rolling
update of the cluster, before the change takes effect.
> Reduce live-1 worker node instance size

- kops/live-1.yaml
- terraform/cloud-platform/templates/kops.yaml.tpl
The last time we changed the cluster, we increased the node size to
r5.2xlarge by creating a new instancegroup called nodes-r52xl and then
deleting the old instancegroup called "nodes"
At that time, we didn't update the yaml file in the github repo.
This change is required so that we can resize the worker nodes via a kops
rolling-update
Clearly, this instancegroup name will be wrong after the resize, however
it's the only way to use a rolling-update to do the resize, so we'll have
to live with it, for now.
> Correct the instancegroup name to nodes-r52xl

- recycle-node.rb
The live-1 worker nodes are in the nodes-r52xl instancegroup.
> Correct the worker nodes instancegroup name

- create-cluster.rb
live-1 worker nodes are now r5.xlarge, not r5.2xlarge
> Fix worker node size of 'production' test clusters

- terraform/cloud-platform-components/variables.tf
This commit silences the following deprecation
warning, when applying the components terraform
code:
```
Warning: Quoted type constraints are deprecated
on variables.tf line 7, in variable "alertmanager_slack_receivers":
7:   type        = "list"
```
> Silence a terraform deprecation warning

- terraform/cloud-platform-account/dlm.tf
This policy will take a snapshot of volume which is tagged as,
"k8s.io/pvc/persistentvolume" = "1"
This policy will run every day at 5:00 AM, and will retain 30days.
> Created persistentvolume_backup policy

- terraform/cloud-platform-account/dlm.tf
This is because users can't use this policy as PVC created by users,
cannot add tags that can pass to the PV.
> Remove dlm policy for persistentvolume_backup

- terraform/global-resources/main.tf
- terraform/global-resources/s3.tf
WHAT
Create S3 bucket for Velero backups
WHY
This bucket will store all backups from all clusters under each clusters prefix folder
> Create S3 bucket for Velero backups

- smoke-tests/spec/servicemonitors_spec.rb
An integration test was already in place to ensure the essential SM existed in the cluster.
This PR add the test of the velero service monitor.
Tested
> add servicemonitor check for velero

- terraform/cloud-platform-components/templates/velero/velero.yaml.tpl
- terraform/cloud-platform-components/velero.tf
WHAT
Add Velero backup to cloud-platform-components to install as parr of new cluster creation
WHY
Velero backup gives you tools to back up and restore your Kubernetes cluster resources and persistent volumes
> Add Velero Backup to cloud-platform-components

- smoke-tests/spec/kubernetes_helper.rb
- smoke-tests/spec/prometheus_crd_spec.rb
This PR introduces a test to ensure that the essential Prometheus (prometheuses.monitoring.coreos.com) resources are there.
> prometheuses.monitoring.coreos.com check

- terraform/cloud-platform-components/resources/prometheusrule-alerts/application-alerts.yaml
Added 2 alerts in application alerts for Velero:
1. Alert if there is a backup failure for any schedule
2. The 'AllNamespaceBackup' runs every 3 hours and currently takes an average of 2 minutes to run. This alert will trigger is there is not a successful timestamp for this schedule for over 4 hours. 
Both alerts will go into low-priority slack channel
> Add alerts for Velero backup

- smoke-tests/spec/alertmanager_spec.rb
- smoke-tests/spec/kubernetes_helper.rb
This PR introduces an integration test that ensures the relevant `alertmanager` (alertmanagers.monitoring.coreos.com) resources (!=CRD) exist.
Works with production and test clusters.
> alertmanagers.monitoring.coreos.com spec

- smoke-tests/spec/servicemonitors_spec.rb
This PR adds ECR and CloudWatch integration tests, which is basically check their ServiceMonitor resources are deployed. 
More information in [#1309](ministryofjustice/cloud-platform#1309)
> ECR and CloudWatch ServiceMonitor tests

- smoke-tests/spec/authorized_keys_spec.rb
This PR closes [#1358](ministryofjustice/cloud-platform#1358). 
It includes smoke tests to check `authorized-keys-provider` namespace exists, it has all pods running and the authorized_keys file exists within S3 bucket.
> Smoke tests for authorized_keys

- smoke-tests/spec/servicemonitors_spec.rb
Smoke-tests for ServiceMonitor (ECR and CloudWatch) for live-1. They should only apply for live-1
> ECR and CloudWatch ServiceMonitor must exist only for live-1

- helm-charts/fluentd-es/templates/prometheusrule.yaml
This PR adds a `prometheusrule.yaml` file into the Fluentd helm chart.
This resource is currently defined in the environment repo, under the logging namespace.
Once this is merged in, this resource can will be removed.
> Move Fluentd PrometheusRule into Helm chart

- smoke-tests/spec/prometheusrules_spec.rb
This PR ensure some prometheus rules are only expected when testing against live-1.
> Live-1 only for the ECR prometheusrule test

- terraform/cloud-platform-components/fluentd.tf
When building a cluster, I got this error:
Error: rpc error: code = Unknown desc = validation failed: unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1"
on fluentd.tf line 20, in resource "helm_release" "fluentd_es":
20: resource "helm_release" "fluentd_es" {
2020-01-02 09:50:46 Cluster components failed to install. Aborting.
I think this is because fluentd needs the PrometheusRule CRD, and
it wasn't there when it tried to install.
After adding this line, I tried another fresh cluster build, and it
worked fine. That's not definitive proof that this fix is required, but
it's a good sign, and does confirm that, at worst, this fix does no
harm.
> Add dependency on prometheus operator from fluentd

- smoke-tests/spec/docker_registry_cache_spec.rb
- smoke-tests/spec/kubernetes_helper.rb
- terraform/cloud-platform-components/docker-registry-cache.tf
- terraform/cloud-platform-components/templates/docker-registry-cache/docker-registry-cache.yaml.tpl
- terraform/cloud-platform-components/templates/docker-registry-cache/namespace.yaml
- terraform/cloud-platform/outputs.tf
- terraform/cloud-platform/templates/kops.yaml.tpl
closes https://github.com/ministryofjustice/cloud-platform/issues/1443
This PR deploys an instance of docker registry into the cluster, configured as
a pull-through cache (https://docs.docker.com/registry/recipes/mirror/).
To do this, we create a `docker-registry-cache` namespace, with a deployment
running a single replica of the registry. A health check is used to limit the
amount of disk space the cache consumes. Once the amount of disk space used in
the container exceeds a threshold, the health check will fail and the pod will
be terminated and replaced.
The worker nodes of the cluster are configured to use the registry mirror by
specifying a `registryMirrors` entry pointing to the ingress' public URL.  If
the registry is not available, the dockerd instance on the worker nodes will …
> Deploy a docker registry as a pull-through cache

- kops/live-1.yaml
The latest terraform code adds
`spec.docker.registryMirrors` to the node config.
This commits those changes to the live-1 kops
config file.
> Commit changes to kops config after tf apply

- smoke-tests/spec/docker_registry_cache_spec.rb
The test which confirms that the docker registry cache is actually
being used by the cluster worker nodes is failing intermittently
on live-1.
This change increases the sleep delay between pulling an image and
checking that the cache logged some output from 1 to 5 seconds, to
try and make this test more reliable.
> Increase wait time for cache log output

- terraform/cloud-platform-components/docker-registry-cache.tf
- terraform/cloud-platform-components/main.tf
- terraform/cloud-platform-network/main.tf
- Components: New data resource pointing to networking terraform remote state, it allows docker registry cache to get nat_ips output
- Network folder have tags based on workspace
> Components fix and network tags using workspace name as cluster name

- smoke-tests/spec/docker_registry_cache_spec.rb
related to #525
Increasing the delay from 1s to 5s in #525 improved the reliability
of the test, but it's still failing occasionally. This change bumps
the sleep delay from 5s to 10s to try and get the test passing
reliably.
> Increase the delay for cache logging test

- smoke-tests/spec/external_dns_spec.rb
This commit adds a comment explaining how to fix a common failure in the
external-dns specs.
> Add how to fix external-dns spec failure

- create-cluster.rb
The latest version of bundler, which is installed
on the fly during the cluster build process, works
differently wrt. the executables provided by gems
(e.g. the `rspec` command provided by the `rspec-
core` gem).
This change ensures that the integration tests run
correctly at the end of the cluster build script.
> Update cluster build wrt. bundler

- terraform/cloud-platform-network/main.tf
- terraform/cloud-platform-network/variables.tf
When new clusters are deployed inside a VPC, AWS creates some tags inside all subnets the clusters are going to use. 
The new tags created are not going to be inside the terraform code because they were not initially. there In order to support a consistent state in the terraform plan/apply the `module.vpc` has to support tags as terraform variables.
> Setting clusters within the VPC as terraform variables

- terraform/cloud-platform-components/docker-registry-cache.tf
The docker-registry-cache namespace is defined in a kubernetes_namespace
resource which had the identifier "docker_registry_cache"
This was confusing the orphaned namespace checker, which reports that
the "docker-registry-cache" namespace is not defined in our source code.
Changing the identifier to match the namespace name should resolve this
problem (assuming terraform will allow an identifier with hyphens in
it).
> Change the ID of a namespace resource

- smoke-tests/spec/cert_manager_spec.rb
Changing random_string to readable_timestamp means we will be
able to easily determine the age of a test namespace, whenever any
get leftover in the cluster.
> Use timestamp in cert. manager test namespace name

- terraform/cloud-platform-components/prometheus.tf
- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
Related to https://github.com/ministryofjustice/cloud-platform/issues/1489
- add AlertManager route and receiver for notifications. 
- add label `status_icon` for prometheus rules to change the message icon to information type.
> Add AlertManager slack integration for notification/information type events

- smoke-tests/spec/cert_manager_spec.rb
- smoke-tests/spec/external_dns_helper.rb
- smoke-tests/spec/kiam_helper.rb
- smoke-tests/spec/kubernetes_helper.rb
- smoke-tests/spec/namespace_spec.rb
If we're running in the concourse pipeline, add a 1-second delay before
every executed command, so  that we don't flood the kubernetes API and
cause KubeAPILatencyHigh alerts
> Add a 1-second delay to all calls, in pipeline

- smoke-tests/spec/kubernetes_helper.rb
We're still getting KubeAPILatencyHigh alerts when running the
tests in the pipeline. So, try a higher delay, to see if that
works around the problem.
> Increase call delay from 1 to 2 seconds for tests

- smoke-tests/spec/kubernetes_helper.rb
With a 2 second delay, we're still getting a few KubeAPILatencyHigh
alerts.
This change increases the delay to 3 seconds, before each command
is sent. If this doesn't work, we may need a different approach
to fix the problem.
> Increase call delay to 3 seconds, for tests

- terraform/cloud-platform-components/resources/prometheusrule-alerts/application-alerts.yaml
Added 4 alerts to Prom Rules
2 Alerts for notifications for any full or partial failure of any backup schedule
2 alerts for the velero-fullnamepsacebackup schedule, to notify for either a full or partial backup failure in the past 3 hours, as this schedule runs every 3 hours. If the next backup run is successful, if the alert will resolve. 
To resolve this alert earlier, you can delete the failed backup running:
`velero delete backup <backup name>`
> Add Velero backup failure alerts

- smoke-tests/spec/tzcronjob_spec.rb
related to
https://github.com/ministryofjustice/cloud-platform/issues/1618
This test fails on test clusters, but passes on live-1.
We don't know why.
> Tag the tzcronjob test as live-1 only

- smoke-tests/spec/kiam_helper.rb
This comment provides a solution to a common error case, where
leftover IAM records break the setup of some KIAM tests.
This commit adds the specific type of the error, in case the user
searches for that, rather than "Invalid principal..."
> Add the AWS error message to kiam helper comment

- smoke-tests/spec/kubernetes_helper.rb
We have started seeing KubeAPILatencyHigh errors again, although
they seemed to have more or less stopped after we added this delay.
They started again after we moved the integration test pipeline to
the manager cluster concourse instance.
This commit is a temporary change to 100% confirm that the sleep
delay is still happening, in the new pipeline.
> Log whenever the tests sleep, for the pipeline

- terraform/cloud-platform-components/metrics-server.tf
Move metrics server back to  kube-system from monitoring NS.
This is due to metrics-server requiring access to configmap extention-apiserver-authentication on kube-system which is not possible when restoring metrics-server using Velero.
> Move metrics-server to kube-system

- smoke-tests/spec/kubernetes_helper.rb
This reverts commit 9bc7804e306d26ff31a845d7ba7a57806b17fe5d.
The sleep is definitely happening, so we don't need this extra
logging anymore.
> Revert "Log when tests sleep, for the pipeline"

- terraform/cloud-platform-eks/eks.tf
This allows the concourse user full access over our manager cluster, which is required to create namespaces and secrets.
> Add concourse user to manager cluster

- smoke-tests/spec/kubernetes_helper.rb
This is to get data to correlate the commands which the tests
execute and the incidence of KubeAPILatencyHigh alerts.
> Log all executed commands, with a timestamp

- create-cluster.rb
- terraform/cloud-platform-components/prometheus.tf
- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
Upgrade prometheus-operator chat version to 7.4.0 (later new PR to upgrade it to 8.7.0)
->    To uprade to latest version 8.7.0, there is dependency, upgrading to latest version of 7.x.x
https://github.com/helm/charts/tree/master/stable/prometheus-operator#upgrading-from-7xx-to-8xx
->    Set force_update = "true" , to avoid error which will occur indicating that the deployment cannot be modified
https://github.com/helm/charts/tree/master/stable/prometheus-operator#upgrading-from-5xx-to-6xx
->    data "template_file" for  "prometheus_operator" moved to values as like EKS components
-> Updated prometheus-operator.yaml.tpl, this is inline with the latest chart version 8.7.0
-> Fix create-cluster.rb to replace slack hook as URL, as there is validation in latest alert-manager at config load …
> Prometheus upgrade 8xx

- smoke-tests/spec/error_page_spec.rb
Skipping error page test due to causing high api latency error. Will remove test if this is confirmed and look into a int test for error pages again at a later date .
> Skipping error page test

- terraform/cloud-platform-components/prometheus.tf
- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
Prometheus upgrade to latest chart version 8.7.0
Updated prometheus-operator.yaml.tpl
->  Set admissionWebhooks to false, as this is causing error
Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prometheus-operator-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
->    Set kubeControllerManager and kubeScheduler to false, as they are not available in our cluster, which is causing high priority alerts.
->    Added any: true for ruleNamespaceSelector, serviceMonitorSelector, ruleSelector, serviceMonitorNamespaceSelector, this is to get alertmanager to not look for particular labels
> Prometheus upgrade latest

- smoke-tests/spec/kubernetes_helper.rb
We have disabled the error page integration tests, because we
think they're responsible for the "KubeAPILatencyHigh" alerts we
often receive when the tests are running.
As such, this additional sleep delay should not be necessary, so
this commit removes it.
An additional commit will remove the environment variable from the
integration tests concourse pipeline.
> Remove the sleep delay when running via pipeline

- terraform/global-resources/iam/main.tf
Having IAM using terraform allow us to have 'as a code' advantages:
-  Track changes within AWS IAM Services
- Encourage changes through PR and peer-reviews.
- Notify when changes happen (adding a divergence concourse pipeline later on)
- etc (history changes, congruent state, etc, etc)
Importing existing resources into terraform state using `terraform import`, so we're able to avoid create -> destroy 
Real Example:
```console
$ terraform import 'module.iam_user_alejandrogarrido.aws_iam_user.this[0]' AlejandroGarrido
module.iam_user_alejandrogarrido.aws_iam_user.this[0]: Importing from ID "AlejandroGarrido"...
module.iam_user_alejandrogarrido.aws_iam_user.this[0]: Import prepared!
Prepared aws_iam_user for import
module.iam_user_alejandrogarrido.aws_iam_user.this[0]: Refreshing state... …
```
> Added IAM terraform definition

- smoke-tests/spec/servicemonitors_spec.rb
This is because concourse is now moved to EKS cluster
> Removed concourse servicemonitor test

- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
We need to keep `kube-state-metrics` in an older version because some required metrics used by us and our teams were deleted in the recent versions
> Added kube-state-metrics custom image tag

- terraform/cloud-platform-components/main.tf
This is because latest provider version 1.0 is compatible for helm3 and we are still using helm2
https://github.com/terraform-providers/terraform-provider-helm#%EF%B8%8F-project-update-helm-3
> Pin helm provider version to "0.10.4"

- makefile
Now that we have both EKS and KOPS clusters, it's convenient to
have a single command that will list all of our clusters.
This command will only work for Cloud Platform team members, who
have the required AWS credentials.
> Add `make list-clusters` to show all clusters

- smoke-tests/spec/tzcronjob_spec.rb
This PR disables the tzcronjob integration-test, which is unreliable.
`describe` ->`xdescribe`
> Disable the tzcronjob test

- terraform/cloud-platform-components/prometheus.tf
- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
Added cloudwatch datasource for grafana, with auth type arn using assume role
ref:https://grafana.com/docs/grafana/latest/features/datasources/cloudwatch/#configure-the-data-source-with-provisioning
Assume role policy for grafana datasource cloudwatch
Added minimal policy permissions
ref:https://grafana.com/docs/grafana/latest/features/datasources/cloudwatch/#iam-policies
Added grafana pod annotation for assume role
In addition, added assume role for role to fix Error: kiam-kiam is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::754256621582:role/
Open issue related to the arn authentication 
https://github.com/grafana/grafana/issues/19173
> Grafana cloudwatch datasource

- smoke-tests/spec/docker_registry_cache_spec.rb
This test intermittently fails when running in the integration test
pipeline. This commit increases the sleep delay from 10 to 20
seconds, to try and make the test more consistent.
> Increase docker-registry-cache test sleep delay

- terraform/cloud-platform-components/main.tf
- terraform/cross-account-IAM/iam-money-to-prisoners.tf
- terraform/cross-account-IAM/main.tf
This PR is to allow access for pods in Cloud Platform cluster to assume role to access a cross-account resources.
All files related to this are placed in infrastructure repo to ensure the code is applied when appropriate.
> Add cross account IAM role creations

- terraform/cross-account-IAM/iam-money-to-prisoners.tf
Service team wants to assumeRole from their app in their namespace and hence the role created should have a policy to allow `assumeRole` for the created role itself.
> Update policy so the role has permissions to perform assumeRole

- terraform/cloud-platform-components/main.tf
- terraform/cloud-platform-eks/components/main.tf
- terraform/cloud-platform-eks/eks.tf
Pin kubernetes provider version to 1.10.0
Error: Failed to initialize config: invalid configuration:
no configuration has been provided
https://github.com/terraform-providers/terraform-provider-kubernetes/issues/759
Pin helm provider version to "0.10.4"
As latest version is not compatible for helm2
> Pin version kubernetes

- smoke-tests/spec/kubernetes_helper.rb
This reverts commit 4d0bc44c5f24d64eb7c43c9446f6cf4a9b2cc836.
It seems that the integration tests send a lot of AWS API calls,
particularly to the route53, where we have an API requests/second
limit (of 7, a global limit we can't alter).
This change reinstates the sleep delay between every command that
the tests execute, to reduce the chances of the integration tests
pushing us over that limit again.
> Revert "Remove sleep when running via pipeline"

- .gitattributes
In order to avoid publishing all our CP Team usernames in AWS we decided to encrypt the `EKS.tf` file.
This ticket closes [#1622](https://github.com/ministryofjustice/cloud-platform/issues/1622)
> Encrypting EKS.tf 

- terraform/cloud-platform-components/velero.tf
If prometheus does not install correctly, we get the following
error when terraform tries to install velero:
Error: rpc error: code = Unknown desc = validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
on velero.tf line 82, in resource "helm_release" "velero":
82: resource "helm_release" "velero" {
This change makes velero depend on prometheus, so that terraform
won't try to install velero until prometheus is installed.
> Add a dependency on prometheus to velero

- terraform/cloud-platform-components/templates/prometheus-operator.yaml.tpl
Prometheus-operator helm chart deletes CRDs when you delete the chart itself. We do want to avoid it.
The reason to avoid it is quite simple: we don't want to lose already existing ServiceMonitor and PromtheusRules
> We don't want to delete the prometheus CRD when we delete the prometheus-operator

- smoke-tests/spec/kubernetes_helper.rb
- smoke-tests/spec/namespace_labels_spec.rb
This test checks that the `kube-system` namespace has
the "openpolicyagent.org/webhook" label set to "ignore"
> Add a test for the OPA label on kube-system

- smoke-tests/makefile
- smoke-tests/spec/alertmanager_spec.rb
- smoke-tests/spec/authorized_keys_spec.rb
- smoke-tests/spec/certificates_spec.rb
- smoke-tests/spec/crds_spec.rb
- smoke-tests/spec/daemonsets_spec.rb
- smoke-tests/spec/docker_registry_cache_spec.rb
- smoke-tests/spec/issuers_spec.rb
- smoke-tests/spec/namespace_annotations_spec.rb
- smoke-tests/spec/prometheus_crd_spec.rb
- smoke-tests/spec/prometheusrules_spec.rb
- smoke-tests/spec/servicemonitors_spec.rb
These tests can be run more frequently to get a  quick and incomplete check
of the cluster state.
On my machine, running natively (i.e. not inside a tools image container),
these tests complete in 21 seconds.
rspec --tag speed:fast
> Enable running just the quick cluster tests

- destroy-cluster.sh
This is because, prometheus is moved to a new module
> Update delete cluster script

- create-cluster.rb
In order to create the build-test-clusters pipeline, some extra functionalities `create-cluster.rb` script had to be added:
- Make the `git-crypt unlock` optional: When it is executed from the concourse pipeline the repository is already unlocked.
- Make integration tests optional: all of them are failing and for test clusters it looks it is expected
- Optional time (argument in seconds) between cluster validation (kops validate) and components deployment (`terraform apply` inside components folder). We were experimenting failing DNS resolutions and it looks it wasn't fully propagated the DNS API at the moment when components were deployed.
> Extend abilities of cluster-creation script

- kops/live-1.yaml
This was causing the kops-convergence pipeline to fail.
> Removed unwanted tab from live-1 manifest

- create-cluster.rb
If we don't default value is fails with:
```console
Traceback (most recent call last):
2: from ./create-cluster.rb:303:in `<main>'
1: from ./create-cluster.rb:60:in `main'
./create-cluster.rb:60:in `sleep': can't convert NilClass into time interval (TypeError)
```
> Set extra_wait default value to 0

- makefile
This image contains a later version of the kubectl binary, which allows additional features such as  as a shorthand among other things.
> Bump tools image to 1.13 in makefile

- terraform/cloud-platform/outputs.tf
We don't want important information to be shown in pipeline outputs, specially auth0 secret keys. When we define an output as sensitive it doesn't show it
> Set Auth0 client secret as sensitive terraform output

- terraform/cloud-platform-components/prometheus.tf
In order to include Thanos sidecar in our Prometheus we need to bump the Prometheus module we need to bump the version of the module to 0.0.5
> Bumping prometheus module to the latest release

- terraform/cloud-platform-starter-pack/main.tf
- terraform/cloud-platform-starter-pack/starter-pack.tf
- terraform/cloud-platform-starter-pack/templates/helloworld-rubyapp/deploy.yaml
- terraform/cloud-platform-starter-pack/templates/multi-container-app/deploy.yaml
- terraform/cloud-platform-starter-pack/templates/multi-container-app/pg-deploy.yaml
- terraform/cloud-platform-starter-pack/versions.tf
Related to [https://github.com/ministryofjustice/cloud-platform/issues/1631](https://github.com/ministryofjustice/cloud-platform/issues/1631)
This terraform code when applied will create a namespace "starter-pack" and deploy the [helloworld-app](https://github.com/ministryofjustice/cloud-platform-helloworld-ruby-app) and [Multi container app](https://github.com/ministryofjustice/cloud-platform-multi-container-demo-app) with postgres database running in a container.
> Add helloworld app and Multi container app for starter pack

- smoke-tests/spec/prometheusrules_spec.rb
Because of the Kubernetes upgrade some of the conditions within Prometheus Operator helm chart made to drift in the rules names which is causing integration tests to fail.
From the Helm Chart it was deleted the rule `prometheus-operator-kube-prometheus-node-alerting.rules`, [this rule only had disk space checks](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/rules/kube-prometheus-node-alerting.rules.yaml#L25-L40) which is already being [implemented by the Cloud Platform team in our custom rules](https://github.com/ministryofjustice/cloud-platform-terraform-prometheus/blob/master/resources/prometheusrule-alerts/node-alerts.yaml#L12-L19)
> Updated Integration tests to match new PrometheusRules for K8S >= 1.14

- smoke-tests/spec/prometheusrules_spec.rb
These rules are not present in the cluster anymore or they were renamed
> Removed PrometheusRules not present in the cluster anymore

- terraform/cloud-platform-eks/components/main.tf
The latest version of the kubernetes provider for terraform is failing with:
```
...
...
module.components.null_resource.cert_manager_issuers: Refreshing state... [id=1077953103912348481]
module.components.null_resource.nginx_ingress_default_certificate: Refreshing state... [id=6234213918410003309]
module.components.aws_iam_role_policy_attachment.externaldns_attach_policy: Refreshing state... [id=externaldns.manager.cloud-platform.service.justice.gov.uk-20200107102431644800000001]
module.components.aws_iam_role_policy_attachment.cert_manager_attach_policy: Refreshing state... [id=cert-manager.manager.cloud-platform.service.justice.gov.uk-20200107102431860400000003]
Error: invalid resource name "/cluster-critical": [may not contain '/']
Error: invalid resource name "/node-critical": [may …
```
> Pin Kubernetes Terraform provider to v1.10.0

- smoke-tests/spec/ingress_spec.rb
This is to verify if api latency high is caused because of this test.
Will un-do this change after validating the result, by running smoke tests.
> Commented out ingress with invalid syntax test

- smoke-tests/spec/ingress_spec.rb
To test kubeapi latency alert, commented out  this test, kubeapi latency alert still triggered, while this test is paused. Now the test is complete so uncommented now.
> Release invalid syntax test

- kops/live-1.yaml
- terraform/cloud-platform-components/prometheus.tf
- terraform/cloud-platform/kops.tf
- terraform/cloud-platform/templates/kops.yaml.tpl
- terraform/cloud-platform/variables.tf
- From terraform 0.12 it is advised to use `templatefile()` to render templates. This PR migrates from data template to `templatefile()`
- Added new variable (`enable_large_nodesgroup`) to enable a larger node group (mainly for Prometheus) be available within the cluster
- Within components, we added new variable and module version which implements NodeAffinity
> New nodegroup and templatefile() migration

- create-cluster.rb
Updated create test clusters script with the new variable `enable_large_nodesgroup` set to false. If we leave the default value (`true`) it will be created a couple of large (r5.2xlarge) nodes which are not required for test clusters.
> No create larger instance node groups for tests clusters

- kops/live-1.yaml
- terraform/cloud-platform/templates/kops.yaml.tpl
The node recycler expects the main worker nodes instancegroup to be the last
document in the kops yaml file. This change puts it there, and adds an
explanatory comment.
This change includes both the template and the file which is produced by
`terraform apply`
> Put kops worker nodes instancegroup at end of file

- recycle-node.rb
We just added an extra instancegroup so that prometheus/thanos could run on a bigger node. 
So the node recycler can't just count all worker nodes; it needs to only count the number of running worker nodes in the relevant instance group.
> Only recycle nodes in target instance group

- kops/live-1.yaml
- terraform/cloud-platform-components/prometheus.tf
- terraform/cloud-platform-components/templates/kiam.yaml.tpl
- terraform/cloud-platform/templates/kops.yaml.tpl
- Update the kops template to set taints for the large nodes dedicated to Prometheus, like that we ensure 
- New prometheus module version which include the following changes:
* Variable to enable or not thanos helm chart deployment (for test cluster it is not needed it)
* Added tolerations in a conditional way with a variable (so test cluster don't get affected) for tolerations.
> Taint and tolerations for Prometheus

- terraform/cloud-platform-components/prometheus.tf
This PR push the Prometheus module one version up in order to use tolerations within the Thanos Helm Chart, specifically Thanos Store, which is consuming a lot of resources.
> Added tolerations to Thanos

- kops/live-1.yaml
- terraform/cloud-platform/templates/kops.yaml.tpl
Following up decisions taken after our meeting, this PR moves `r5.2xlarge` nodes from AZ-A to AZ-B.
> Remove large nodegroup access to AZ-A

- terraform/cloud-platform-components/opa.tf
- terraform/cloud-platform-components/templates/opa/values.yaml.tpl
OPA Helm chart is the only chart blocking us towards Helm 3 migration. This PR pushes the chart to the latest available version so we can retry and test the Helm 3 migration and hopefully get better results.
This change also includes migration to terraform `templatefile()` function and deletion of some already default values within the `values.yaml` file.
> Upgraded OPA Helm Chart to latest

- terraform/cloud-platform-eks/components/main.tf
Pin kubernetes provider to `0.10.0` otherwise it doesn't work.
Added extra hostzone in cert-manager IAM role  (0.0.7 module version).
> Kubernetes provider set to 1.10.0 and IAM roles fix

- terraform/cloud-platform-components/prometheus.tf
In order to fix the PrometheusOutOfOrderTimestamps we are trying to increase the scrape interval
> Increased cloudwatch interval to 2 mins

- terraform/cloud-platform-eks/components/main.tf
Bumped the terraform module to the latest one, which includes the OPA terraform module. This OPA module is shared between EKS and KOPS.
> OPA terraform module in EKS components

- terraform/cloud-platform-components/monitoring.tf
- terraform/cloud-platform-eks/components/main.tf
Besides the rename, we re-deployed Cloudwatch exporter and add explicitly the stable repository. (more information [here](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/13/files))
> Renamed prometheus module to monitoring

- terraform/cloud-platform-eks/components/main.tf
Set up nginx as terraform module and upgrade it to the latest helm chart (1.35).
> Nginx as terraform module and helm chart pushed to latest

- terraform/cloud-platform-components/monitoring.tf
To fix "Context Deadline Exceeded" error for cloud-watch in prometheus.
> Updating cloudwatch timeout: 60s

- terraform/cloud-platform-components/monitoring.tf
For some metrics which are updated very
infrequently (such as S3/BucketSize), Prometheus
may refuse to scrape them if this is set to true. So set it to false.
> Updated cloudwatch_exporter set_timestamp to false

- smoke-tests/spec/ingress_spec.rb
We are getting timeouts and we see it gets fixed only when we extend the time to 30 seconds.
> Increased timeout for ingresses (otherwise they fails)

- terraform/cloud-platform-components/nginx-ingress-acme.tf
In order to support IE11 to access our platform, we need to activate legacy TLS support in nginx. This is what this PR does.
> Added legacy-TLS support to nginx ingress controller

- terraform/cloud-platform-eks/components/main.tf
This change uses the latest cert-manager version
> Upgrade cert-manager in EKS manager cluster

- terraform/cloud-platform-eks/main.tf
Grafana callback URL in EKS is pointing to the wrong domain causing fail logins, this PR fixes it
> Fixed grafana callback URL in Auth0

- terraform/cloud-platform-components/monitoring.tf
New module with silenced api high latency alarm.
Custom alarms have been created with differing trigger values and separated out specifically for ingress post api calls.
> New module with silenced api high latency alarm

- create-cluster.rb
- smoke-tests/makefile
- smoke-tests/spec/authorized_keys_spec.rb
- smoke-tests/spec/crds_spec.rb
- smoke-tests/spec/daemonsets_spec.rb
- smoke-tests/spec/docker_registry_cache_spec.rb
- smoke-tests/spec/external_dns_spec.rb
- smoke-tests/spec/kiam_spec.rb
- smoke-tests/spec/logging_spec.rb
- smoke-tests/spec/master_nodes_spec.rb
- smoke-tests/spec/namespace_annotations_spec.rb
- smoke-tests/spec/prometheusrules_spec.rb
- smoke-tests/spec/servicemonitors_spec.rb
- smoke-tests/spec/tzcronjob_spec.rb
This is for EKS integration tests.    
Updated rspec tag cluster: live-1 to live-1: true, and create new tag for kops: true and eks-manager: true. New tags can be used to differentiate tests to run on kops cluster and EKS cluster.   
Updated create-cluster.rb to exclude eks tests
Update makefile to use new tags.
The --tag ~eks-manager will exclude eks tests, running on kops clusters.
The --tag ~kops will exclude kops specific tests, running on eks clusters.
> EKS integration tests

- terraform/cloud-platform-eks/components/main.tf
The cluster creation was failing because of missing Prometheus dependencies. Below the error.
```
on .terraform/modules/components.cert_manager/irsa.tf line 14, in resource "aws_iam_policy" "cert_manager":
14: resource "aws_iam_policy" "cert_manager" {
Error: rpc error: code = Unknown desc = validation failed: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
on .terraform/modules/components.cert_manager/main.tf line 49, in resource "helm_release" "cert_manager":
49: resource "helm_release" "cert_manager" {
```
> Fixed EKS cluster creation. 

- smoke-tests/spec/ingress_spec.rb
- smoke-tests/spec/kiam_spec.rb
- smoke-tests/spec/modsec_spec.rb
This will fix below error, by not running "fetch_or_create_role", for eks cluster tests.
Error:
"An error occurred while loading ./spec/kiam_spec.rb.
Failure/Error:
client.update_assume_role_policy(policy_document: role_policy.to_json, role_name: role_name)"
Also, Increase sleep time for ingress and mod-security tests.
As some integration test runs are failing, when ingress is deployed, it fails to returns 200 for http get.
> Eks kiam tests

- terraform/cloud-platform-eks/components/main.tf
More details about the change in github.com/ministryofjustice/cloud-platform-terraform-eks-components
> Added Cloud Platform monitoring module to EKS

- terraform/cloud-platform-components/velero.tf
The module dependence is called "Prometheus" instead of "monitoring"
> Renamed dependence on Prometheus

- smoke-tests/spec/prometheusrules_spec.rb
Removed "prometheus-operator-kubernetes-apps", not using this after prometheus module change.
> Fix Prometheus Rules eks tests

- terraform/cloud-platform-components/kiam.tf
- terraform/cloud-platform-components/kuberos.tf
- terraform/cloud-platform-components/main.tf
- terraform/cloud-platform-components/opa.tf
Helm 3 [doesn't create namespaces](https://itnext.io/breaking-changes-in-helm-3-and-how-to-fix-them-39fea23e06ff) and helm terraform provider does [not assume stable repo anymore](https://github.com/terraform-providers/terraform-provider-helm/issues/163)
These changes are required as part of the transition to Helm 3.
> Explicitly added namespaces as part of the transition to Helm 3

- terraform/cloud-platform-eks/components/main.tf
This release contains the external-dns module call
> Bump EKS components version to 0.3.3

- terraform/cloud-platform-eks/components/main.tf
More details about this change in the externalDNS repository: https://github.com/ministryofjustice/cloud-platform-terraform-external-dns/pull/4
Basically it was added the right annotations within the ServiceAccount for EKS be able to link the IAM role to the ServiceAccount
> Fixed externalDNS in manager cluster

- terraform/cloud-platform-components/monitoring.tf
- terraform/cloud-platform-eks/components/main.tf
This is required for Helm 3. Otherwise we face:  https://github.com/helm/charts/issues/20581
> Prometheus upgrade to 8.13 latest

- terraform/cloud-platform-components/monitoring.tf
This module update silence aggregateAPI alarm. More information in https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/27
> components pointing to the latest monitoring tf module

- terraform/cloud-platform-eks/components/components.tf
- terraform/cloud-platform-eks/components/k8s-resources.tf
- terraform/cloud-platform-eks/components/main.tf
- terraform/cloud-platform-eks/components/resources/psp/pod-security-policy.yaml
- terraform/cloud-platform-eks/components/variables.tf
- Migrated components from cloud-platform-terraform-eks-components to infrastructure.
- Pinned helm provider 1.0.0, which basically means Helm3
> Helm 3 and migration of EKS components to infrastructure

- terraform/cloud-platform-components/cert-manager.tf
- terraform/cloud-platform-components/external-dns.tf
- terraform/cloud-platform-components/monitoring.tf
- terraform/cloud-platform-components/velero.tf
Updated components to the latest module versions. 
The only change affecting live-1 is the rename of the externalDNS serviceAccount from `default` to `externalDNS`
> Updated components to the latest module versions

- terraform/cloud-platform-eks/components/components.tf
We are using grafana datasource in EKS, it actually is causing problems with the role length. For the time being, it was removed
> Remove grafana datasource from EKS

- terraform/global-resources/s3.tf
WHAT 
Add replication for the s3 buclet that store the kops state to a secondary bucket 
WHY
This is now in code and adds redundancy incase we lose the primary bucket 
Note:
There is an ignore_changes added to the primary s3 bucket under replication configuration
lifecycle {
ignore_changes = [
replication_configuration[0].rules,
]
}
This is due to the `id` changing each time a terraform plan is run. The whole block as been ignored as this block is a set and not a typelist so unable to ignore specifics in the block
https://github.com/hashicorp/terraform/issues/22504#issuecomment-522615551
There is also a priority status for each rule, this is optional and not required unless we have multiple rules and need to add priority.
> Add replication to kops_state_store s3 bucket

- smoke-tests/spec/cert_manager_spec.rb
- smoke-tests/spec/daemonsets_spec.rb
We are not using kube2iam in EKS now, instead we are using "IAM roles for service accounts".
Increased cert-manager sleep time . Cert-Manager test fail, may be caused due to ingress creation delay. Increased the sleep time to fix it.
> Fix smoke tests kube2iam

- destroy-cluster.rb
Catching exception and retry when destroying prometheus due to CRDs deleted before deleting prometheus resources.
> Catch exception and retry - tf_destroy prometheus module

- smoke-tests/makefile
- Useful and easy when testing upgrade on test clusters
> To run fast tests on test clusters. 

- smoke-tests/spec/logging_spec.rb
- terraform/global-resources/elasticsearch.tf
Update cloud-platform live ES version to 7.4
Created s3 bucket for snapshot before upgrading it to 7.4
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains-snapshots.html
Also increased sleep time for ES integration test, as test is failing.
> Update es version

- smoke-tests/spec/fixtures/helloworld-deployment.yaml.erb
- smoke-tests/spec/fixtures/modsec-integrationtest.yaml.erb
Since 1.16 (as you can see [here](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)) Kubernetes 1.16 won't support `apiVersion: extensions/v1beta1` and that is exactly what we are using in our Integration tests. I'll also upgrade ingress to use `networking.k8s.io/v1beta1`
> Upgrade APIs versions for Deployments and Ingresses in 1.16

- smoke-tests/spec/logging_spec.rb
The new ES API returns different JSON. Our integration tests need to be updated.
> Fix JSON parse

- terraform/cloud-platform-components/external-dns.tf
- terraform/cloud-platform-eks/components/components.tf
external-dns stable chart is depreciated, we used Bitnami maintained ExternalDNS Helm chart.
bitnami-external-dns :
https://github.com/bitnami/charts/tree/master/bitnami/external-dns
As part of the upgrade, use policy: sync.
> Update external-dns to chartv3.1.0

- terraform/cloud-platform-eks/components/components.tf
Nginx is not in the latest terraform module, which includes changes related with shared memory issues we faced in live-1. More information [here](https://github.com/ministryofjustice/cloud-platform-terraform-ingress-controller/pull/3)
`dependence_deploy` variable was needed when we were using Helm 2, it was the way to tell Helm Chart inside our terraform modules to wait for tiller before getting installed.
Now we are using Helm 3 and there is not tiller in the clusters.
> Removed dependence_deploy IN EKS and nginx upgrade to latest module

- destroy-cluster.rb
related to https://github.com/ministryofjustice/cloud-platform/issues/1926
Add command-line options for the required variables, so that the script can be invoked non-interactively, by a concourse pipeline.
> Make `destroy-cluster.rb` non-interactive

- destroy-cluster.rb
We tried putting `terraform workspace select` before `terraform init` to
avoid the error where the user already has a workspace selected, and that
workspace no longer exists. But, this doesn't work, and you get the
error:
```
Error: Initialization required. Please see the error message above.
```
So this change reverts back to running `terraform init` first, and then
running `terraform workspace select ...`
> Revert to terraform init, then select

- terraform/cloud-platform-components/monitoring.tf
- terraform/cloud-platform-eks/components/components.tf
This is due to Grafana 7.0.2 released with important security fix
https://grafana.com/blog/2020/06/03/grafana-6.7.4-and-7.0.2-released-with-important-security-fix/?utm_source=grafana_news&utm_medium=rss
> Upgrade grafana to 7.0.2

- terraform/cloud-platform-eks/components/resources/psp/pod-security-policy.yaml
In EKS we are using already 1.16 and `extensions/v1beta1` was already removed deprecated.
This PR upgrades de PSP to `policy/v1beta1`, already tested in EKS against _ale1_ cluster.
> Migrated PSP to policy/v1beta1 for EKS

- smoke-tests/spec/kiam_helper.rb
Kiam tests are failing with reason "Unable to locate credentials". Added sleep for create role to fix this issue.
> Add sleep to fix kiam test

- kops/live-1.yaml
- terraform/cloud-platform/templates/kops.yaml.tpl
This allows Prometheus to scrape the kubeProxy endpoint as outlined in https://github.com/ministryofjustice/cloud-platform/issues/1636
> Add kubeProxy stanza to kops manifest

- terraform/cloud-platform-eks/variables.tf
This is to fix CPU-High Alerts
Alert: This device's CPU usage has exceeded the threshold with a value of 95.53333333324797. Instance XXXXXX CPU usage is dangerously high
>  Increase instance type for EKS cluster.

- terraform/cloud-platform/main.tf
- terraform/cloud-platform/outputs.tf
Why:
[Delete Expired SSL Certificates#1909](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/1909)
Whilst investigating 2 expired ssl certificates - it was found that they had been created as AWS ACM's in the Ireland region dashboard and cli. I then found 29 in the London region - that were not in use (including 1 that had expired).
The conclusion was that these were being created in redundant code for cluster creation.
> remove references to the module cluster_ssl

- smoke-tests/spec/concourse_spec.rb
New 'concourse_spec.rb' test added to verify concourse / concourse-main namespaces and running of pods within concourse ns.
> Concourse tests

- kops/live-1.yaml
- terraform/cloud-platform/templates/kops.yaml.tpl
Kubernetes upgrade from 1.15.10 to 1.15.12 to mitigate https://github.com/ministryofjustice/cloud-platform/issues/1971
> Kubernetes upgrade to v1.15.12

- recycle-node.rb
This has changed in the live-1 cluster, and it's how the script
identifies which worker nodes are eligible to be recycled
> update the main worker nodegroup name

- .github/workflows/format-code.yml
- .github/workflows/malformed-yaml.yml
- ministryofjustice/github-actions has changed the default branch to main, hence use the main branch of that repo
> Change github-actions repo to pull from main instead of master

- smoke-tests/spec/fixtures/privileged-deployment.yaml.erb
- smoke-tests/spec/fixtures/unprivileged-deployment.yaml.erb
- smoke-tests/spec/kubernetes_helper.rb
- smoke-tests/spec/psp_spec.rb
Overview
---
This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/1908 and relates to the creation of integration tests for the pod security policies in a Cloud Platform cluster. The tests check the following:
- Whether the three important pod security policies exist in the cluster
- Whether a privileged and unprivileged container can run inside and privileged namespace.
- Whether a privileged container fails to run inside an unprivileged namespace.
- Whether an unprivileged container can run inside an unprivileged namespace.
> Create pod security policy integration tests

- terraform/cloud-platform-components/resources/psp/pod-security-policy.yaml
The API change is part of the Kubernetes 1.16 upgrade path. The old extensions api is deprecated. The docker/default seccomp was deprecated as of 1.11. Runtime/default is now used. Docker/default is still allowed in the allowedProfileNames annotation to backport legacy apps. This document describes seccomp in more detail: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp
Tests in a 1.15.11 cluster were successful.
> Amend API version and seccomp profile used in pod security policies

- terraform/global-resources/elasticsearch.tf
Update ES instance_type to m4.4xlarge.elasticsearch
This is related to: https://github.com/ministryofjustice/cloud-platform/issues/1939
> Update ES instance_type to m4.4xlarge.elasticsearch

- smoke-tests/spec/ingress_spec.rb
This test is intermittently failing because of performance
problems with our shared ingress.
It's not telling us anything useful right now, and is encouraging
us to ignore integration test failures, so I'm disabling it until
we can fix the underlying problem.
> Disable the ingress spec which is failing

- .github/workflows/linter.yml
We are testing the github super-linter and infrastructure repo sounds a good place to start with. Added `VALIDATE_ALL_CODEBASE: false` to avoid it scan our whole repository [1] and instead focus on PR code 
[1] It takes a lot of time to scan and we have **a lot** (more than 100...) of errors with markdownlint.
> Added Github SuperLinter

- README.md
- create-cluster.rb
- destroy-cluster.rb
- makefile
- terraform/cloud-platform-eks/main.tf
- terraform/cloud-platform/main.tf
This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/1990 and relates to the change in Auth0 Terraform provider. The third party provider alexkappa/terraform-provider-auth0 has recently been accepted in the Terraform Provider Developer Program. This means we can now let `terraform init` pull the provider on each run. 
It has been decided that we should pin the tested version `0.12.2` to the provider call. This PR contains the pinning of said provider along with the removal of a check method in the create/destroy cluster scripts. 
I noticed we're still referencing circleci in our README, so I decided to remove this also.
> Pin auth0 provider version

- terraform/global-resources/elasticsearch.tf
This is created for manual snapshot before ES 7.4 upgrade, no longer needed now.
> Remove aws_s3_bucket for cp-elasticsearch

- .gitattributes
- .github/workflows/linter.yml
Added exclusions to Github Super Linter:
- Files that are encrypted (`*.tfvars`)
- `cluster.tf`
> Fixing linter

- terraform/cloud-platform/main.tf
The latest version includes authorized-keys inside the module rather than pointing to S3 bucket.
> Upgrade bastion module to latest version

- terraform/cloud-platform/main.tf
- terraform/cloud-platform/outputs.tf
Before I deleted some outputs thinking they were not used, later on @vijay-veeranki realised they were being used in the [concourse apply pipeline](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/environments-terraform/jobs/apply-live-1/builds/338) so I'm adding them back.
> Added back outputs because they are required by the apply pipeline

- smoke-tests/spec/psp_spec.rb
PSP integration tests fails sometimes as the expect checks before the deployment creates container and the container is ready.
> Add sleep between deployment and expect psp tests

- smoke-tests/spec/authorized_keys_spec.rb
Now we are maining the keys in
https://github.com/ministryofjustice/cloud-platform-terraform-bastion/blob/main/files/authorized_keys.txt
> Update authorized_keys test

- smoke-tests/spec/authorized_keys_spec.rb
Removed an integration test which doesn't apply anymore because of the latest changes (moved the authorised keys to the bastion module).
> Fixed integation tests with the latest changes

- kops/live-1.yaml
- makefile
- smoke-tests/spec/daemonsets_spec.rb
Kops live-1.yaml changes for kubernetes 1.16.13 upgrade
bump tools image
Add kops-controller daemonset as not part of kubernetes upgrade 1.16.13
> Changes for Kops 1.16.3 and Kubernetes Upgrade 1.16.13

- recycle-node.rb
The worker node instance group was changed as part of the upgrade to
kubernetes 1.16. This change updates the recycle-node.rb script
accordingly.
> Fix WORKER_NODE_INSTANCEGROUP in recycle-node.rb

- smoke-tests/spec/psp_spec.rb
- terraform/cloud-platform-components/resources/psp/pod-security-policy.yaml
This PR amends the Cloud Platform pod security policies, allowing them to work on an AWS EKS cluster (specifically the live manager cluster). It also includes the removal of the "kops only" flag in our integration tests, meaning it'll be run against both EKS 
and kops clusters in the future. 
The API groups had to be changed as the extensions API has been deprecated. In addition to this a number of service accounts were added to allow numerous kube-system pods access to the privileged PSP.
When merged we will need to perform a `terraform apply` to the components of both live-1 and manager. EKS comes with a default PSP, this will need to be removed in all future clusters. An issue has been raised to approach this work [here](https://github.com/ministryofjustice/cloud-platform/issues/2106) …
> AWS EKS Pod Security Policies

- smoke-tests/spec/prometheusrules_spec.rb
We no longer send alerts to #lower-priority-alarms for ECRs with high
image counts. So this change removes the check for
`prometheus-custom-alerts-ecr-exporter` in the list of prometheus rules.
> Remove ECR check from expected prometheus rules

- terraform/global-resources/elasticsearch.tf
Doubled number of ES nodes because we are going to deploy fluentbit in live cluster.
> Increased elasticsaerch nodes

- smoke-tests/spec/daemonsets_spec.rb
* live-1 runs fluentd and fluent-bit
* manager cluster runs fluentd
These tests will need to be updated again if we
add fluent-bit to the manager cluster and/or 
remove fluentd.
> Update tests wrt. fluent-bit

- smoke-tests/spec/daemonsets_spec.rb
fluent-bit is not running in the EKS manager cluster yet.
> Only test for fluent-bit on kops clusters

- smoke-tests/spec/psp_spec.rb
By deleting the clusterrolebinding after every context, it will ensure
any leftover resources will be removed.
We found an issue whereby the test was failing on the method before
cleanup(`expect(all_containers_running?(pods)).to eq(true)`), which
meant the delete_clusterrolebinding method was never called.
> Move delete_clusterrolebinding method call to clean up resources

- smoke-tests/spec/external_dns_helper.rb
We sometimes see this failure:
```
Failures:
1) external DNS when zone matches ingress domain and an ingress is deleted it deletes an A record
Failure/Error:
client.change_resource_record_sets({
hosted_zone_id: zone_id,
change_batch: {
changes: [record_change]
}
})
Aws::Route53::Errors::InvalidChangeBatch:
[Tried to delete resource record set [name='integrationtest.service.justice.gov.uk.', type='A'] but it was not found]
```
I'm not entirely sure how this happens. It may be that someone is running the
external dns tests manually at the same time as the pipeline, so a race
condition arises.
Either way, this particular error should not cause the test to fail. The only
thing that matters is that the zone does not exist before the test runs - how
that happens doesn't matter. So, we can catch …
> Continue if zone deletion throws an error

- smoke-tests/spec/external_dns_helper.rb
I made a mistake in #833, whereby the rescue block is outside of the
context in which `record` exists, so an [undefined variable error gets
thrown](https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/reporting/jobs/integration-tests/builds/1297) if the rescue clause is triggered.
This change moves the begin/rescue inside the loop, where `record`
exists if an error occurs. This should have the desired effect of
allowing the tests to continue successfully, even if the A/TXT record is
not found when the cleanup code tries to delete it.
> Move begin/rescue inside the 'records' loop

- smoke-tests/spec/kubernetes_helper.rb
This method is used by the logging specs, which launch a job and then
check whether the logs show up in elasticsearch.
The method relies on kubectl output including the word "Succeeded",
which used to appear 2 lines above the job name in the output from
`kubectl describe pods`
It seems the format of kubectl output has changed, because "Succeeded"
now *sometimes* appears 4 lines above the job name, not 2 lines.
This caused `wait_for_job_to_start` to always fail, resulting in the
logging specs failing.
This change should make the logging specs pass more consistently.
> Fix the "wait_for_job_to_start" helper method

- smoke-tests/spec/modsec_spec.rb
With the previous sleep delay of 90s, we were getting intermittent but
frequent failures for these tests.
We believe this is because our current setup of having one ingress
controller for (almost) every namespace means it takes much longer to
implement ingress changes than it should, hence the need for this delay.
In testing, a sleep of 180 seconds meant the tests passed consistently.
> Increase sleep delay after creating modsec ingress

- terraform/cloud-platform-account/main.tf
It was also included the exceptions and it was already tested against our CP account.
More details about the change within the module are [here](https://github.com/ministryofjustice/cloud-platform-terraform-awsaccounts-baselines/pull/3)
> Lambda to block public access for S3 buckets

- terraform/cloud-platform-components/components.tf
Why [Amend nginx alarm to show which pod has failed#2188](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2188) >
https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/releases/tag/0.3.6
> new release 3.6  to cloud-platform-terraform-monitoring

- create-cluster.rb
We're using helm3 now, which doesn't have/need an "init" command
> Remove "helm init" from the cluster build script

- terraform/cloud-platform-components/components.tf
Due fluent-bit adds serviceMonitor resource (CRD components of Prometheus) it was needed to create an explicit dependency. Please check https://github.com/ministryofjustice/cloud-platform-terraform-logging/pull/11
> fluentbit depends on prometheus for deployment

- smoke-tests/spec/psp_spec.rb
This test seems to be failing occasionally. This change is an attempt to
make it more reliable.
> Increase sleep from 10 to 20 for a PSP test

- kops/live-1.yaml
- terraform/cloud-platform/main.tf
Migrate from kubeDNS to CoreDNS.
As of Kubernetes v1.12, CoreDNS is the recommended DNS Server, replacing kube-dns
https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#introduction
Use new kops module with the change
> Use new kops module and amend live-1 manifest to use CoreDNS

- kops/live-1.yaml
- terraform/cloud-platform/variables.tf
This is because the c4 instance family is nearing its end of life, and
we ran into availability problems the last time we tried to replace a c4
master node.
This change should help to mitigate such issues, because c5 has
generally better availability. We are talking to AWS about a more robust
way to prevent such problems in future.
> Change master nodes from c4.4xlarge to c5.4xlarge

- smoke-tests/spec/psp_spec.rb
Similar to #06898b34, this change is an attempt to make this particular
test more reliable. It doesn't fail often, but this specific test has
failed multiple times over the past few days.
> Increase sleep delay for PSP test

- terraform/cloud-platform-components/components.tf
More details please visit [this PR](https://github.com/ministryofjustice/cloud-platform-terraform-monitoring/pull/40/files)
> New version of the monitoring's terraform module

- terraform/cloud-platform-eks/components/components.tf
This version got additional permissions for concourse to create EKS components
> Update concourse to use the latest version 1.2.4

- smoke-tests/spec/psp_spec.rb
This psp spec fails occasionally. Increasing sleep to 20 seconds seems
to have fixed the other psp tests, so hopefully this will have the same
effect for this one.
> Increase sleep delay to make tests more reliable

- smoke-tests/spec/cert_manager_spec.rb
- smoke-tests/spec/external_dns_spec.rb
- smoke-tests/spec/ingress_spec.rb
- smoke-tests/spec/modsec_spec.rb
This is to avoid load on ingress-controller, as we are having Nginx config issues.
> Disable tests which creates ingress

- terraform/cloud-platform-eks/components/components.tf
This is causing error "Error: Invalid multi-line string"
> Fix monitoring source in EKS

- terraform/cloud-platform-components/components.tf
As the latest cloud-platform-terraform-teams-ingress-controller changes, will use the ingress-controller default certificate
> Remove default_cert for monitoring namespace

- smoke-tests/spec/fixtures/external-dns-ingress.yaml.erb
- smoke-tests/spec/fixtures/helloworld-deployment.yaml.erb
- smoke-tests/spec/fixtures/invalid-nginx-syntax.yaml.erb
- terraform/cloud-platform-components/docker-registry-cache.tf
PR connects to https://github.com/ministryofjustice/cloud-platform/issues/2243
Due to the split of ingress controllers we will need to define which
ingress controller our traffic should traverse. It has been decided that
we will keep a generic controller but will need to be specified via an
annotation.
> Add annotations to integration test ingress

- smoke-tests/spec/servicemonitors_spec.rb
Remove ingress-controllers service-monitor check
The ingress-controllers namespace will now have a servicemonitor added
to it every time we create a new ingress-controller. This means the test
for expected servicemonitors is going to be impossible to manage.
> Remove ingress-controllers service-monitor check

- terraform/cloud-platform-components/components.tf
Add explicitly dependencies between ingress controller for monitoring namespace and Prometheus/CertManager
> Fix cluster creation dependences

- terraform/cloud-platform-components/components.tf
From now on monitoring traffic is going through the default ingress controller.
> Removing monitoring ingress controller

- smoke-tests/spec/ingress_spec.rb
- smoke-tests/spec/modsec_spec.rb
The Integration test pipeline fails because the tests specific to kops are not tagged and got tested for EKS cluster
This will fix the pipeline.
> Add kops:true tag for tests specific to kops cluster

- terraform/cloud-platform-eks/components/components.tf
This version provides the HOODAW API key secret.
related to
https://github.com/ministryofjustice/cloud-platform-terraform-concourse/pull/9
> Use v1.2.7 of the concourse module

- terraform/cloud-platform-eks/components/components.tf
This commit connects to
https://github.com/ministryofjustice/cloud-platform/issues/2078 and will
bump the monitoring stack on the Manager cluster to version 0.4.3. This
version contains a change to the monitoring (alertmanager and
prometheus) proxies.
> Bump monitoring release for Manager cluster

- terraform/cloud-platform-components/components.tf
- terraform/cloud-platform-eks/components/components.tf
This PR connects to
ministryofjustice/cloud-platform#2078 and
relates to the chart version upgrade of the alertmanager and prometheus
proxies.
> Bump the live-1 monitoring module to 0.4.3

- terraform/cloud-platform-components/components.tf
Bump version of default ingress-controller to 0.0.6 which has ModSecurity disabled
> Bump version of default ingress-controller to 0.0.6

- terraform/cloud-platform-components/components.tf
Revert "Removed dependency variables, not required anymore"
This reverts commit f1e468b. We need this dependency for "ingress_controller_integration_test"
Destroy cluster fails some times as ingress-controller namespace stuck in terminating state, so added cert-manager dependency.
"reason":"ContentDeletionFailed","message":
"Failed to delete all resource types, 1 remaining: conversion webhook for acme.cert-manager.io/v1alpha2
> Add dependency for ingress_controller_integration_test, and default ingress_controllers

- terraform/cloud-platform-components/components.tf
More details about the change here: https://github.com/ministryofjustice/cloud-platform-terraform-certmanager/pull/10
> Add custom Prometheus labels for CertManager

- terraform/cloud-platform/main.tf
The new Prometheus URL also needs a CallbackURL registration in Auth0. This PR includes it.
> Adding new Prometheus URL

- smoke-tests/spec/servicemonitors_spec.rb
This will fix the integration test 
servicemonitors expected prometheus servicemonitors in kops clusters
Failure/Error: expect(names).to include(*expected)
expected ["cloudwatch-exporter-prometheus-cloudwatch-exporter", "ecr-exporter-prometheus-ecr-exporter", "prome...rometheus-operator-node-exporter", "prometheus-operator-operator", "prometheus-operator-prometheus"] to include "prometheus-operator-kube-dns"
> Replace kube-dns with corends service monitor test

- terraform/cloud-platform-components/components.tf
This will fix build test cluster failure dependency issue.
https://concourse.cloud-platform.service.justice.gov.uk/teams/main/pipelines/build-test-cluster/jobs/build-kops-test-cluster/builds/11
> Add dependency for ingress_controller_integration_test

- terraform/cloud-platform-components/components.tf
The new module versions include a slack annotation in the namespace that
were previously applied via the environments repository.
> Bump Kiam, Kuberos, Logging and Opa module versions

- destroy-cluster.rb
Prevent script executing outside docker container
We only want this script to run in a docker
container (usually started via `make tools-shell`)
so that we have complete control over its
environment.
This function tests whether the script is running
inside a docker container, and fails if it isn't.
> Prevent destroy script running outside container

- terraform/cloud-platform-eks/components/components.tf
This PR is to bump cluster-autoscaler to version 0.0.4 which uses the latest chart 1.0.3 and image 1.16.6
Related to: https://github.com/ministryofjustice/cloud-platform-terraform-cluster-autoscaler/pull/1
> Bump cluster-autoscaler to version 0.0.4

- kops/live-1.yaml
- recycle-node.rb
- terraform/cloud-platform/main.tf
- terraform/cloud-platform/variables.tf
This is related to [2272](https://github.com/ministryofjustice/cloud-platform/issues/2272)
This will help to alter our kops config to control which AZ our worker nodes are created.
Also updated the recycle node job script to handle multiple AZ ig.
> Define per-AZ instancegroups for worker nodes

- smoke-tests/spec/daemonsets_spec.rb
- smoke-tests/spec/master_nodes_spec.rb
Please note, this will not remove fluentd from our cluster, just the
ability to test it. We are aware of issues related to this integration
test and a decision has been made to remove fluentd altogether. The
removal will be undertaken in another ticket.
Fluentd still exists in the manager cluster so all tests that take place
there are untouched.
> Remove fluentd integration tests

- smoke-tests/spec/daemonsets_spec.rb
As fluentd still exists in the cluster it's easier to add this daemonset
check back in.
> Add fluentd-es back to daemonset integration test

- terraform/cloud-platform-components/components.tf
In order to have a test cluster similar to live-1, we should also include network policies. This PR calls the latest version of the terraform monitoring module which includes network policies
> Adding network policies inside terraform monitoring module

- smoke-tests/spec/ingress_spec.rb
This ingress spec is consistently failing. I think that may be because
it's taking longer to create/modify ingresses than it was when the test
was first written.
This change increases the delay from 60 to 90 seconds, after creating
the test ingress, before trying to use it.
> Increase wait after creating ingress

- smoke-tests/spec/ingress_spec.rb
I dug into the consistently failing test (line 47), and it does pass,
when running locally, with a sufficiently long delay. By repeatedly
testing with different sleep delays, 400s looks like a valid choice to
get tests which pass consistently.
This is a ridiculously long time to wait for a test to run, so I've
added a `speed: "slow"` tag, so that people can bypass this test when
they need faster feedback.
> Increase ingress sleep_delay to 400s

- smoke-tests/spec/concourse_spec.rb
- terraform/cloud-platform-eks/components/components.tf
1.3.2 - Remove minor version upgrade for postgres
1.3.3 - Upgrade helm chart 13.0.0 and concourse version 6.6.0
> Bump concourse version to 1.3.3

- kops/live-1.yaml
This commit adds three additional instance groups to the Kops manifest.
These groups contain a single instance in each eu-west-2 az to allow
for fine grained failure and scale.
The idea behind these instance groups is to dedicate a resource pool to
a critical component in a production cluster.
This PR connects to https://github.com/ministryofjustice/cloud-platform/issues/2416
> Add three ingress instance groups

- smoke-tests/spec/cert_manager_spec.rb
- smoke-tests/spec/ingress_spec.rb
- smoke-tests/spec/modsec_spec.rb
This reduces the integration tests until they do virtually nothing :(
This is (hopefully) a temporary measure until we are confident our default ingress controller is stable.
> Disable all specs which create ingresses

- terraform/cloud-platform-components/components.tf
This commit connects to
https://github.com/ministryofjustice/cloud-platform/issues/2406 and
relates to the requirement of an ingress controller with modsec turned
on.
> Add modsec ingress controller

- terraform/cloud-platform/main.tf
- terraform/cloud-platform/variables.tf
Connects to https://github.com/ministryofjustice/cloud-platform/issues/2416 and relates to the requirement to place ingress controllers onto dedicated nodes. This change will allow a user to create the dedicated nodes in test clusters.
> Bump kops version and enable ingress nodegroup variable

- terraform/cloud-platform-components/components.tf
Add modsec policies to reject mod-sec ingresses, In the default ingress controller
changes for the opa module:
https://github.com/ministryofjustice/cloud-platform-terraform-opa/pull/8
> Add modsec policies to reject mod-sec ingresses

- smoke-tests/spec/fixtures/helloworld-deployment-modsec.yaml.erb
- smoke-tests/spec/modsec_spec.rb
As we have a new OPA policy which will block mod-sec config on ingress, created a separate file for mod-sec tests
> Added new fixture for mod-sec integration tests

- terraform/cloud-platform-components/components.tf
As we have fluent-bit and fluentd daemonsets running in logging namespace
> Increase pod limit to 100 for logging namespace

- smoke-tests/spec/daemonsets_spec.rb
Now that we have switched completely to fluentbit, this test needs to be
updated.
> Remove fluentd from list of expected daemonsets

- terraform/cloud-platform-components/components.tf
To fix below error, while creating fluent-bit in test cluster.
File output-elasticsearch.conf
Error in line 40: Key has an empty value
> Added placeholder for ES audit for fluentbit

- terraform/cloud-platform-components/resources/psp/pod-security-policy.yaml
Add only capabilities needed for the privileged instead of a wildcard. This would allow to add any drop capabilities. Drop NET_RAW capability as this would allow root access to all the pod running as privileged CVE-2020-14386. NET_ADMIN is enough to run any pods with escalated permissions.
Related to: https://github.com/ministryofjustice/cloud-platform/issues/2335
> Add only capabilities needed for the privileged PSP

- smoke-tests/spec/ingress_spec.rb
Normally, I'd put this test in a spec of its own,
but these tests take so long to set up that it
makes more sense to have multiple expectations in
a single spec.
> Add a test that we don't get a "Server" header

- smoke-tests/spec/ingress_controller_spec.rb
- smoke-tests/spec/spec_helper.rb
These specs check that known ingresses on each of
the "nginx" and "modsec01" ingress controllers
respond as expected.
In particular, the specs confirm that the "Server"
header is not returned in the HTTP response.
As of now, this is true for the "modsec01" 
controller, but not for the "nginx" controller,
which needs a small configuration change to 
suppress that header. So, this test will fail
until that change is made.
These tests are quite brittle, because they depend
on an ingress which we don't control.
> Add tests for different ingress controllers

- terraform/cloud-platform-eks/main.tf
- terraform/cloud-platform-eks/variables.tf
Why? It will allow us to remove this in the divergence pipeline:
https://github.com/ministryofjustice/cloud-platform-concourse/blob/main/pipelines/manager/main/divergence.yaml#L78
It will also allow us to automate in an easier way a global terraform plan against cloud-platform-infrastructure when we start working with automated pipelines.
> Replace if/else with a map

- terraform/cloud-platform-components/components.tf
Applying the EKS version of this change, #962, did not cause any downtime to the "concourse" ingress, so I think this change should be safe to apply too.
> Use v0.0.11 for default ingress controller

- kops/live-1.yaml
- terraform/cloud-platform/main.tf
This version enables cross-zone load-balancing
depends on https://github.com/ministryofjustice/cloud-platform-terraform-kops/pull/8
> Use kops module v0.0.9

- destroy-cluster.rb
The starter-pack was recently changed, so that the namespace which
exists by default is `starter-pack-0` rather than `starter-pack`
This caused the cluster delete pipeline job to fail.
This change will ignore any namespaces called `starter-pack-0` to
`starter-pack-9`, when deciding if it is safe to delete a cluster.
> Ignore starter-pack namespaces

- terraform/cloud-platform-components/components.tf
- terraform/cloud-platform-eks/components/components.tf
Why:
Ticket [Check all custom Prometheus Rules #2475](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2475)- 
new release module cloud-platform-terraform-monitoring - version 0.5.8
> new-release-cloud-platform-terraform-monitoring-0.5.8

- recycle-node.rb
This will allow will remove it from the cluster entirel and as part of that process, it will remove it from ELB targetgroup for de-registering. This will ensure the existing connections are closed from ELB side.
As part of this ticket, the "Connection termination on deregistration" is enabled for the load-balancer of default ingress-controller.
Related to: https://github.com/ministryofjustice/cloud-platform/issues/2540
> Add delete node step after draining.

- create-cluster.rb
- makefile
Connects to https://github.com/ministryofjustice/cloud-platform/issues/2566
Due to the rate limiting on un-authenticated user accounts in Docker
hub, we need to add a docker config file to the worker and master nodes.
This is achieved by adding a kops secret, containing the base64 encoded
docker config file.
The following commit amends the `create-cluster.rb` script to allow
passing an argument to include a dockerconfig file or not. If the
argument is passed, the `add_dockerconfig` function checks the file
exists and executes the required command. I didn't want the script to
fail if the dockerfile doesn't exist so it should shield the [add secret](https://github.com/kubernetes/kops/blob/master/docs/cli/kops_create_secret_dockerconfig.md)
command to execute only if it exists.
> Add argument for adding a Docker config file to nodes

- terraform/cloud-platform-account/main.tf
We got the DockerHub pro account. We don't need this ECR repos anymore.
> Remove ECR repos

- kops/live-1.yaml
- terraform/cloud-platform/main.tf
This aligns the code with the manual changes we did during the incident at the beginning of the week. This should also fix the kops divergence pipeline.
> Remove mixed instance policies within monitoring nodes

- terraform/cloud-platform-components/components.tf
The Ingress controller upgrade is completed for live-1 so this is no longer required
> Remove fallback ingress controller

- terraform/cross-account-IAM/pathfinder-to-analytical-platform-prod.tf
AWS will not accept underscores here, so I've changed them to -
> Correct the metadata.name of the kubernetes secret

- create-cluster.rb
The `cloud-platform-eks` module look for the var.vpc_name for a given key, if not provided will use terraform.workspace as a vpc_name. For all eks test clusters the vpc_name is same as the workspace name.
> Remove vpc_name input during eks cluster creation

- terraform/cloud-platform-components/components.tf
What?
Move `hmpps-book-secure-move-api-ingress-production` ingress to the fallback ingress controller and have the ingress controller pods scheduled on InstanceGroup:ingress-nodes-1.17.12*. 
Why?
This is to isolate traffic on ingress `hmpps-book-secure-move-api-ingress-production` and see the behaviour of the NLB -TCP_Target_reset_count and sentry connection TIMEOUT without other interruptions such as recycling node pipeline.
> Add fallback controller back to test connection TIMEOUT. 

- terraform/cloud-platform-eks/components/components.tf
Upgrading to the latest logging module, otherwise EKS clusters fail in creation with:
```
Error: failed to download "stable/eventrouter" (hint: running `helm repo update` may help)
on .terraform/modules/logging/main.tf line 63, in resource "helm_release" "eventrouter":
63: resource "helm_release" "eventrouter" {
```
> Fix eventrouter helm repo in EKS

- terraform/cross-account-IAM/pathfinder-to-analytical-platform-prod.tf
This fixes the validation error:
```
Error: Duplicate resource "kubernetes_secret" configuration
on pathfinder-to-analytical-platform-prod.tf line 31:
31: resource "kubernetes_secret" "analytical_platform_landing_bucket" {
A kubernetes_secret resource named "analytical_platform_landing_bucket" was
already declared at pathfinder-to-analytical-platform-preprod.tf:31,1-66.
Resource names must be unique per type in each module.
```
> Fix duplicate secret in terraform/cross-account-iam

- terraform/cloud-platform-eks/components/main.tf
- Terraform plan and apply stuck and only works on this version.
- This fix the test EKS cluster creation.
> Pin kubernetes provider version specific to 1.11.1

- terraform/cloud-platform-components/components.tf
Also, disable affinity flag as this is specific to scheduling the ingress pods to ingress-nodes nodegroup which is not available in test clusters
> Disable installing fallback ingress controller on test cluster 

- terraform/cloud-platform-components/components.tf
Mode details on this PR: https://github.com/ministryofjustice/cloud-platform-terraform-logging/pull/28/
> Bump logging module which enable fluent-bit on Nodegroup ingress-nodes

- smoke-tests/spec/daemonsets_spec.rb
The ingress-nodes have fluent-bit enabled and hence the fluent-bit tests has to include all_nodes.
> Check all nodes for fluent-bit pods integration tests

- terraform/cloud-platform-eks/components/components.tf
The module 0.1.0 uses latest chart ingress-nginx version 3.6.0
> Upgrade ingress controller of EKS to module 0.1.0

- terraform/global-resources/elasticsearch.tf
- terraform/global-resources/guardduty.tf
Both the main and the audit cluster are showing
"ClusterIndexWritesBlocked", and not recording any data.
This change should double the disk space for all cluster nodes.
This is not sufficient to fix the problem. After the disk space is
available, we also need to take the clusters out of read-only mode as
described in this blog post:
https://engineeernitesh.blogspot.com/2019/12/elasticsearch-error-clusterblockexcepti.html
> Increase EBS volume for ES clusters

- terraform/cloud-platform-components/components.tf
- terraform/cloud-platform-eks/components/components.tf
- Latest monitoring module has include Thanos condition (we don't want it in test clusters, it is only for prod clusters)
- Updated stable repo to the new URL (more info https://helm.sh/blog/new-location-stable-incubator-charts/ )
> Updated monitoring module to latest

- terraform/cloud-platform-account/main.tf
In order to solve our issue with Dockerhub API rate limits (ONLY IN EKS SIDE), we are testing the possibility of mirroring the public repositories. This is a start with fluentbit
> Added fluent-bit repository

- terraform/cloud-platform-components/components.tf
- terraform/cloud-platform-eks/components/components.tf
This change does two things:
- Update fluent-bit to the latest version
- Set ECR mirror repository ONLY in the EKS side.
> New release logging module

- destroy-cluster.rb
This change allows the name of the cluster to be supplied as **either**
of:
* foobar
* foobar.cloud-platform.service.justice.gov.uk
This makes it easier to copy and paste the cluster name from the
output of `kops get clusters`
> Accept long cluster name, for destroy

- cloudformation/aws-limit-monitor/limit-monitor.template
WHAT
Limit-monitor is uses AWS Trusted Advisor limits to alert on resource usage
Warning - 80%
Error - 100%
WHY
To alert the team that resource limit is being reached.  
The job will run ~11am daily and alert in the lower-priority channel for Warning and Error. Platforms email address will also get an email up on an Error alert.
> Update limit-monitor schedule and Runtime version 

- terraform/cloud-platform-components/main.tf
- terraform/cloud-platform-eks/components/main.tf
- terraform/cross-account-IAM/main.tf
Overview
---
This PR links to https://github.com/ministryofjustice/cloud-platform/issues/2132 and relates to the Helm Terraform provider upgrade work across all cloud-platform-* repositories.
To see the comparison between versions, please see [here](https://github.com/hashicorp/terraform-provider-helm/compare/v1.1.1...v1.3.2)
Testing
---
I have completed an init and plan in all three Terraform states and they came up clean.
> Update Helm Terraform provider to 1.3.2

- terraform/global-resources/elasticsearch.tf
WHAT
Increase number of nodes on live1 es cluster to 15
WHY
The minimum free space on a node was below the threshold of 20GB
> Increase es nodes live1 to 15
